### ISSUE TITLE
[Bug] Keyboard stays open after closing nav drawer

### ISSUE THREAD

**Issue by SlayterDev** [Memmy-App/memmy#1000]
### Check for open issues

- [x] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

1. Open Nav drawer (hamburger menu)
2. Tap search bar to present keyboard 
3. Tap right side to return to feed
4. Keyboard stays open 

### Expected Behavior

Keyboard dismisses when leaving nav drawer

### Version

0.5.1.1

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPhone 14 Pro Max

**Comment by gkasdorf** [comment]
Fixed now.
