### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by succip** [Memmy-App/memmy#1002]
### Check for open issues

- [ ] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

In the main feed, swiping from the left to open the communities list forces a post to open from the main feed (it opens the comments). This happens one time then you can open the communities list as expected. 

### Expected Behavior

I expect the communities list to open instead of a post comments. 

### Version

0.5.1.1

### App Store or TestFlight?

App Store

### iOS Version

17.x Beta

### Device

iPhone 14 Pro

**Comment by eoddc5** [comment]
No title. No check on duplicate search.
