### ISSUE TITLE
[Bug]: Listing type defaults to ‘All’ instead of ‘Subscribed’

### ISSUE THREAD

**Issue by mr00z** [Memmy-App/memmy#1003]
### Check for open issues

- [x] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

I have default listing type set to ‘Subscribed’, but it looks like this feature ceased to work for me - I’m always getting ‘All’ listing in my feed.

### Expected Behavior

I’m getting the listing set in settings as a default one.
![IMG_3920](https://github.com/Memmy-App/memmy/assets/22932530/c7d27a45-fb59-42b7-b188-dfeac3ee1554)
![IMG_3922](https://github.com/Memmy-App/memmy/assets/22932530/4c39f944-08ba-41d6-9421-038ba73094cc)

### Version

0.6.1

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 13

**Comment by jderose9** [comment]
I'm seeing the same behavior.

**Comment by swemoney** [comment]
Also seeing the same behavior

**Comment by gkasdorf** [comment]
This is fixed now.
