### ISSUE TITLE
[Bug]: Hostname is replaced with IP when sharing to iMessage

### ISSUE THREAD

**Issue by crickford** [Memmy-App/memmy#1004]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

When I shared this post https://lemmy.sdf.org/post/2525413 with a friend via iMessage (from my account on a different lemmy instance), the link was rewritten as http://10.1.1.7/post/2525413 🤷

### Expected Behavior

The URL to the post on the original instance is shared

### Version

0.5.1.1

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPhone SE 2020

**Comment by eoddc5** [comment]
Have you tried sharing other links and gotten the same behavior?

I’ve shared a ton and never had this issue

if this is a one off, I dunno. If this is doing it for all links you share then that’s something different

**Comment by crickford** [comment]
Yeah maybe some very specific quirk. I’ve also shared lots of others, this is the only link that I’ve seen this issue with.

**Comment by damoun** [comment]
Your instance must have configured something wrong on their lemmy server.

**Comment by gkasdorf** [comment]
That would be some issue with the configuration of the instance. You can look in (I believe) config.hjson to see what the AP ID is. They likely misconfigured this when using Ansible.
