### ISSUE TITLE
[Bug]: multiple rows saying no post found when visiting community from search 

### ISSUE THREAD

**Issue by kingcong1** [Memmy-App/memmy#1007]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

![IMG_5499](https://github.com/Memmy-App/memmy/assets/70293657/4ad70a1b-19a8-4770-a2e5-a459d81ac600)

When searching and opening a community, it shows multiple rows of no posts found

### Expected Behavior

Should show posts but shows no posts found

### Version

0.6.1 (1)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

12

**Comment by gkasdorf** [comment]
Shoudl be fixed now.
