### ISSUE TITLE
[Bug] Can't clear stuck notification 

### ISSUE THREAD

**Issue by Jordybeer** [Memmy-App/memmy#1009]
### Check for open issues

- [ ] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

> Open Memmy
> Go to inbox
> Click on 'unread' notification 

![IMG_4339](https://github.com/Memmy-App/memmy/assets/19562111/7814e2a8-5056-4e69-b618-5d341a41fc92)

### Expected Behavior

Get redirected to the specific comment and thereby clearing the inbox, removing the upper right  red dot.

### Version

0.6.1.1

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPhone X

**Comment by damoun** [comment]
You must be on lemmy.world instance, isn't it ? To me it looks like your instance is blocking memmy push server.

**Comment by gkasdorf** [comment]
This is fixed now.
