### ISSUE TITLE
[Bug]: fast multiple “Submit” press will send multiple requests

### ISSUE THREAD

**Issue by felix-staud** [Memmy-App/memmy#1011]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Create a new comment.
Go Ham on the “Submit” button by clicking it multiple times. The comment will be created multiple times.

### Expected Behavior

Should only submit once.

### Version

0.6.1.1

### App Store or TestFlight?

App Store

### iOS Version

17.x Beta

### Device

iPhone 13

**Comment by gkasdorf** [comment]
Submit buttons are now disabled after requests are made.
