### ISSUE TITLE
[Bug]: url encoded links sometimes not resolving properly

### ISSUE THREAD

**Issue by Dhammiko** [Memmy-App/memmy#1012]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

https://derp.foo/post/257727 example post containing encoded url, instead of decoding the url memmy is dropping everything after the first % so the target link ends up 404'ing

### Expected Behavior

urls should be run through a decoder function before attempting to be followed

https://www.w3schools.com/tags/ref_urlencode.ASP

### Version

0.5.1 (1)

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iphone 7 :)

**Comment by gkasdorf** [comment]
Going to be reworking the whole system.
