### ISSUE TITLE
[Bug]: "Mark as read" not working as intended and other bugs

### ISSUE THREAD

**Issue by RandomUsername404** [Memmy-App/memmy#1018]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

1. Toggle these on and open a post:
![read toggles](https://github.com/Memmy-App/memmy/assets/18629430/dab69502-2863-4cde-8cf3-e7ad6f8bb7fe)
It will not be marked as read. None of these options work. 

2. NSFW toggles not working as intended:
![NSFW toggles](https://github.com/Memmy-App/memmy/assets/18629430/ce5e70ca-0006-4e94-8508-658b5c66ee14)
I have NSFW enabled so the first toggle should be on. Trying to toggle it doesn't do anything. 
the blur toggle doesn't work. It stays off. 

3. Erratic behaviour with these toggles:
![avatar toggles](https://github.com/Memmy-App/memmy/assets/18629430/0f695cc9-818a-4893-9bbb-e5a3c4bb831b)
Both can get stuck and appear as being toggled when clearly they aren't (avatar and/or name not showing). 

4. Confusing posts timestamp:
![timestamp](https://github.com/Memmy-App/memmy/assets/18629430/0bb74961-40c1-4588-b7e5-778765793633)
It means "38 days ago", I suppose?

### Expected Behavior

1. Post is marked as read. 

2. The first toggle displays correctly our Lemmy account's NSFW setting. The second one can be toggled on and off. 

3. They should work as intended. 

4. It should display the time in a "legible" manner. 

### Version

1.0.40 (40)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 7

**Comment by felix-staud** [comment]
I think most of those are known issues right now. There was a major rework recently and some of the former feature/button have to still be re-integrated. Please be patient and keep an eye out for the future patches

**Comment by gkasdorf** [comment]
Yup, I'll have these resolved in the coming days. Thanks for putting them here though, helps to at least not lose track of things!

**Comment by gkasdorf** [comment]
Fixed now.
