### ISSUE TITLE
[Bug]: When in your comments, tapping a comment no longer goes to it’s context thread 

### ISSUE THREAD

**Issue by asciiletters** [Memmy-App/memmy#1019]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Click the middle button can go to Comments. Tap a comment and nothing happens. 

### Expected Behavior

It should go to the comment in the context of the thread where it was submitted. 

### Version

Latest beta

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

Latest iPhone

**Comment by gkasdorf** [comment]
To clarify this is happening on the inbox screen? I'm going to be taking a look at some issues tonight so I'll fix this.

**Comment by gkasdorf** [comment]
Fixed somewhat, needs tweaking for deeply nested comments. Will work on this along with other issues. https://github.com/Memmy-App/memmy/commit/a600c895d03fe041ad4277dc9d22476948b5360b

**Comment by asciiletters** [comment]
Similar to this one, when you go to comments under inbox, tapping on those comments doesn’t work either. It just keeps loading and says undefined.

**Comment by gkasdorf** [comment]
Should be fixed now. Not going to close yet, as there are some things that need to get fixed still with it, but it is mostly functional.

**Comment by asciiletters** [comment]
When I tap a comment that someone made to me in my inbox now, it goes to the top of thread in question and not the the persons comment, so I can see what I said that they are responding to.

**Comment by gkasdorf** [comment]
Fixed.
