### ISSUE TITLE
[MEM-91] Persist user-selected feed when opening app

### ISSUE THREAD

**Issue by ammacdonald3** [Memmy-App/memmy#102]
**Is your feature request related to a problem? Please describe.**
The app defaults to the "All" feed. After choosing "Subscribed" and reopening the app, it reverts back to "All".

**Describe the solution you'd like**
Persist the user-selected feed to display on initial app opening.

**Describe alternatives you've considered**
- Add a setting where the user chooses the default view
- Display whichever view was most recently used

**Additional context**
N/A

<sub>[MEM-91](https://linear.app/memmyapp/issue/MEM-91/persist-user-selected-feed-when-opening-app)</sub>

**Comment by gkasdorf** [comment]
As a user would you prefer the setting to set your default and have it reset to that on every launch or to remember your previous? I can add an option for both too I suppose.

**Comment by ammacdonald3** [comment]
Thanks for asking for input! I'd probably recommend a toggle in settings with options:

- All
- Local 
- Subscribed
- Last Selected

That way, it blends both paths but makes it clear to the user which is being used. If you take this approach, I'd still recommend defaulting to "Last Selected" as the initial selection.

**Comment by gkasdorf** [comment]
> Thanks for asking for input! I'd probably recommend a toggle in settings with options:
> 
>     * All
> 
>     * Local
> 
>     * Subscribed
> 
>     * Last Selected
> 
> 
> That way, it blends both paths but makes it clear to the user which is being used. If you take this approach, I'd still recommend defaulting to "Last Selected" as the initial selection.

Good idea. Will implement 👍

**Comment by devmattrick** [comment]
Not sure if this belongs here, but  I think it would also be nice to have these sorts of settings be per-account instead of global in the app.

**Comment by enghseb** [comment]
This issue could be closed, feature has been implanted through the means of default settings.
