### ISSUE TITLE
[Bug]: The unit of measure is missing next to the posted duration.

### ISSUE THREAD

**Issue by asciiletters** [Memmy-App/memmy#1020]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Anywhere where you have the clock and number saying how long a post or comment has existed, it is now not providing h, min, mon, y. 

### Expected Behavior

It needs to provide a unit of measure. Just showing a number without knowing whether it’s months, minutes, etc is not helpful and messes up timed sorting. 

### Version

Latest Beta

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

Latest

**Comment by gkasdorf** [comment]
https://github.com/Memmy-App/memmy/commit/08341f45f9d44bec2ee6db28001b9bf09b686be9
