### ISSUE TITLE
[Bug]: Turning off blur NSFW doesn’t work. It just flips right back. 

### ISSUE THREAD

**Issue by asciiletters** [Memmy-App/memmy#1021]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

In the settings. If you attempt to turn off the NSFW blur feature, it won’t let you. It just flips right back. 

### Expected Behavior

Turn off the blur NSFW feature. 

### Version

Latest beta

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

Latest

**Comment by gkasdorf** [comment]
https://github.com/Memmy-App/memmy/commit/1086550f920dd8363c7a7e213f82532be8c2831a
