### ISSUE TITLE
[Feature]: Get rid of the mouse icon transition in menu changes

### ISSUE THREAD

**Issue by asciiletters** [Memmy-App/memmy#1022]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

I would like the mouse head that appears during some menu changes removed. I don’t particularly like mice and it feels like extra irrelevant clutter when moving between menus. That app was previous very polished. It feels like we took a few steps back. Possible to go back to the old interface elements or make it feel like that again?

### Solution

Remove the mouse in transitions between menus. 

### Alternatives

Make it an option. Although I feel it should be the default to have it removed instead of the exception.

**Comment by gkasdorf** [comment]
https://github.com/Memmy-App/memmy/commit/c4d852c1aa46ded69420907dd410887040991edb
