### ISSUE TITLE
[Bug]: The information bar under comments are missing

### ISSUE THREAD

**Issue by asciiletters** [Memmy-App/memmy#1024]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

It no longer shows when a comment was posted or let’s you use upvote or downvote button icons on a comment or bookmarks comments or share permalink on comment. The narrow bar under each comment is missing. The most important missing feature is knowing when the comment was posted.  

### Expected Behavior

The narrow bar under the comment is missing. See previous builds that used to have it. 

### Version

Latest beta

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

Latest

**Comment by gkasdorf** [comment]
Yea, will be adding that here in a few minutes. Thanks.

**Comment by gkasdorf** [comment]
Sharing and save are in the context menu. Voting buttons can be enabled under appearance.
