### ISSUE TITLE
[Bug]: Filters button doesn’t work

### ISSUE THREAD

**Issue by asciiletters** [Memmy-App/memmy#1025]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Filters under setting doesn’t work when pressed. Nothing happens.  

### Expected Behavior

Goes to filters menu.

### Version

Latest beta

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

Latest

**Comment by gkasdorf** [comment]
https://github.com/Memmy-App/memmy/commit/1645b5db0e7be948fdcea7f41ad99df2621cb49e
