### ISSUE TITLE
[Feature]: Once in the comments section, tapping the picture won’t invoke the image viewer

### ISSUE THREAD

**Issue by asciiletters** [Memmy-App/memmy#1027]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

I want tapping the post picture to have the same functionality regardless of whether you are in a posts area or the comments section of a post and tap the image at the top.

### Solution

Tapping an image or video anywhere should open it in a viewer or media player. 

### Alternatives

N/A

**Comment by gkasdorf** [comment]
Fixed.
