### ISSUE TITLE
[Bug] When tapping to edit a comment it opens the reply box

### ISSUE THREAD

**Issue by Levsgetso** [Memmy-App/memmy#1029]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

When pressing the “edit comment” button from the drop-down menu on the comment, it opens the reply box to that comment.

### Expected Behavior

Taking you to an editing box to edit your comment

### Version

1.0 (46)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iPhone SE 2

**Comment by gkasdorf** [comment]
Fixed
