### ISSUE TITLE
[Bug]: Getting unknown error when upvoting in a community that I’m banned in

### ISSUE THREAD

**Issue by asciiletters** [Memmy-App/memmy#1031]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

It used to know that I was banned from a community and show that in the error for why upvoting a post their didn’t work. Now it says unknown error. 

### Expected Behavior

It should know the reason that the vote did not work. 

### Version

Latest

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

Latest

**Comment by gkasdorf** [comment]
Wonder if none of the errors work...let me take a look. Thanks.

**Comment by gkasdorf** [comment]
Fixed this one. I'll need to take a look and see if any other codes changed at some point. Let me know if you run into more.
