### ISSUE TITLE
[Bug]: The bold, italics, and quote button don’t work in the editor

### ISSUE THREAD

**Issue by asciiletters** [Memmy-App/memmy#1032]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

The bold, italics, and quote button don’t work in the editor

### Expected Behavior

They should add the proper characters around the text. 

### Version

Latest

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

Latest

**Comment by gkasdorf** [comment]
Fixed
