### ISSUE TITLE
[Bug]: When inputting large replies, there is a character limit  

### ISSUE THREAD

**Issue by asciiletters** [Memmy-App/memmy#1033]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

I wrote a long reply and after a certain point, I could no longer see the words that I was writing since it wouldn’t move to the next line. The works were there, but off the screen. 

### Expected Behavior

You should be able to see the text of your reply as you are typing it and shouldn't have a solution were your cursor falls off the screen. 

### Version

Latest 

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

Latest

**Comment by gkasdorf** [comment]
Hmm weird. Will fix that now. Thanks!

**Comment by gkasdorf** [comment]
Fixed now.
