### ISSUE TITLE
[Bug]: Clicking the negative space after a user name on a post loads the user page 

### ISSUE THREAD

**Issue by flames5123** [Memmy-App/memmy#1035]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Compact view. Show user names and thumbnails. 

Clicking the negative space after a user name on a post loads the user page, even very far away from the user name. 

### Expected Behavior

The post should be loaded, not the user page.

### Version

1.0

### App Store or TestFlight?

App Store

### iOS Version

17.x Beta

### Device

iPhone 13 Pro Max

**Comment by gkasdorf** [comment]
👷Fixed 👍
