### ISSUE TITLE
[Bug]: NSFW blur not working on gifs

### ISSUE THREAD

**Issue by GaloisGhost** [Memmy-App/memmy#1042]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Just scrolling through the All feed encountered posts from a NSFW community. (lemmit.online/c/gonewild) The images were blurred the gifs were not.

### Expected Behavior

All NSFW to be blurred

### Version

1.0.59

### App Store or TestFlight?

App Store

### iOS Version

17.x

### Device

iPhone xr

**Comment by gkasdorf** [comment]
Yea, I am aware of this. I'm going to look into if/how I can get the image library to support this and if not will need to do a bit of a workaround. Thanks.

**Comment by GaloisGhost** [comment]
This appears to be fixed in 1.1.78

**Comment by gkasdorf** [comment]
@GaloisGhost Thanks for the heads up. Looks like a few changes made to Expo Image did fix that issue (was not the intention, but good to see).
