### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by efwis** [Memmy-App/memmy#1045]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Cannot easily switch between instances using the quick switch function with the long hold of account icon

### Expected Behavior

Allowing to switch between instances with long hold

### Version

1.0

### App Store or TestFlight?

App Store

### iOS Version

17.x

### Device

iPhone 11

**Comment by gkasdorf** [comment]
Are you not getting the context menu to switch accounts? Or is something else happening there? Testing now on the App Store build seems to work for me.

**Comment by efwis** [comment]
I long hold the icon and the only instance that appears is the current one I’m on even though I have both instances I’m signed up on signed in. 
![Uploading IMG_0771.jpeg…]()

**Comment by gkasdorf** [comment]
@efwis I'm assuming you submitted the comment before the image uploaded😅

Anyway just from the comment I think I *might* know an issue that's going on. Will take a look now. Thanks.

**Comment by efwis** [comment]
![IMG_0771](https://github.com/Memmy-App/memmy/assets/105600820/4c163ac3-40a1-495b-8a99-281fb2440a4c)
I did sorry gavin

**Comment by gkasdorf** [comment]
Thanks. And both of these accounts show up separately under Accounts in settings?

I added the subtitles back so you can differentiate between the different accounts in the context menu, but it shouldn't have prevented each of the accounts from showing up.

**Comment by efwis** [comment]
No they are not both listed for some reason. I logged out of one to log into the other but it’s not saving the one I log out of as far as ai can tell

**Comment by gkasdorf** [comment]
Oh so that's where the issue is at then. Thanks, will check now.

Are both accounts using the same username just a different instance?

**Comment by efwis** [comment]
Found my problem. I didn’t realize you changed the add accounts part. That was my bad. Although it would be nice to tell which instance is which since I use the same username on both instances

**Comment by gkasdorf** [comment]
> Found my problem. I didn’t realize you changed the add accounts part. That was my bad. Although it would be nice to tell which instance is which since I use the same username on both instances

Oh ok cool. And I've already done that, should be on the App Store in a day or so 👍

**Comment by efwis** [comment]
Awesome I went ahead and marked as closed on my end
