### ISSUE TITLE
[Bug]: Instance switching

### ISSUE THREAD

**Issue by Hazardous544** [Memmy-App/memmy#1046]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

After long press, it only shows account names, not instance names as it used to.
![IMG_4912](https://github.com/Memmy-App/memmy/assets/15476634/c17ed7ea-f7c5-49be-bdb1-0afe65db87a8)

### Expected Behavior

Prior to the update, you could long press account and see instance names to choose what instance we would want to view. Now in this version, it only shows account names.

### Version

1.0

### App Store or TestFlight?

App Store

### iOS Version

17.x

### Device

iPhone 15 Pro Max

**Comment by Hazardous544** [comment]
The same issue shows up in Settings > Accounts > long press on username. It only has account name options not instance options.

**Comment by gkasdorf** [comment]
Oh I see that the instance name is not visible there, and I'm guessing you have the same username across all those instances. I'll add the subtitle back in. Missed that.
