### ISSUE TITLE
[Bug]: Compact not being marked read when post viewed

### ISSUE THREAD

**Issue by gkasdorf** [Memmy-App/memmy#1049]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

NA

### Expected Behavior

NA

### Version

NA

### App Store or TestFlight?

App Store

### iOS Version

17.x

### Device

NA

**Comment by flames5123** [comment]
When will this be shipped? This is still a bug in 1.1.3.89.

**Comment by gkasdorf** [comment]
> When will this be shipped? This is still a bug in 1.1.3.89.

To be honest I think this was closed on accident. I’ll have it done today though, sorry about that.

**Comment by gkasdorf** [comment]
Fixed now 👍
