### ISSUE TITLE
[Feature]: Swipe to Share

### ISSUE THREAD

**Issue by MaximilianZenz** [Memmy-App/memmy#1051]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

I would like to have the option that besides upvote, downvote, save, hide and reply that there is also an option so share the post.

### Solution

Add an additional option to the gestures menu that triggers the share post option.

### Alternatives

At least it would be great to have a share post button directly in the feed without having to open a post or press the 3 dot button.

**Comment by gkasdorf** [comment]
Done.
