### ISSUE TITLE
[Bug]: Comment reply button will trigger post reply

### ISSUE THREAD

**Issue by MaximilianZenz** [Memmy-App/memmy#1052]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Enable the comment buttons. O n any post and press the reply button on the comment.

### Expected Behavior

It will open the reply dialog but as a post reply and not a comment reply

### Version

1.0.59

### App Store or TestFlight?

App Store

### iOS Version

17.x

### Device

iPhone 12 Pro Max

**Comment by gkasdorf** [comment]
This is fixed already, updated should be out on the store within the next day. 👍 Thanks!
