### ISSUE TITLE
[Bug]: posts not marked as read for On Feed Scroll

### ISSUE THREAD

**Issue by nerdmann** [Memmy-App/memmy#1066]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Mark as read doesn‘t work for „On Feed Scroll“. It works for „On Post Open“, so I know it‘s not the hiding read posts feature that isn‘t working.

- enable Marking Read -> On Feed Scroll
- disable Show Read Posts
- scroll through feed (Subscribed)
- refresh feed (e.g. by pull-to-refresh or restart app)

### Expected Behavior

Posts should be marked as read and not shown after refreshing feed

### Version

1.1.1.81 (81)

### App Store or TestFlight?

App Store

### iOS Version

17.x

### Device

iPad Air 3rd Gen

**Comment by gkasdorf** [comment]
I noticed this too, looks like a small regression. Will address it today.
