### ISSUE TITLE
[Bug]: Images from private instance not loading

### ISSUE THREAD

**Issue by aapokiiso** [Memmy-App/memmy#1074]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

1. Create a private Lemmy instance or mark an existing instance private.
2. Make a post with an image to this instance, for example using Memmy.
3. View the new post in Memmy. 

The image will be stuck loading, probably because the JWT cookie is not passed alongside the image request when it is loaded. 

### Expected Behavior

Images from a private instance should load if the user has access to them.

### Version

1.1.2

### App Store or TestFlight?

App Store

### iOS Version

17.x

### Device

iPhone 13

**Comment by gkasdorf** [comment]
@aapokiiso Oh I wasn't even aware that was a feature. Figured the images might still be publicly accessible.

Does the JWT need to get passed along in the header for the image request?

**Comment by aapokiiso** [comment]
@gkasdorf Yep, looks like it 👍 

Without a JWT
```
$ curl -sD - -o /dev/null https://<private-instance>/pictrs/image/1c1f32ca-7e49-4924-b3ba-047a3c2d4755.jpeg?format=webp

HTTP/2 502
server: nginx
date: Wed, 08 Nov 2023 07:44:54 GMT
content-type: text/html
content-length: 150
```

With a valid JWT
```
$ curl -H "Cookie: jwt=<jwt>" -sD - -o /dev/null https://<private-instance>/pictrs/image/1c1f32ca-7e49-4924-b3ba-047a3c2d4755.
jpeg?format=webp

HTTP/2 200
server: nginx
date: Wed, 08 Nov 2023 07:45:29 GMT
content-type: image/webp
accept-ranges: bytes
access-control-expose-headers: content-type, accept-ranges, transfer-encoding, date, cache-control, last-modified
cache-control: public, max-age=604800, immutable
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
last-modified: Wed, 08 Nov 2023 07:42:56 GMT
referrer-policy: same-origin
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
```

**Comment by gkasdorf** [comment]
Cool. No big deal, will just need to do a check to see if the logged in instance hostname matches that of the image path and add in the cookie header (strangely `Authorization` doesn't work here, at least not for uploads, so I assume this is the same) with the request. Probably will knock that out tonight before I head to sleep, fairly trivial.

Thanks for the info, never would have realized that one on my own 😅

**Comment by gkasdorf** [comment]
This should fix it https://github.com/Memmy-App/memmy/commit/32b65909bb8ad661e56a6969f194cbee678bbbbf

If it doesn't feel free to open another issue. I don't know of a private instance to test on so...

**Comment by aapokiiso** [comment]
@gkasdorf Just updated to the latest build and yes, it fixes it! Thank you for the extremely quick response 🙏
