### ISSUE TITLE
Floating button to jump to next comment

### ISSUE THREAD

**Issue by MrSuttonmann** [Memmy-App/memmy#111]
**Is your feature request related to a problem? Please describe.**
Almost accessibility related but in Apollo there was a nice button when viewing a post to scroll up and down to the next/previous root comment. 

**Describe the solution you'd like**
A button in the bottom right of the screen when viewing a post to scroll the page down to the next root comment when short pressed, and to scroll up to the previous root comment when long pressed. 

**Describe alternatives you've considered**
I haven't, to be honest.

<sub>[MEM-92](https://linear.app/memmyapp/issue/MEM-92/button-to-quickly-screen-to-next-root-comment)</sub>

**Comment by gkasdorf** [comment]
Ohh I like this one. I'll add it on the list. Thanks!

**Comment by theycallmebeez** [comment]
This will be great for reading threads with tons of comments!

**Comment by sgriff96** [comment]
Finally working on this :D

**Comment by theycallmebeez** [comment]
Going to Next root comment as regular tap and Previous as long-tap worked nicely in Apollo. 

Also ability to set the location of the button is something nice but could be future enhancement. 😊

**Comment by Felix-Staud** [comment]
> Finally working on this :D

Is there an update on this?

**Comment by sgriff96** [comment]
Yea, it's blocked until Gavin finishes some comment changes. He might've finished them tonight though.
