### ISSUE TITLE
[MEM-55] Sort post comments 

### ISSUE THREAD

**Issue by ninawired** [Memmy-App/memmy#124]
Add the ability to sort the comments on a post by new, hot, top etc the same as post sorting. 

<sub>[MEM-55](https://linear.app/memmyapp/issue/MEM-55/sort-post-comments)</sub>

**Comment by Mereo** [comment]
When this feature is implemented, Memmy will become in my opinion, THE Lemmy app to use.

**Comment by ktgd** [comment]
#286 
This was merged in today and will be available in the next update.
