### ISSUE TITLE
[MEM-56] Landscape mode

### ISSUE THREAD

**Issue by ninawired** [Memmy-App/memmy#125]
**Is your feature request related to a problem? Please describe.**
Not really, I just noticed that in landscape mode the content is there but only partial width of the screen. 

**Describe the solution you'd like**
A layout designed to for reading with phone in landscape mode with ability to switch between card or compact view 

<sub>[MEM-56](https://linear.app/memmyapp/issue/MEM-56/landscape-mode)</sub>

**Comment by b-bayport** [comment]
Wow I'm not getting landscape mode at all. I'm on v0.0.2.5 at the moment. 
Landscape mode would be nice to have

**Comment by gkasdorf** [comment]
I disabled it temporarily while I fix up some issues with the rendering. It will be back. It is available on iPad though.

I'll put it back on in the coming days. Not a permanent thing.

**Comment by gkasdorf** [comment]
No longer an issue.
