### ISSUE TITLE
[MEM-57] Make subscription page more visible e.g in search

### ISSUE THREAD

**Issue by ann0see** [Memmy-App/memmy#128]
**Is your feature request related to a problem? Please describe.**

Currently the subscribed communities view is quite hidden in the feed tab behind the star. Personally I'm interested in navigating to a specific community quickly.

I think the current way is not visible and unintuitive. I suggest to use another more visible way to jump to a subscribed community.

**Describe the solution you'd like**

I think there are multiple solutions:

* Have a separate tab called communities.
* Include Communities in search tab (my preference, but this mixes concepts)
* Rename Feed to Posts like in Apollo and behave comparably

**Additional context**
Apollo start page:

![](https://uploads.linear.app/7655b776-38c4-4273-b069-78045fe3cd9c/e4590ce5-d554-4a4d-a512-a06780361908/ec97aafa-423f-406f-a0d5-336a98ab6641)

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-57](https://linear.app/memmyapp/issue/MEM-57/make-subscription-page-more-visible-eg-in-search)</sub>

**Comment by teflocarbon** [comment]
A communities tab has been mocked up but hasn't been implemented yet. It should be implemented in the near future.
