### ISSUE TITLE
[MEM-61] Add option for GitHub Sponsors

### ISSUE THREAD

**Issue by b-bayport** [Memmy-App/memmy#139]
**Is your feature request related to a problem? Please describe.**
Nope 

**Describe the solution you'd like**
Would like the option to support this project thru GitHub sponsors. 
This is in addition to the current "Buy me a coffee" option.  
Reference: https://github.blog/2020-03-24-getting-started-with-github-sponsors/

**Additional context**
Thanks for all your hard work!  Please don't burn yourself out

<sub>[MEM-61](https://linear.app/memmyapp/issue/MEM-61/add-option-for-github-sponsors)</sub>

**Comment by gkasdorf** [comment]
I will look into the best way to do this.
