### ISSUE TITLE
[MEM-63] [BUG] switching accounts does not have an effect

### ISSUE THREAD

**Issue by B0rax** [Memmy-App/memmy#142]
**Describe the bug**
I have two accounts on different instances with different subscriptions.
Switching to the second account still shows all subscriptions and servers from the first account. I am not able to see the subscriptions of the second account at all.

**To Reproduce**
Sign in with two different accounts (I am on two different instances)
Try to switch between them

**Expected behavior**
On account switching I would expect that the home feed reloads and shows the one applicable for this account.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 16.5.1
 - Version 0.0.1 (66)

<sub>[MEM-63](https://linear.app/memmyapp/issue/MEM-63/[bug]-switching-accounts-does-not-have-an-effect)</sub>

**Comment by gkasdorf** [comment]
Can you try switching between them again? This was probably a network issue.

Regardless, I'm rewriting this screen as we speak, and there will be a pull to refresh incase of network issues.

**Comment by B0rax** [comment]
I tried to switch accounts multiple times. But it never shows anything different than my first account.
Network should be working fine (I am on a stable WiFi right now)

**Comment by gkasdorf** [comment]
Hmm interesting. What instance is this happening on? I'll look into it.

**Comment by B0rax** [comment]
The instance that is not getting loaded is lemmynsfw.com

**Comment by gkasdorf** [comment]
@B0rax Sorry for the late response. Can you try disabling the NSFW filter and see if that works. Might need to do something for per-account NSFW filters.

**Comment by eoddc5** [comment]
@B0rax can you update the status of this bug?

**Comment by B0rax** [comment]
Still not working. It still shows the feed of the first account when switched to the second account. 
Toggling the NSFW filter in settings does not solve this problem.

**Comment by ebits21** [comment]
Try re-installing? Accounts work fine for me from that instance.

**Comment by B0rax** [comment]
Reinstall seems to have fixed it. Thanks!
