### ISSUE TITLE
[MEM-73] [Feature request] Show community instance when browsing All or Subscribed

### ISSUE THREAD

**Issue by JohnPaton** [Memmy-App/memmy#169]
**Is your feature request related to a problem? Please describe.**

When I'm browsing All or Subscribed posts, I have to click into the post comments to see which instance the community is from. (In Local it's obvious of course).

**Describe the solution you'd like**

When I'm browsing All or Subscribed posts, I'd like to be able to see which instance the community is from on the post card, so I don't have to expand it to find out. I use the compact layout if it matters. 

**Describe alternatives you've considered**
This could be opt in

<sub>[MEM-73](https://linear.app/memmyapp/issue/MEM-73/[feature-request]-show-community-instance-when-browsing-all-or)</sub>

**Comment by yrahul3910** [comment]
I could probably work on this, although we need to consider where to display this when the feed is in Compact mode. Alternatively, perhaps we simply do not show the instance in Compact mode?

**Comment by JohnPaton** [comment]
For me personally I'm only interested in Compact mode, not enough overview with the big cards for me (I realize a lot of people prefer them). It could go beside the age of the post? Or else just append to the name of the community, but truncate if it's too long like you do with usernames?

**Comment by sgriff96** [comment]
We have a UI designer @teflocarbon that works on the designs. Would want to involve him before making a change like this.

**Comment by eoddc5** [comment]
Medium priority assigned. Would work like “show instance for usernames” currently does

now that the redesign of text placements, the choice is easy for where to put the @

**Comment by gkasdorf** [comment]
I think this is the current functionality.
