### ISSUE TITLE
[MEM-68] [BUG] Crash when collapsing comment thread in this post

### ISSUE THREAD

**Issue by JeremyLeland** [Memmy-App/memmy#174]
**Describe the bug**
Collapsing the first comment thread in this post seems to lead to a crash.

**To Reproduce**
1. Go to https://lemmy.world/post/85123 (on Lemmy World, sort by "Most Comments" and scroll down to the "196" community's "important rulepost" with the cartoon of the lady punk punching the male punk that says "kick tankies out of 196")
2. Collapse the first comment thread (starship_lizard's "What's a tankie?")

Note that no other comment threads are visible yet (there should be more). Before any more appear...

3. Tap collapsed thread to try to un-collapse it

Nothing happens

4. Tap "Feed" in upper left to return to feed
5. Tap "important rulepost" again to reload

**Expected behavior**
Should be able to collapse, expand, go back to feed, reopen post, etc without problems

**Actual behavior**
This sequence often (though not always) causes Memmy to crash for me. (If it doesn't do it the first time, trying it again a few more times usually produces a crash).

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 16.5.1
 - Version 0.0.1 (72)

Crash report submitted.

**Logs**
[1687813179312] Clearing instance.
[1687813179312] Attempting to initialize instance. lemmy.world
[1687813179312] Already authenticated. Using existing authentication token.

**Additional context**
I can record a video if that helps.

<sub>[MEM-68](https://linear.app/memmyapp/issue/MEM-68/[bug]-crash-when-collapsing-comment-thread-in-this-post)</sub>

**Comment by JeremyLeland** [comment]
Now that I'm trying to catch it on video, of course, I can't get it to crash. However, lots of weird slow loading issues when collapsing various comments in that post. Maybe something is happening out of order, or trying to use something that isn't loaded yet?

**Comment by gkasdorf** [comment]
@JeremyLeland Yea, it's just because of the sheer number of comments in that thread. Too many to be rendering and unrendering at once. This will be resolved once I properly implement comment chains (in the same way Apollo does, taking you to a different screen to view the whole thread.

**Comment by gkasdorf** [comment]
Fixed in next update.
