### ISSUE TITLE
[MEM-67] [Feature Request] Disable Thumbnails and Bold Post Titles

### ISSUE THREAD

**Issue by haderp** [Memmy-App/memmy#182]
**Is your feature request related to a problem? Please describe.**

N/A Feature request. 

**Describe the solution you'd like**

Setting option to disable thumbnails, and option to bold post titles.  

**Describe alternatives you've considered**

Non, accessibility/visual enhancement that would add real estate for the post title when the user has large system fonts and zoom mode enabled. The bold title option would allow for a smaller font choice and also reduce the amount of the screen used by posts.  

**Additional context**
Accessibility option for users that may be visually impaired and use larger than normal fonts so posts don’t consume large portions of the screen. 

<sub>[MEM-67](https://linear.app/memmyapp/issue/MEM-67/[feature-request]-disable-thumbnails-and-bold-post-titles)</sub>

**Comment by eoddc5** [comment]
Post title weight is completed

Low priority assigned for thumbnail

**Comment by gkasdorf** [comment]
Both of these are implemented. For the thumbnail, select "Thumbnail Position -> None".
