### ISSUE TITLE
[MEM-74] Support iOS 14

### ISSUE THREAD

**Issue by sahlaysta** [Memmy-App/memmy#186]
**Is your feature request related to a problem? Please describe.**
TestFlight says I must update my device. I am on 14.7.1.

**Describe the solution you'd like**
Perhaps you could add support for iOS 14 as well.

**Describe alternatives you've considered**
If I update my iOS, I lose TrollStore.

**Additional context**
Is there any way to get it to run without updating?

<sub>[MEM-74](https://linear.app/memmyapp/issue/MEM-74/support-ios-14)</sub>

**Comment by sgriff96** [comment]
We can't really commit to supporting 3 year old iOS versions, sorry. TrollStore might be available on 15.5 though and I believe Memmy works on iOS 15, might be worth looking into.

**Comment by sahlaysta** [comment]
Thank you for supporting the new update on iOS 14.7.1. It is now working.
