### ISSUE TITLE
[MEM-78] Use SecureStore for API token

### ISSUE THREAD

**Issue by jderose9** [Memmy-App/memmy#193]
The attack surface is pretty narrow, but it may be an improvement to use Expo's SecureStore to encrypt the API token rather than AsyncStorage.

I have an example here where I remove the token from the account object and stick it in SecureStore, then merge them back together when I fetch the accounts.

https://github.com/jderose9/lemmy-reader/blob/b8cd74777ba9d79e92300b0584f572d200f76cf5/services/AuthService.ts#L9-L33

If you agree with the approach, I'm happy to open a PR. Thanks!

<sub>[MEM-78](https://linear.app/memmyapp/issue/MEM-78/use-securestore-for-api-token)</sub>

**Comment by gkasdorf** [comment]
This is a good idea. Like you said, very small attack vector but better to be safe than sorry. If you need help figuring out the current disorganized state of things let me know. Still a lot of refactoring to do. Thanks! 👍

**Comment by jderose9** [comment]
@gkasdorf I started working on this but noticed the user password is stored in AsyncStorage currently as well. I would expect that to be discarded after the API token is received on login. From the best I can tell, the Lemmy JWT doesn't expire unless the password is changed, so I think it is safe to stop storing it.. does that sound right to you?

**Comment by jderose9** [comment]
opened #470 to address this.

**Comment by Felix-Staud** [comment]
fix #470

**Comment by Felix-Staud** [comment]
> opened #470 to address this.

You wanna put a comment/edit a comment in your PR mentioning one of those keywords so issue & PR get connected:

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by jderose9** [comment]
Hi @gkasdorf, it seems in the current main branch that the lemmy account password is still stored unnecessarily, and that both the token and password are stored in plain text in AsyncStorage. 

https://github.com/Memmy-App/memmy/blob/183da589bebace027e3bb39ab0ef51669962e14e/src/stores/account/accountStore.ts#L85-L91

Does the PR need to be adjusted to work with recent changes, or otherwise why was it closed? Thank you.

**Comment by jderose9** [comment]
> They are redoing the state management in general right now by implementing [immer](https://immerjs.github.io/immer/) that's why your PR was closed. It's not cause they don't want to fix it but rather to get it right adapted to that

I didn't think they didn't want to fix it, but I also don't want my password stored as it is, so I'm trying to figure out how I can help get it across the finish line. I thought the switch had already happened, and I don't really see much change in how the persistent storage is handled with regards to the state change.

If the answer is just to wait, that's fine, but I didn't want it to get forgotten, either.

**Comment by gkasdorf** [comment]
@jderose9 Honestly this was the best way to remind me...I've completely removed the storing of the passwords now here https://github.com/Memmy-App/memmy/commit/c308c93ec9e17b2bb99818b07602f35cb7166f1d

**Comment by jderose9** [comment]
Thanks so much for knocking that out @gkasdorf !

Is the plan still to store the token in SecureStore? Should I update the PR or just wait?

Thanks again!

**Comment by gkasdorf** [comment]
@jderose9 Yes, I'm finally free for a bit again, and will be overhauling quite a bit of things here. Primarily for this in particular will be the use of Zustand state from the beginning and not using `AsyncStorage` directly, but rather just using persistent state for the user settings and accounts. So we will handle the encryption of the token in there.
