### ISSUE TITLE
[MEM-113] [BUG] Onboarding GUI has wrong font size and text overlaps

### ISSUE THREAD

**Issue by ann0see** [Memmy-App/memmy#220]
**Describe the bug**

The new onboarding looks great! Unfortunately on small devices (SE 1st gen, maybe also \*Mini iPhones?) the text is hidden on some pages:
![image](https://github.com/gkasdorf/memmy/assets/20726856/12ae46c6-0d01-403a-a909-2d18523e761b)

![image](https://github.com/gkasdorf/memmy/assets/20726856/56daca34-a09c-4a03-8bb9-1d2a305e08dd)
![image](https://github.com/gkasdorf/memmy/assets/20726856/d47296bf-6b3f-47ff-9d0e-464a3b1b7910)
![image](https://github.com/gkasdorf/memmy/assets/20726856/a93023d9-bdb6-48d9-a885-8778f3d921ba)
**To Reproduce**
Launch the app on iPhone SE (simulator). 
**Expected behavior**
No text overlap

**Screenshots**
See above

**Smartphone (please complete the following information):**
iPhone SE 1st gen
**Logs:**

N/A

**Additional context**
N/A

<sub>[MEM-113](https://linear.app/memmyapp/issue/MEM-113/[bug]-onboarding-gui-has-wrong-font-size-and-text-overlaps)</sub>

**Comment by ann0see** [comment]
I believe there might also be some other issues in the app while logged in. Not sure.

**Comment by ann0see** [comment]
The last build on testflight still shows these issues - at least on my SE.

**Comment by gkasdorf** [comment]
Do you have font scaling enabled iOS side? It's been super hard to repro this, but it's probably because all I have is a simulator to do it with for this device...

Appreciate your feedback, not really able to see it myself so good that someone is reporting it 👍

**Comment by ann0see** [comment]
iOS dynamic text size is set to two bars from left, if you mean that. I do have access to a mac - this evening. If I can set up the development environment, I can try to help out. Unfortunately, I don't have much experience with expo or Javascript/typescript.

**Comment by ann0see** [comment]
Even with the smallest text size nothing changes.

**Comment by gkasdorf** [comment]
What iOS version is it?

**Comment by ann0see** [comment]
15.7.3

**Comment by gkasdorf** [comment]
Ah maybe I need to test with a lower iOS version perhaps. I'll give it a go here in a bit.

**Comment by ann0see** [comment]
It doesn't like my Apple ID. I'm going to try a local build with Xcode: https://devshogun.medium.com/how-to-build-an-ios-expo-app-without-using-eas-build-78bfc4002a0f but no guarantees - it's getting quite late, so maybe - I can look at it again tomorrow evening.

**Comment by ann0see** [comment]
Unfortunately I had a bunch of dependency errors while trying to set the environment up. 

I think the simulator should also show this issue as it should just depend on the screen size. No currently supported iPhone has the SE 1st gen screen size, so I believe an older iOS version must be tested.
If there's an easy way to get a compiled ipa "from the CI" which is unsigned, I'd be able to debug. (Expo is something like that - I suppose?)
Otherwise - which I think is more time saving would be a (video) chat or a way to send ipa files around between someone who can compile the app.

**Comment by gkasdorf** [comment]
@ann0see If you join the Discord we will help you get set up. Also, that might be the issue as far as it being a SE 1. I think I was testing on an SE 2 and assuming (wrongly) that the screen size was the same.

**Comment by ann0see** [comment]
I think the easiest fix would be making the onboarding views scrollable.

**Comment by ann0see** [comment]
![grafik](https://github.com/Memmy-App/memmy/assets/20726856/b70b18e6-1540-4e99-a434-ae6c3a8217b2)

Should be ok? I *think* I go to this by decreasing the onboarding text size by one in the first screen.

**Comment by eoddc5** [comment]
@gkasdorf @ann0see can either of you update this bug with the latest status

**Comment by eoddc5** [comment]
> 0.4 (2) now has a broken menu bar in German ![image](https://user-images.githubusercontent.com/20726856/254171888-626dac48-ed27-4494-894c-e42c11227a82.jpeg)

Can you open a separate ticket about this? It isn’t relevant to the issue you’re replying to. (I know this one is your own posted issue, but let’s keep the requests / reports separate so they can be properly worked on)

**Comment by gkasdorf** [comment]
> 0.4 (2) now has a broken menu bar in German ![image](https://user-images.githubusercontent.com/20726856/254171888-626dac48-ed27-4494-894c-e42c11227a82.jpeg)

That should also be fixed now, can you confirm? If not I'll work on it some more.

**Comment by ann0see** [comment]
Yes. Seems to be ok now.

**Comment by Felix-Staud** [comment]
Sounds like this issue can be closed?

**Comment by ann0see** [comment]
@Felix-Staud unfortunately not. The onboarding GUI still has these problems. See https://github.com/Memmy-App/memmy/issues/220#issuecomment-1620730888

**Comment by Felix-Staud** [comment]
> @Felix-Staud unfortunately not. The onboarding GUI still has these problems. See [#220 (comment)](https://github.com/Memmy-App/memmy/issues/220#issuecomment-1620730888) which is a potential fix for part of the problem.

We are still taking about IPhone SE 1st gen?

**Comment by ann0see** [comment]
Yes.
* Running on the latest version of iOS for the SE 1st gen
* I tried to set up a development environment, but my VM crashes every X seconds or is unresponsive if I use an up to date version of macOS and Xcode
* To test it on the SE 1st gen simulator, you'll need iOS 15 support, but the latest version of Xcode just needs a download.

**Comment by gkasdorf** [comment]
Fixed now.
