### ISSUE TITLE
[MEM-115] [BUG] Animated GIFs playing at 2x speed

### ISSUE THREAD

**Issue by aesecakes** [Memmy-App/memmy#225]
**Describe the bug**
GIFS uploaded with Memmy from the camera roll on Iphone 13 Pro play at greater speed in Memmy compared to when viewed using Chrome mobile browser

**To Reproduce**
1. Go to my Lemmy profile, aesecakes@lemmy.world using Memmy 
2. Test animated GIFs in post history using Memmy vs Browser
3. View the GIF used in those posts at Imgur. 
![](https://i.imgur.com/hSypMFV.gif)

**Expected behavior**
GIF plays at the speed seen on imgur and when viewing GIF post in a browser. 

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS16.5
 - Version 77

<sub>[MEM-115](https://linear.app/memmyapp/issue/MEM-115/[bug]-animated-gifs-playing-at-2x-speed)</sub>

**Comment by b-bayport** [comment]
Is this a clever way to get more visits to arsecakes profile?

![](https://giphy.com/gifs/its-a-trap-admiral-ackbar-8McNH1aXZnVyE)

**Comment by gkasdorf** [comment]
Fix found here https://github.com/DylanVann/react-native-fast-image/issues/956#issuecomment-1545526634

**Comment by gkasdorf** [comment]
Downgraded. Should be ok now.

**Comment by aesecakes** [comment]
Thank you for looking at this. I just downloaded 0.0.2 (5) and the behaviour of the GIFs hasn’t changed, unfortunately.

**Comment by gkasdorf** [comment]
> Thank you for looking at this. I just downloaded 0.0.2 (5) and the behaviour of the GIFs hasn’t changed, unfortunately.

This is pretty weird. I can view almost all GIFs just fine, but it does seem I run across a few that have issues...

I'll take a look again to make sure that the lib got properly downgraded.

**Comment by gkasdorf** [comment]
I've now ran tests with two different versions of SDImage. I reverted back to 5.1.11 in one build, then in the last one went back to the latest version. This happens when SDImage is > 5.1.11. I will continue to use the downgraded version until that library is fixed.

**Comment by linux2647** [comment]
This is still happening for me. Lemmy 0.6.1, iOS 16.6.1. iPhone 13 Pro. I don’t think I’ve ever seen gifs animate at 1x
