### ISSUE TITLE
[MEM-108] Deep link protocol

### ISSUE THREAD

**Issue by shocklateboy92** [Memmy-App/memmy#230]
Hey, I'm putting together a link redirection service for Lemmy:
https://lemmy.guide

It lets people create links to that will open in their instance (set in browser local storage) in the app of their choice:
https://lemmy.guide/link?target=!programmer_humor@programming.dev

At the moment, I only have Liftoff (and browser, obviously) in there. But I'd love to add more, including Memmy.
Does Memmy have a protocol it's registered to open like say, `memmy://lemmy.world/c/programmer_humor@programming.dev`?

<sub>[MEM-108](https://linear.app/memmyapp/issue/MEM-108/deep-link-protocol)</sub>

**Comment by gkasdorf** [comment]
@shocklateboy92 Hey! Thanks for letting me know. Right now, it is memmyapp://. Go ahead and add it, then I will play with how to manage the redirections in app. If you want to chat on Discord, add me: g_k_d or join the Discord itself and @ me. Thanks!
