### ISSUE TITLE
[MEM-121] Swipe action for saving posts 

### ISSUE THREAD

**Issue by leftbones** [Memmy-App/memmy#231]
I know customization for swipe gestures are off the table for now, but I think a swipe gesture for saving is crucial. I’ve been trying many other Lemmy apps, and they almost all have this feature. 

Ideally, swiping a post left should first bring up the reply option, then swiping further should bring up the save option. Right now, it just does reply and then nothing else. That empty space could be utilized!

<sub>[MEM-121](https://linear.app/memmyapp/issue/MEM-121/swipe-action-for-saving-posts)</sub>

**Comment by gkasdorf** [comment]
If you noticed, there is a second "slot" now for the right->left swipe that is empty. Was thinking of adding it there.

**Comment by leftbones** [comment]
> If you noticed, there is a second "slot" now for the right->left swipe that is empty. Was thinking of adding it there.

Exactly what I meant! That’s where it is on Apollo and most of the other Lemmy apps, it definitely would help with my muscle memory too haha.

**Comment by gkasdorf** [comment]
In your opinion, should it be the first option or the second? I'm fine with either.

I've noticed that we might need to increase the distance for the right-left actions. It seems that's its a bit too easy to miss the first action right now and hit the second one, maybe because I believe Apollo defaulted to reply being the second option rather than the first.

**Comment by leftbones** [comment]
Personally I think the second option is best for saving. It’s easier to do quickly, whereas stopping at the reply option has to be more deliberate.

**Comment by gkasdorf** [comment]
Yea I think I agree.

Here's another question:

Should saved posts be stored locally (as well as being updated on Lemmy) and available to all of your accounts? I.e. if you save something on x@lemmy.ml it will be available in your saved list so you can go to it on y@lemmy.world

**Comment by leftbones** [comment]
Hm that I’m not sure about since I don’t use multiple accounts, maybe someone else could chime in on that. 

I would think that accounts would have separate saves though.

**Comment by InquisicionEspanola** [comment]
Separate saves would be preferred imho.

**Comment by gkasdorf** [comment]
I'll address this issue today.

**Comment by leftbones** [comment]
> I'll address this issue today.

When I saw the giant update today I was hoping this change made it in, but no luck. Hopefully next time!

**Comment by gkasdorf** [comment]
@leftbones I think Sean is either working on this now or is finished with it 😉
