### ISSUE TITLE
Comment sorting

### ISSUE THREAD

**Issue by minorsecond** [Memmy-App/memmy#267]
**Describe the solution you'd like**
It would be nice to be able to sort comments within a post by hot, top, newest, controversial, etc.

**Comment by yrahul3910** [comment]
Let me see if I can tackle this. I believe Lemmy only has [four options](https://join-lemmy.org/api/types/CommentSortType.html), though.

**Comment by gkasdorf** [comment]
@yrahul3910 Sounds good. And I think you're right.

I'm going to do some refactoring in there, but I'll wait until you're finished up to do it.

**Comment by ktgd** [comment]
#286 
This was merged in today and will be available in the next update.

**Comment by theycallmebeez** [comment]
I believe this can be closed out @sgriff96
