### ISSUE TITLE
Full width swipe back 

### ISSUE THREAD

**Issue by SpenHub** [Memmy-App/memmy#277]
**Is your feature request related to a problem? Please describe.**
I have small hands and like being able to navigate back without having to grab the left edge of the screen. 

**Describe the solution you'd like**
One of my favorite features of Apollo is the ability to disable per-post/comment gestures where instead a thumb swipe from left to right (anywhere on the page) will slide your current view/ pane off to the right, essentially acting as a back button.

**Comment by erikgeiser** [comment]
Yes this would be so great, especially together with swiping from the right to re-open the previously opened post from the feed.

**Comment by hungryca-t** [comment]
I also support this. A toggle option in settings to turn swipe gestures on and off is preferred. I’m just not a fan of gestures because I frequently end up upvoting or downvoting comments when all I wanted to do was swipe back to the feed.

**Comment by gkasdorf** [comment]
Yea, I want to do this. We will get to it sooner than later, can't guarantee a timeframe though.

**Comment by ainen** [comment]
Additionally, it would be great if swiping from left to right on the navigation bar would also bring you bring you back (just like in Apollo).

**Comment by Felix-Staud** [comment]
> Additionally, it would be great if swiping from left to right on the navigation bar would also bring you bring you back (just like in Apollo).

You might want to create a new feature request for that otherwise this will probably get lost

**Comment by SpenHub** [comment]
> Additionally, it would be great if swiping from left to right on the navigation bar would also bring you bring you back (just like in Apollo).

This might be hard on homebar devices since that’s really close to the app switching gesture.

**Comment by SpenHub** [comment]
> Yea, I want to do this. We will get to it sooner than later, can't guarantee a timeframe though.
> 
> Now that we have added the buttons for voting though I think we could probably do this fairly soon.
> 
> Edit: Honestly, if I feel up to it I'll take a stab at it tomorrow.

As the OP of this feature request who just broke his primary wrist, this will be a godsend ❤️🙏

**Comment by Felix-Staud** [comment]
> As the OP of this feature request who just broke his primary wrist, this will be a godsend ❤️🙏

What the 😂

**Comment by SpenHub** [comment]
> @gkasdorf i think you already implemented it, right ?

Nope it's still not present. @gkasdorf i just saw that the lemmy app Liftoff has it👀

**Comment by Felix-Staud** [comment]
@SpenHub  I just saw a pr that sounded like it did that so I wanted to confirm wasn’t sure. I couldn’t check it yet cause I was busy with work.

**Comment by SpenHub** [comment]
@Felix-Staud Just saw the new build on TestFlight, looks like it's there now. Feel free to close! It doesn't **_look_** like how it's done in Apollo, but a swipe gesture anywhere still takes me back so I'm happy.

**Comment by eoddc5** [comment]
Fixed with #717
