### ISSUE TITLE
Downvotes shown on instances with downvotes disabled

### ISSUE THREAD

**Issue by ashrude** [Memmy-App/memmy#281]
**Describe the bug**
The downvote button and count shows when logged into instances with downvotes disabled. If you try to downvote it shows an error

**To Reproduce**

log into a Lemmy instance with downvoting disabled (lemmy.blahaj.zone for example)

Observe behaviour while attempting to downvote a post

**Expected behavior**
Downvote buttons, and gestures are hidden/disabled, and counts aren’t shown.

**Smartphone:**
 - Device: iPhone 12 Pro
 - OS: iOS 16.5.1
 - Version: 0.0.2(5)

**Comment by gkasdorf** [comment]
Will make sure this is resolved in 1.0

**Comment by gkasdorf** [comment]
Done
