### ISSUE TITLE
Ability to set subscribed communities as favorites

### ISSUE THREAD

**Issue by Mori22** [Memmy-App/memmy#282]
**Describe the solution you'd like**
The list of subscribed communities can get large quite quick - it would be create if it were possible to pin specific communities to the top of the list.

**Additional context**
I guess the easiest way to achieve that would be to add little starts on the community list and make them clickable to. Each community with an 'activated" star would be pinned to the top of the community.

**Comment by gkasdorf** [comment]
This is done.
