### ISSUE TITLE
[MEM-80] Home page images are wrong.

### ISSUE THREAD

**Issue by sc0ttwood** [Memmy-App/memmy#288]
I have noticed a peculiar issue, when I  implement an image into a post, it overwrites the main post image.

Video:
https://share.icloud.com/photos/065IHg6USpaHIY5IvV_1Yb6Pg

<sub>[MEM-80](https://linear.app/memmyios/issue/MEM-80/home-page-images-are-wrong)</sub>

**Comment by gkasdorf** [comment]
Acknowledge. Will fix. Thanks.

**Comment by gkasdorf** [comment]
@sgriffin6697 is this still an issue or did that PR fix it?

**Comment by sgriff96** [comment]
This is fixed now
