### ISSUE TITLE
[MEM-79] Add toggle to hide read posts

### ISSUE THREAD

**Issue by chowanana99** [Memmy-App/memmy#291]
**Describe the solution you'd like**

I think it would be nice to add a toggle to hide read posts. If possible, it could be community-specific. Of course with the option to unhide them in case you need to find something you've already seen.

<sub>[MEM-79](https://linear.app/memmyios/issue/MEM-79/add-toggle-to-hide-read-posts)</sub>

**Comment by gkasdorf** [comment]
This is an easy one. I'll deal with it today.
