### ISSUE TITLE
Functional Upvote/Downvote button in left side

### ISSUE THREAD

**Issue by KaranGauswami** [Memmy-App/memmy#302]
**Is your feature request related to a problem? Please describe.**
 In the feed We have two upvote arrows , But when i try to click left side of Upvote button it is just opening the Post intead of upvoting it.

**Describe the solution you'd like**
It would be nice to make the Left upvote clickable instead of just displaying the status of upvote and upvote counts. 

**Describe alternatives you've considered**
Currently Right side upvote is just working fine, but it would be nice to have left side functional working button.

**Comment by Ragos81** [comment]
I have the same experience. Intuitively I want to upvote on the left side, before I notice the other buttons on the right side. IMO the space for the right buttons could be used for something else.

**Comment by sgriff96** [comment]
We won't make these a button but will explore ways to make it more clear that they aren't buttons for those users unfamiliar with Apollo's layout

**Comment by KaranGauswami** [comment]
@sgriff96 

In apollo those buttons were functional so thats why i have opened this issue, But if it is not in plan no problem 👍.
