### ISSUE TITLE
Please confirm with a user working with text that they want to discard it, before discarding it.

### ISSUE THREAD

**Issue by Drunemeton** [Memmy-App/memmy#304]
**Is your feature request related to a problem? Please describe.**

Whilst working in the floating window (on iPadOS) for post creation / text editing, neither the "Cancel" button nor merely selecting the UI outside of that window (stray finger taps the iPad screen) queries the user if they want to discard their work. The window just disappears!

**Describe the solution you'd like**

A confirmation dialog box warning of the discard about to happen if they ‘fat finger’ touch the UI outside of the floating edit window.

**Describe alternatives you've considered**

Their work is auto-saved so when they bring that box back up the work is still there. This seems like it has a potential to create drive space issues with sloppy users. 

**Additional context**

Edit: To add information that this happening on iPadOS since the edit window in iOS doesn’t have an area outside of the UI that user can ‘fat finger’ touch to dismiss the box.

**Comment by gkasdorf** [comment]
Drafts are stored now.
