### ISSUE TITLE
[MEM-79] Use/Sync available user settings with desktop profile

### ISSUE THREAD

**Issue by kenny-adam** [Memmy-App/memmy#31]
**Is your feature request related to a problem? Please describe.**
On desktop there are various user settings to show scores, show NSFW, show read posts, etc. which do not yet exist in the mobile app

**Describe the solution you'd like**
Utilize and sync the same settings in-app which are available from the desktop platform for a consistent user experience

**Describe alternatives you've considered**
add the option to sync or not, in the event a user would like separate settings between mobile and desktop

**Additional context**
I believe this contains a full list of available user settings:
https://github.com/LemmyNet/lemmy-js-client/blob/main/src/types/SaveUserSettings.ts

<sub>[MEM-79](https://linear.app/memmyapp/issue/MEM-79/usesync-available-user-settings-with-desktop-profile)</sub>

**Comment by gkasdorf** [comment]
Oh awesome! I didn't even see this. I'll implement this. Thanks for the heads up!

**Comment by eoddc5** [comment]
@gkasdorf just checking the status on this
