### ISSUE TITLE
Tapping search tab icon twice should focus the search text entry field

### ISSUE THREAD

**Issue by RustedSwitch** [Memmy-App/memmy#312]
**Is your feature request related to a problem? Please describe.**
The search tab icon is on the complete opposite end of the screen from the search text entry field. Engaging with search requires tapping the bottom most area, then the top most area, then back to the bottom keyboard area. It’s slow and clumsy. 

**Describe the solution you'd like**
Tapping the search tab icon once already brings the user to the search interface. Tapping the tab icon a second time while already on the tab should bring the search text entry field into focus so the user can start typing. See IMDb app for a live demo. 

**Describe alternatives you've considered**
n/a

**Additional context**
the first method I describe is how Apollo behaved. Other apps also behave this way. IMDB aid one other example.

**Comment by gkasdorf** [comment]
Search bar is much better designed now. Should be good.
