### ISSUE TITLE
Add new sorting options to "top"

### ISSUE THREAD

**Issue by enghseb** [Memmy-App/memmy#314]
As of 0.18 there are now more sorting options for "top". Hour, six hours and twelve hours. 

It would be lovely if these were added as sorting options in the app.

**Comment by RustedSwitch** [comment]
referring to post sorting?

**Comment by enghseb** [comment]
> referring to post sorting?

Yes exactly, should've been clearer with that!

**Comment by ManikandanUV** [comment]
Would love this, along with new comments sort
