### ISSUE TITLE
Link entry wizard doesn’t honor dark mode

### ISSUE THREAD

**Issue by RustedSwitch** [Memmy-App/memmy#315]
**Describe the bug**
When posting or commenting in a dark mode theme, the link creation wizard is light mode

**To Reproduce**
1. Choose sunset dark mode theme
2. Open a comment on any post
3. Tap the link creation wizard icon
4. Shield your eyes!

**Expected behavior**
When a dark mode theme is selected, this entry wizard should honor that choice. 

**Screenshots**
![IMG_1818](https://github.com/gkasdorf/memmy/assets/11944220/bbcb1acb-be07-4d25-87a0-3e3eb8617d6f)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 16.4
 - Version 0.0.2.7

**Comment by gkasdorf** [comment]
Fixed.
