### ISSUE TITLE
Make a F-Droid repo for the Android builds

### ISSUE THREAD

**Issue by Gamey404** [Memmy-App/memmy#318]
**Is your feature request related to a problem? Please describe.**
The problem isn't really out yet but once the apks arrive because Google decided you can wait a few more months for Play Store access that will/would be really annoying to keep up to date with the current update cycle!

**Describe the solution you'd like**
As the title suggests, I think the best solution to this problem would be a F-Droid repo but the official one usually moves very slow so it's not really a fit for a alpha project. Luckely F-Droid aims for the official repo to be one of many and it's absolutely possible to just host your own till updates slow down or something and the official one becomes viable. I never did this myself and I am not a developer so I can only guess how much work it would require but I think it would be managable if expo allows you to just build every candidate for both.

**Describe alternatives you've considered**
Unless Google accepts you some time soon I don't really see a alternative except for the manual apk file releases but that would be really tedious for all Android users and probably take a comparable amount of time to do.

**Additional context**
Again, I am not a expert by any means but here is a official guide on how to set up a repo for F-Droid:
https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/

Apparently F-Droid also has a web app called Repomaker and what it dose is in the name, no clue how well it works but it definitely looks easy!
https://f-droid.org/en/repomaker/

If you don't feel comfortable making your own repo you could also try to get in contact with the F-Droid team or the third party repository maintainer IzzyOnDroid who dose a great job to deliver more up to date packages.

**Comment by sgriff96** [comment]
We've decided to just focus on the ios version of memmy, since there are a lot of big android devs from reddit who are bringing their apps over to lemmy, like Sync.

**Comment by Gamey404** [comment]
I understand that decition but disagree with the reasoning, I love that they port them but as far as I know none of the two clients switching over is actually open source, I really like Liftoff but the choice definitely isn't over whelming yet. Dose that mean you will drop Android support forever or is it just too much atm? This doesn't seem to be something you will change your mind on any time soon but in case you do so after all or some time in the future, IzzyOnDroid would be happy to do the F-Droid part if you ever decide to release apks. Ether way, thanks for the quick response and good luck with Memmy!

**Comment by sgriff96** [comment]
Not something we want to drop forever but
1. We want to focus on an ios design and not compromise for android, in turn making both versions worse
2. You are correct, it is also just too much atm. It's much easier for @gkasdorf and I to just focus on ios since that's what we are easily able to test with.

We may explore releasing an android version in the future, but at the moment we sadly have no concrete plans to do so.
