### ISSUE TITLE
post body viewport issues

### ISSUE THREAD

**Issue by RustedSwitch** [Memmy-App/memmy#319]
**Describe the bug**
When I’m adding a new post, the view is janky. I can’t see the text box boundary, and it seems like there’s a bunch of dead space between the text box and the formatting ribbon. 

**To Reproduce**
1. Enter new post mode. 

**Expected behavior**
the text box boundaries should be clearly visible, and should take up the full amount of available space. 

**Screenshots**
![IMG_1819](https://github.com/gkasdorf/memmy/assets/11944220/1b1c3d64-e4ac-4267-a7c0-5aad1a590508)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro 
 - OS: iOS 16.4 
 - Version 0.0.2.7

**Comment by RustedSwitch** [comment]
Updated, I realized this was happening in new posts, not in comments. The dead space is where the thing you are replying to would normally show. In new posts that preceding message doesn’t exist.

**Comment by gkasdorf** [comment]
Fixed.
