### ISSUE TITLE
Share sheet doesnt honor sunset darkmode theme

### ISSUE THREAD

**Issue by RustedSwitch** [Memmy-App/memmy#321]
**Describe the bug**
when using the sunset theme (and possibly others), the share sheet doesn't honor the theme's dark mode

**To Reproduce**
1. set your theme to sunset
2. view any post
3. tap the share sheet icon
4. shield your eyes!

**Expected behavior**
The share sheet should honor the mode of the theme

**Screenshots**
![image](https://github.com/gkasdorf/memmy/assets/11944220/c36350dd-b9ec-4da6-92ee-0357ac453e8b)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 pro
 - OS: ios 16.4
 - Version 0.0.2.7

**Comment by gkasdorf** [comment]
I'm going to have to look into if this is possible. Currently it seems to follow the system theme. I'll close this but I am going to look into it.
