### ISSUE TITLE
Special visual indicator for the original batch of TestFlight users

### ISSUE THREAD

**Issue by RustedSwitch** [Memmy-App/memmy#323]
**Is your feature request related to a problem? Please describe.**
n/a. This is a purely fluff idea. 

**Describe the solution you'd like**
I'd like some way to recognize other people who were part of the OG Memmy TestFlight group. 

I'd propose a DB that syncs a list of user accounts that have been logged into early TestFlight builds. When I encounter those users during my browsing in Memmy, show me some indicator that they were part of the early adopter group. Either a distinct colored username, or an icon, or a MEM pill, etc.

**Comment by theycallmebeez** [comment]
this would be kinda nifty for the OGs 🤘

**Comment by sgriff96** [comment]
Sorry lol, not really worth the effort or potential cost though we appreciate all the testers

**Comment by gkasdorf** [comment]
> this would be kinda nifty for the OGs 🤘

This would require something that we don't currently have. We don't store any record of information about users, so we don't actually know *who* is testing. This is by design as we don't want your data.
