### ISSUE TITLE
Incorrect Cake Day Year 

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#334]
The cake day is wrong by one (1) calendar year, showing 2024 instead of 2023.  I do not believe this is intentional.

**Comment by sgriff96** [comment]
It's technically correct and intentional, it's telling you when your next cake day is. Would it make more sense to not include the year? The other date next to it is saying when you first signed up, which would be what you are describing you want

**Comment by theycallmebeez** [comment]
Ah. Makes sense - I guess it wouldn’t be needed if that’s the intent. 

The alignment and whatnot could be touched up when addressing this. 

Also when selecting the various sections of profile the whole page slides and refreshes. Can you fix the top “profile info” section and just swap the containers with posts comments etc. below the buttons?
