### ISSUE TITLE
Inbox - Unable to open Mentions or Messages

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#337]
**Describe the bug**
When in the Inbox, unable to open Mentions or Messages.

**To Reproduce**
1. Go to 'Inbox'
2. Click on 'Mentions' or 'Messages'
3. Neither will open.

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17

**Comment by gkasdorf** [comment]
It is not yet implemented but will be. Closing this as it is already on the roadmap.
