### ISSUE TITLE
[MEM-97] Theme/Appearance Previews

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#340]
As a Memmy user, I would like to preview a theme before selecting.  It would also be nice to preview other options/changes to the "appearance" (such as compact mode, etc.).

See suggestion below:

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/efc9a845-1149-488b-a624-ed81978aa41c/905272dd-71d7-4694-ae6b-9bfa8fc6a674)

[Source image](https://github.com/Memmy-App/memmy/assets/382845/9717a529-7402-4bf2-a897-76d65762deed)

[https://media.discordapp.net/attachments/1118520596909797429/1125172967165415536/image0.jpg?width=630&height=1363](https://media.discordapp.net/attachments/1118520596909797429/1125172967165415536/image0.jpg?width=630&height=1363)

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-97](https://linear.app/memmyios/issue/MEM-97/themeappearance-previews)</sub>

**Comment by sgriff96** [comment]
We plan on some sort of preview for themes, but not preview for the other appearance changes

**Comment by teflocarbon** [comment]
A theme preview has been implemented in the latest build, as of now there aren't any plans to have other appearance change previews.
