### ISSUE TITLE
Release ipa file

### ISSUE THREAD

**Issue by dtantono** [Memmy-App/memmy#353]
**Is your feature request related to a problem? Please describe.**
I heard issues that Testflight slots are full and I know there is a maximum capacity for testflight

**Describe the solution you'd like**
Release an ipa file to cater users that cannot join testflight

**Describe alternatives you've considered**

**Additional context**

https://lemmy.world/post/958379
https://www.reddit.com/r/Lemmy/comments/14ons96/comment/jqf5h4a/?utm_source=share&utm_medium=web2x&context=3

**Comment by My-ThrowAwayAccount** [comment]
I'm leaving a comment as this issue is not completely resolved. The [latest release](https://github.com/Memmy-App/memmy/releases/tag/0.5.5) does not seem to include an IPA file yet the TestFlight still has no free slots
