### ISSUE TITLE
The beta is full

### ISSUE THREAD

**Issue by mplorentz** [Memmy-App/memmy#361]
Tapping the TestFlight link in there README shows me an error message that the beta is full. Could you open up some more slots?

**Comment by zchilds** [comment]
TestFlight caps out at 10,000 testers, as an Apple limit. 
The app should be released to the app store officially pretty soon though.

**Comment by teflocarbon** [comment]
Unfortunately all slots have been filled. There will be an App Store release very soon though, it’s currently under review.
