### ISSUE TITLE
Line Breaks are missing

### ISSUE THREAD

**Issue by michikade** [Memmy-App/memmy#362]
**Describe the bug**
In the newest build, line breaks are not displaying properly and every text based post looks like a wall of text.

**To Reproduce**
1. Go to any lengthy post or comment.

**Expected behavior**
This is a new issue in 0.0.2 (9), it dod not exist before.  Line breaks should display as written in the post.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17 DB 2
 - Version 0.0.2 (9)

**Comment by michikade** [comment]
This is the same post in Memmy and in Safari to show the lack of line breaks.

![image](https://github.com/Memmy-App/memmy/assets/6156381/48d7f0ff-dc90-4282-974e-dfad20b758b2)

![image](https://github.com/Memmy-App/memmy/assets/6156381/02e53d3e-fb23-4070-8c4d-1f0e0f7fb6fa)

**Comment by sgriff96** [comment]
Sorry about this, it will be fixed in the next release. Closing for now, feel free to re-open if not fixed then for some reason.
