### ISSUE TITLE
[MEM-98] Dummy icon in Traverse channels list

### ISSUE THREAD

**Issue by bviefhues** [Memmy-App/memmy#363]
**Describe the solution you'd like**
For channels without icon, the channels list in Traverse shows whitespace only. Having a mix of channels with and without icons looks unclean. 

Use a default icon or an icon consisting of the capitalized channel name first letter to fill the whitespace.

<sub>[MEM-98](https://linear.app/memmyios/issue/MEM-98/dummy-icon-in-traverse-channels-list)</sub>

**Comment by sgriff96** [comment]
Easy add, prob will do that tonight if i don't forget
