### ISSUE TITLE
Bug: community header does not display on communities with no posts

### ISSUE THREAD

**Issue by xpsKING** [Memmy-App/memmy#367]
**Describe the bug**
Community header (name, icon, subscribe button, post button) does not display on communities with zero posts
**To Reproduce**
I tap on “search” 
I search for a community without posts (ex. “iosbeta@lemmy.ml”)
I click “communities”
I navigate to the community

**Expected behavior**
Header for community should show to allow user to post or subscribe to the empty community. The message “No posts found. Maybe you should get a conversation started?” Should display underneath. 

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/19416922/5baea96c-d327-4943-8533-86d937a73e6b)
**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS developer beta 17
 - Version 0.0.2 (9) TestFlight

**Comment by sgriff96** [comment]
Will be fixed next release
