### ISSUE TITLE
Markdown is not rendered in the post feed (post preview)

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#373]
![IMG_0793](https://github.com/Memmy-App/memmy/assets/382845/66feafd6-1b02-489b-a70e-24405a204149)

**Comment by sgriff96** [comment]
This is intentional, we don't want to render stuff like headings in the preview. Side effect is that links like that are displayed that way. We may explore a different way to handle this in the future but for now will leave as is.

**Comment by theycallmebeez** [comment]
Can you render only links and ignore other formatting or strip after render?
