### ISSUE TITLE
[MEM-100] Descriptions are totally broken.

### ISSUE THREAD

**Issue by sc0ttwood** [Memmy-App/memmy#376]
As I was posting my lastest post I realised that something was wrong, then I saw it, the description!

Memmy:

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/b76852ba-239a-4900-9fea-13c1b030f631/89152e55-b359-48ac-b3e0-16f11373b434)

[Source image](https://github.com/Memmy-App/memmy/assets/138073160/0187f02a-1b86-4eea-9730-389c1b801a23)

Website:

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/5bff82d1-5e6c-42e8-84ff-39defd92cc70/e820a015-475a-46ff-a0ec-d47e27cfbdac)

[Source image](https://github.com/Memmy-App/memmy/assets/138073160/350b0906-a02e-44b5-970b-4b9b19f8fefa)

Post:
[https://lemmy.world/post/1000435](https://lemmy.world/post/1000435)

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-100](https://linear.app/memmyios/issue/MEM-100/descriptions-are-totally-broken)</sub>

**Comment by sgriff96** [comment]
Looks like something to do with the `**Quote**` markdown. Can you post what that description is in raw markdown?

**Comment by sc0ttwood** [comment]
![](https://i.imgur.com/ikmHhNL.jpg)

![](https://i.imgur.com/3telAOb.png)

![](https://i.imgur.com/rpghDow.jpg)

![](https://i.imgur.com/ZWpps4I.jpg)

**Quote:**

>“Makers of death vans,” *USA Today reports,* “say they save money for poor
localities that would otherwise have to pay to construct execution
facilities in prisons or court buildings. The vans ensure that prisoners
sentenced to death can be executed locally, closer to communities where
they broke the law.”

Learn more here:

https://en.wikipedia.org/wiki/Execution_van

https://www.thesun.co.uk/news/13939633/china-brutal-execution-death-vans-trials/

https://www.news.com.au/world/asia/mobile-death-vans-inside-chinas-brutal-execution-system/news-story/4b920eced96dbb32245d6e10d4410cb0

**Comment by sgriff96** [comment]
Hmm for some reason adding bold markdown before the quote messes up the quote. Will look into it.
