### ISSUE TITLE
[Bug] Links to matrix crash the app

### ISSUE THREAD

**Issue by felixchiasson** [Memmy-App/memmy#385]
**Describe the bug**

Links to Matrix groups/channels (not familiar with Matrix at all so not sure what the nomenclature is) will crash the app when clicked. 

**To Reproduce**
1. Go to https://sh.itjust.works/comment/657413 on the Memmy app (or make a comment with a matrix link like the one here)
2. Click on the link
3. Crash

**Expected behavior**
Link should open properly like other non Lemmy links

**Screenshots**
here is a link that crashes the app: https://matrix.to/#/#sh.itjust.works:matrix.org

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.5.1
 - Version 0.0.2 (9)

**Comment by gkasdorf** [comment]
For reference here is the issue that I opened over there. https://github.com/expo/expo/issues/23282

**Comment by gkasdorf** [comment]
They merged that PR in to fix the issue. I'm implementing a hack right now to fix the issue until it gets published though. It will just open these links in your default browser instead of the built in one.
