### ISSUE TITLE
[MEM-106] Some links cause "TypeError: Cannot convert null value to object"

### ISSUE THREAD

**Issue by JeremyLeland** [Memmy-App/memmy#386]
**Describe the bug**
Links in the attached post cause "TypeError" when opened.

**To Reproduce**
1. Go to https://lemmy.world/post/983150
2. Tap on any of the links

**Actual**
None of the links work -- they all say "TypeError: Cannot convert null value to object"

**Expected**
Links should open the communities in Memmy

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 16.5.1
 - Version 0.0.2 (10)

**Additional context**
From the HTML, the list of links looks like:

```
<ul>
<li><a href="/c/nostupidquestions@lemmy.world">!NoStupidQuestions @lemmy.world</a></li>
<li><a href="/c/asklemmy@lemmy.ml">!AskLemmy @lemmy.ml</a></li>
<li><a href="/c/youshouldknow@lemmy.world">!YouShouldKnow @lemmy.world</a></li>
<li><a href="/c/fediverse@lemmy.world">!Fediverse @lemmy.world</a></li>
<li><a href="/c/general@lemmy.world">!general @lemmy.world</a></li>
<li><a href="/c/showerthoughts@lemmy.world">!showerthoughts @lemmy.world</a></li>
<li><a href="/c/ukcasual@lemmy.world">!UKCasual @lemmy.world</a></li>
<li><a href="/c/casualconversation@lemmy.world">!casualconversation @lemmy.world</a></li>
</ul>
```

<sub>[MEM-106](https://linear.app/memmyios/issue/MEM-106/some-links-cause-typeerror-cannot-convert-null-value-to-object)</sub>

**Comment by gkasdorf** [comment]
I'll play with this and try to find the issue.

**Comment by gkasdorf** [comment]
I believe this is fixed in [https://github.com/Memmy-App/memmy/pull/406](https://github.com/Memmy-App/memmy/pull/406), let me verify

**Comment by JeremyLeland** [comment]
FYI: Still repro’s for me in 0.0.2 (17), not sure if that build has the fix you mentioned.

**Comment by gkasdorf** [comment]
@JeremyLeland Ok I *THINK* it is fixed now. Let's update and see. I'm not closing this though because I could be wrong (someone else was working on this one)
