### ISSUE TITLE
[MEM-105] Feed preview for this single-image post shows two images

### ISSUE THREAD

**Issue by JeremyLeland** [Memmy-App/memmy#387]
**Describe the bug**
The preview for the post https://lemmy.world/post/965172 shows two images, even though the post only has one.

**To Reproduce**
1. Go to https://lemmy.world/c/dndmemes@sh.itjust.works
2. Look for the post "Roll for Sniff" (https://lemmy.world/post/965172)

**Actual behavior**
Preview shows two images (see screenshot)

**Expected behavior**
Post only has one image, it shouldn't show two images in the preview.

**Screenshots**
<<< will attach from mobile shortly >>>

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 16.5.1
 - Version 0.0.2 (10)

**Additional context**
In web browser, post HTML looks like:

```
<article class="col-12 card my-2 p-2" id="postContent"><div class="md-div"><p><img src="https://lemmy.one/pictrs/image/1bad3899-2945-4b66-bea6-4951712502d7.png" alt="First panel: a dwarf smelling a human's butt. Second Panel: A group of dogs playing DnD with the dungeon master dog asking &quot;Okay, what do you want to do next?&quot; Credit to Good bear comics"></p>
</div></article>
```

<sub>[MEM-105](https://linear.app/memmyios/issue/MEM-105/feed-preview-for-this-single-image-post-shows-two-images)</sub>

**Comment by JeremyLeland** [comment]
![Double image](https://github.com/Memmy-App/memmy/assets/50390633/5fc7beaa-3af9-41df-b820-6b3f6aae713d)

**Comment by gkasdorf** [comment]
Let me see what caused it. I have an idea.

**Comment by gkasdorf** [comment]
fixed.

**Comment by JeremyLeland** [comment]
Now it doesn’t show any preview at all:
<img width="375" alt="Now no preview" src="https://github.com/Memmy-App/memmy/assets/50390633/7e45fe8d-2061-4d08-94d3-3d9ccdf93d72">

**Comment by gkasdorf** [comment]
Oh jeez…it’s a really weird case that the link is put into the post as well. Regardless I’ll fix it next build. Thanks.
