### ISSUE TITLE
[MEM-101] Display Embedded Link Once Viewing a Post

### ISSUE THREAD

**Issue by Wailzy** [Memmy-App/memmy#390]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when \[...\]

If I'm browsing, see a post with a link attached, and then click on the post to view the comments or description of the link before I choose to click on it, I then have to go back to my Home Screen to click on the link because it doesn't show in the post. It doesn't feel intuitive, because if I view the link and then want to share my own thoughts - I have to click back on the post to open it up.

**Describe the solution you'd like**

I would like the embedded link to be viewable and able to be interacted with in the post itself.

**Describe alternatives you've considered**

**Additional context**

Showing the post with the link:

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/d3a80de0-75f8-4b83-8688-f480414c78ea/eed682af-652c-42f8-af10-c10a078bd4f6)

[Source image](https://github.com/Memmy-App/memmy/assets/137726328/25cef518-115b-4cac-a8c9-f1fe4b45d2b3)

Showing that once you click on the post you can't see the link.

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/be77ef90-52bc-4bf1-9009-3008c1179186/d012ca6a-1289-4941-8137-b3ddaff4377e)

[Source image](https://github.com/Memmy-App/memmy/assets/137726328/b56be70a-a11c-4e2e-bc29-080f0f8587db)

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-101](https://linear.app/memmyios/issue/MEM-101/display-embedded-link-once-viewing-a-post)</sub>

**Comment by phriedrich** [comment]
I believe this happens when a post has both a link and a text. When opening the post, the text is shown, but the link isn't.

If it's a link only, then it shows the link.

**Comment by gkasdorf** [comment]
I'll be taking a look at this tomorrow morning

**Comment by gkasdorf** [comment]
Fixed!
