### ISSUE TITLE
[MEM-103] The ‘load all comments’ option is missing when opening comments from profile

### ISSUE THREAD

**Issue by michikade** [Memmy-App/memmy#394]
**Describe the bug**
This was here until the latest couple builds.  Now when opening a comment from your profile, there is no way to load all comments in a thread.

**To Reproduce**
1. Go to your profile
2. Click on any comment
3. See error

**Expected behavior**
Previously there was a banner between the post and above your comment that said “load all comments”.  Can this be added back in please?

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17 db 2
 - Version 0.0.2 (16)

<sub>[MEM-103](https://linear.app/memmyios/issue/MEM-103/the-load-all-comments-option-is-missing-when-opening-comments-from)</sub>

**Comment by michikade** [comment]
Video showing the issue: https://github.com/Memmy-App/memmy/assets/6156381/cefb8219-cdd9-4e20-99b6-1b08bb1986d3

**Comment by gkasdorf** [comment]
I noticed this yesterday and will fix it today. Thanks.

**Comment by gkasdorf** [comment]
Fixed.
