### ISSUE TITLE
[MEM-102] Profile Won't Try Reloading After Fail.

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#396]
**Describe the bug**
If the user profile fails to load (due to lemmy.world issues) clicking retry does not actually try to reload the profile.

Even if you switch to a new account after on a different instance, you cannot load a profile until you restart the app.

**To Reproduce**
1. Try to load a profile on an overloaded server until it fails.
2. Click on Retry (app does not seem to retry)
3. Change to different user on different instance.
4. Return to profile, cannot load new profile. Retry does nothing.

**Expected behavior**
Clicking retry should show progress indicator and retry to load the profile. Changing user should load new profile.

**Additional context**
0.0.2.16 build

<sub>[MEM-102](https://linear.app/memmyios/issue/MEM-102/profile-wont-try-reloading-after-fail)</sub>

**Comment by gkasdorf** [comment]
I heard about this today. I'll get a fix in today.

**Comment by gkasdorf** [comment]
Fixed.
