### ISSUE TITLE
Feature: tap top part of a post to enter to the comments

### ISSUE THREAD

**Issue by chowanana99** [Memmy-App/memmy#397]
Right now you can only enter the comments by tapping on the title or the bottom of the post. 

It would be nice if you could also do it by tapping the top (between the user and the community).

Example:

![09C5692A-3510-453D-A436-35490AC5FCE8](https://github.com/Memmy-App/memmy/assets/138327657/a1e80f8c-b37f-4639-ab1d-c81c5651d96c)

**Comment by gkasdorf** [comment]
Fixed this now.
