### ISSUE TITLE
TestFlight is full

### ISSUE THREAD

**Issue by aukustiponki** [Memmy-App/memmy#400]
I dont know what else there is to say, but I can't download the app, it says that the beta is full.

**Comment by WaldoAndFriends** [comment]
It’s a limitation set by Apple, there’s a limit to how many people can enter a public TestFlight beta through a public link. I believe the limit was 10,000 users.

So the Memmy team can only do so much, the only possibility is to remove people from the TestFlight. For example when they haven’t downloaded the app yet.

Also the app has been submitted to the AppStore, but Apple might take a while and could still reject the app.
