### ISSUE TITLE
New Icon setup multiple selectable icons

### ISSUE THREAD

**Issue by benAcrowder** [Memmy-App/memmy#401]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
A new icon and preferably multiple icons with a selectable icon theme

**Describe alternatives you've considered**
N/A

**Additional context**
Created an icon similar in styling to apollo. Just a personal preference to change icons selectively on mood. 

### Figma File View only im for permissions
https://www.figma.com/file/8XNmxEUoxbQ9YbUkDwp3zh/App-Icon-Toolkit---iOS%2FmacOS%2FAndroid-(Community)?type=design&node-id=9%3A1170&mode=design&t=DoSCJw2logCRVQRO-1

#### Icon zip
[memmyIcon.zip](https://github.com/Memmy-App/memmy/files/11952016/memmyIcon.zip)

#### Screencap
![image](https://github.com/Memmy-App/memmy/assets/31901688/4d2e3660-2bd6-423c-99bd-76886888cda8)

**Comment by sgriff96** [comment]
We're working with someone on an icon (we are doing a rebrand and moving away from the lemming). If you want to contribute other icons please reach out to me on Discord and we can chat about it.
