### ISSUE TITLE
Accent color picker isn’t working for all hex

### ISSUE THREAD

**Issue by michikade** [Memmy-App/memmy#402]
**Describe the bug**
I was able to get it to work with some (FF0000 and 00FF00) but it will not take 008080 for example

**To Reproduce**
1. Go to profile - appearance
2. Type in #0008080 
3. See error

**Expected behavior**
This particular color isn’t being accepted, should turn things teal.

**Screenshots**
https://github.com/Memmy-App/memmy/assets/6156381/49862a87-25ad-4433-b145-119c1d9e3f19

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17 db 2
 - Version 0.0.2 (16)

**Comment by ebits21** [comment]
Works for me. Did you include the # sign?

You mean #008080 right? You have an extra zero I assume is a typo.

**Comment by michikade** [comment]
The video had a typo, but no colors worked at all for a while and after deleting and reinstalling it’s working now.  I am going to chalk this up to some weird install bug on my end.
