### ISSUE TITLE
Collapsed comment replies get uncollapsed

### ISSUE THREAD

**Issue by adambowles** [Memmy-App/memmy#405]
**Describe the bug**
Collapsed comment replies get partially uncollapsed when you uncollapse the parent

**To Reproduce**
1. Have three (or more) nested comments where each is a reply of the parent
2. Collapse comment 3
3. Collapse comment 2
4. Collapse comment 1
5. Uncollapse comment 1

**Expected behavior**
Comment 2 should not have children shown, it is not properly collapsed

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/10128574/68fdf099-16b1-47e4-8410-3ffdbf66202e)
![image](https://github.com/Memmy-App/memmy/assets/10128574/276aa4e5-bc4e-4d57-90e6-49b0eb14f50b)

**Comment by gkasdorf** [comment]
Fixed in next update.
