### ISSUE TITLE
[MEM-80] [Feature Request] The ability to navigate to a custom community

### ISSUE THREAD

**Issue by HrBingR** [Memmy-App/memmy#41]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
I'd like the ability to manually navigate to a community I specify in the format of community@instance, rather than only being able to navigate to those I've subscribed to.

**Describe alternatives you've considered**
A search feature might cover this as well, similar to how Apollo does search.

**Additional context**
N/A

<sub>[MEM-80](https://linear.app/memmyapp/issue/MEM-80/[feature-request]-the-ability-to-navigate-to-a-custom-community)</sub>

**Comment by fireshaper** [comment]
As of now this is the only thing keeping me from using Memmy exclusively over mlem.

**Comment by gkasdorf** [comment]
Search was added, I am going to add one more item to it so that regardless of whether the community shows up in the search results from Lemmy API, it will show up in the results in app. Cheers.

**Comment by gkasdorf** [comment]
This works inside of search now. Just enter the community@instance and it will take you directly there.
