### ISSUE TITLE
Image not centered in landscape orientation on iPad

### ISSUE THREAD

**Issue by phriedrich** [Memmy-App/memmy#412]
**Describe the bug**
In iPad on landscape view the image is off-center and not completely visible. In portrait it's displayed correctly.

**To Reproduce**
1. Go to image post
2. open image in full screen mode

**Expected behavior**
Image should be centered and fully visible, as it is in portrait orientation.

**Screenshots**

![image dispplaye orientation bug](https://github.com/Memmy-App/memmy/assets/470153/9ceb6775-cdd3-4dce-88c1-6952084fac21)

**Smartphone (please complete the following information):**
 - Device: iPad Mini 6
 - OS: 16.5.1
 - Version 0.0.2.17

**Comment by phriedrich** [comment]
Update: it seems to be related to the orientation of the device, when you start the app. 

* Killing the app, rotate device to landscape, open app → works in landscape and it’s shifted in portrait. 
* Killing the app again, rotate to portrait, open app → works in portrait but not correctly in landscape

**Comment by gkasdorf** [comment]
Oh that's weird. I'm going to be working on that library in a bit so I'll see what I can do about that. Don't have a physical iPad to test with so hopefully a simulator works out.

**Comment by phriedrich** [comment]
Just tested this, it also show this behaviour in the simulator.

**Comment by gkasdorf** [comment]
Yup, I see the issue. Looking into it not.

**Comment by gkasdorf** [comment]
I see the issue. The image library doesn't account for screen orientation and is using the screen height in applying styles. When in landscape, instead of RN changing these values, you need to use screen width as the screen height. I'll add some logic to my fork to make this work.

**Comment by ibhagwan** [comment]
Using the latest beta 0.1.0 (11) on iPad in landscape mode full-screen mode causes the image to cut off the right side.

Without full-screen:

![IMG_1374](https://github.com/Memmy-App/memmy/assets/59988195/f84abecf-30e0-4f41-b951-b5bc04b33e50)

After clicking the image:
![IMG_1375](https://github.com/Memmy-App/memmy/assets/59988195/804dc7b7-55af-4aa7-aa24-6f3eda20e91f)

On another note, tysm @gkasdorf for your work on this project, your app has single-handedly cemented my move to the Fediverse, you’re truly an amazing developer.

On another note, I  thought I was a “fast” project maintainer, you’re setting up new standards for speed of development, Ty! 😄 ❤️

**Comment by eoddc5** [comment]
@phriedrich @ibhagwan is this still happening with the (14) build that is out?

**Comment by phriedrich** [comment]
@eoddc5 unfortunately it still happens

**Comment by gkasdorf** [comment]
Should be fixed in next build.

**Comment by phriedrich** [comment]
Excellent, works great! Thank you very much!
