### ISSUE TITLE
Request: remember collapsed comments

### ISSUE THREAD

**Issue by chowanana99** [Memmy-App/memmy#413]
**Is your feature request related to a problem? Please describe.** 
Right now, if you re-enter a post, all previously collapsed comments will be uncollapsed

**Describe the solution you'd like**
I think remembering which comments had been collapsed would be useful and make finding where you’d left off easier

**Comment by sgriff96** [comment]
I could see this being useful, but probably wouldn't get to it for a while.

**Comment by gkasdorf** [comment]
This should work somewhat now. Will do some more implementation.
