### ISSUE TITLE
Profile Join Date Incorrect

### ISSUE THREAD

**Issue by tktackett** [Memmy-App/memmy#416]
**Describe the bug**
When logged into an account, my profile join date shows +1 year (5th July 2024).

**Expected behavior**
Profile join date should show the current year (2023).

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: iOS 17 Beta 2

**Comment by gkasdorf** [comment]
Technically we did this on purpose. But I've seen enough people be stumped about it that I think we can just go ahead and change it. I'll do it now.
