### ISSUE TITLE
Broken Link "Null Value"

### ISSUE THREAD

**Issue by sc0ttwood** [Memmy-App/memmy#419]
In the comments of a post I saw this link and clicked on it only to be greeted with this error:

![IMG_2067](https://github.com/Memmy-App/memmy/assets/138073160/7dcaa22c-2d99-4515-93ec-3c0d7dee008c)

Link to comment:
https://sopuli.xyz/comment/809278

**Comment by ktgd** [comment]
Hey. 
This has been fixed and will be in the next update. Thanks!
