### ISSUE TITLE
Setting option to swipe left on a comment to collapse chain (Apollo feature)

### ISSUE THREAD

**Issue by einsteinx2** [Memmy-App/memmy#420]
**Is your feature request related to a problem? Please describe.**
When far down in a comment chain, it's hard to find the OP comment to tap to collapse the chain. In very large, deep chains, it can be very frustrating.

**Describe the solution you'd like**
In Apollo, there was a setting option to change the swipe left action from reply to collapsing the comment chain. I need to collapse comment chains constantly but only rarely reply, so I find it much more convenient to use the swipe left to collapse the chain from any comment reply in that chain and use the 3 dots menu to select reply.

**Describe alternatives you've considered**
The only alternative I can think of is to add "collapse comment chain" to the 3 dots menu, but that's not very convenient for an action taken so often. However, when adding this feature, I think it would be good to have it there, and then if this option is activated, it's replaced with "reply". 

Or perhaps better, just have both options always in the 3 dot menu and just have the setting change the left swipe action so that the menu options don't change depending on what setting you choose, but if there's a preference to have fewer menu options, I think it would be fine to just show one or the other. I don't have a strong preference.

**Additional context**
I have a lot of native iOS experience, but have also written non-trivial software in React (though never using this exact Expo/React Native stack). I was planning to try and just implement this and open a PR, but it seemed appropriate to first open a feature request for comments and feedback before just dropping a PR unannounced. I'm trying out both Memmy and Mlem and am looking forward to contributing to both!

**Comment by dsl101** [comment]
+1 for this. wefwef has exactly this functionality on swipe left. First stop is collapse, second is reply, so no need to choose I think.

I also like the more compact view of collapsed comments now—this would just make it much more useful.

**Comment by sgriff96** [comment]
If you can make a PR to do it that would be great. I believe though at the moment we're having some comment render issues, don't know if swiping on a child comment would cause issues with that though.

**Comment by einsteinx2** [comment]
I took a look through the codebase and started tinkering with adding it, but I’m on a trip right now so time is limited. I’ll keep pecking away at it, and if I get a PR up first that would be cool, otherwise maybe someone will beat me too it which would also be cool.

I actually really like the idea of having it be a multi-level thing just like swiping right is multi-level for up and down vote… it would greatly simplify things since no need for a setting option. Anyway I’ll post back when I get some more time to tinker.

**Comment by dsl101** [comment]
Some people seem to prefer swipe and want less screen space taken up with buttons. Some people want buttons and no swipe action to make scrolling / navigation easier. 

I'm in one of those groups, and happy to add settings if / when the functionality is there. I'm also away for a week, so will check back. If I can do both at the same time, happy to.

**Comment by Felix-Staud** [comment]
@dsl101 @einsteinx2 are you still actively working on it ? If so consider contacting one of the main devs to get assigned to the issue

**Comment by dsl101** [comment]
It's in my list to get back to this week, but I haven't had chance. I will reach out to Mike to get it assigned if time frees up :/

**Comment by eoddc5** [comment]
@dsl101 perfect. would love to get this feature added :)

**Comment by Scooter411** [comment]
@dsl101 just adding my voice to this as it’s the last feature from Apollo that I miss.

**Comment by gkasdorf** [comment]
Doing this tomorrow.
