### ISSUE TITLE
Accent color should accept color code without the #

### ISSUE THREAD

**Issue by WaldoAndFriends** [Memmy-App/memmy#422]
While entering a color code I got an error stating the color code wasn’t valid. Whilst I knew for certain that it was.

Turns out I needed to also enter the # symbol. Often programs allow you to enter color codes both with or without the # for simplicity sake of the user.

**Describe the solution you'd like**
Both formats should be accepted.

**Describe alternatives you've considered**
- Add a hint text

**Additional context**
![image](https://github.com/Memmy-App/memmy/assets/77986224/78da6861-d1cf-4529-8353-534ffaf6fbb6)

**Comment by gkasdorf** [comment]
Done 👍
