### ISSUE TITLE
Feature request- Support widget for Android and iOS

### ISSUE THREAD

**Issue by dtantono** [Memmy-App/memmy#425]
**Is your feature request related to a problem? Please describe.**
Now, The app reach App store which is deemed by Apple that this app reach stable version. It is perfect that we can read our feeds indirectly from the app

**Describe the solution you'd like**
It will be really helpful to support widget. So, we can read our feeds indirectly 

**Describe alternatives you've considered**
Apollo for Reddit did this in the past and I hope Memmy can do the same. What do you think?

**Additional context**

**Comment by sgriff96** [comment]
Maybe in the distant distant future, but not any time soon.

**Comment by sgriff96** [comment]
Won't do this any time soon, that's a lot of work and we have a lot of work to do on the core app instead

**Comment by oxjox** [comment]
I support this request. It’s the only thing holding me back from keeping Memmy installed on my devices.
