### ISSUE TITLE
[Feature Request] Community Icons

### ISSUE THREAD

**Issue by danielwolbach** [Memmy-App/memmy#427]
Having the option to choose community icons similarly to Apollo would be amazing!

**Comment by sgriff96** [comment]
What do you mean choose? I'm unaware of that option from Apollo (finding out so many things I didn't know and I used that app for like 5 years lol)

**Comment by gkasdorf** [comment]
@sgriff96 I think he's just talking about having different icons for the app.

If that's the case, yea we have some icons that are being made and we will be adding those.

**Comment by sgriff96** [comment]
Ahh yea okay
