### ISSUE TITLE
Adding more than one picture in comments isn’t displaying anything in app

### ISSUE THREAD

**Issue by michikade** [Memmy-App/memmy#429]
**Describe the bug**
I added two pictures to a comment I posted and Memmy doesn’t show anything there - no links to tap on or anything.

**To Reproduce**
1. Go to any thread
2. Add multiple pictures as separate links

**Expected behavior**
The app should show each link to be tapped on for images (if it doesn’t show pictures in line)

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/6156381/b56e4b32-9773-43b0-ab4e-0aae64664873)

Here’s Safari showing the images:

![image](https://github.com/Memmy-App/memmy/assets/6156381/837a81c6-9ce3-4c8e-8d26-c3b9ba70bfbd)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17 db 2
 - Version 0.0.2 (17)

**Comment by sgriff96** [comment]
Related to our markdown woes sadly. Hopefully fixed soonish.
