### ISSUE TITLE
[MEM-116] Very tall images are cut off on the top, and scrolling them down makes the image modal close

### ISSUE THREAD

**Issue by graham-pyett** [Memmy-App/memmy#430]
**Describe the bug**
If I look at a very tall image, the very top of it might be cut off. In order to see the image fully I have to pull down, but if I let go it will close the modal

**To Reproduce**

1. Go to [https://lemmy.ml/post/1761841](https://lemmy.ml/post/1761841)
2. Click on the image to open the modal
3. See that the top is cut off a bit behind the front facing camera cutout of the phone
4. Pull down to view the image

Screen shot below doesn’t show the issue as it doesn’t include the front facing camera cutout, but imagine the notch coming down on to the image

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/429392a0-daa5-4d90-9a02-80ed927183e0/53d05831-4b40-4ed6-a971-7fa5c0551b35)

[Source image](https://github.com/Memmy-App/memmy/assets/47046755/2447e5d5-8817-474a-b3e4-cc3b3cd0385d)

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/da402f84-2e1c-4295-b3eb-fdc163385862/40a52ae8-90db-4568-9604-5c81b0aa799f)

[Source image](https://github.com/Memmy-App/memmy/assets/47046755/3ddb7de8-2a86-4022-a1e7-bfd80c34a357)

**Expected behavior**
Probably, you should be able to tap the image and have it expand to full resolution and then scroll around as needed, or have the image box be constrained by the viewport a bit more tightly

**Smartphone (please complete the following information):**

* Device: iPhone 11 Pro Max
* OS: 16.5
* Version 0.0.2 (17)

**Additional context**

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-116](https://linear.app/memmyios/issue/MEM-116/very-tall-images-are-cut-off-on-the-top-and-scrolling-them-down-makes)</sub>

**Comment by gkasdorf** [comment]
Thanks for providing the link. I'll work on this now.

**Comment by gkasdorf** [comment]
This shouldn't be an issue anymore.
