### ISSUE TITLE
[MEM-110] Show link's domain in compact list view

### ISSUE THREAD

**Issue by phriedrich** [Memmy-App/memmy#431]
**Is your feature request related to a problem? Please describe.**
In the feed/list link posts show a small preview and the link symbol, and this is fine. But you have to open the post to see the source of the link.

**Describe the solution you'd like**
Showing the link's domain in the list would make it easier to decide if it's worth opening the post.

Like lemmy shows it in the browser version:

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/6f25b41b-1fa0-464c-9e67-3053396317a0/cf3e9e9b-ab98-4e33-adac-768970c8a2d4)

[Source image](https://github.com/Memmy-App/memmy/assets/470153/27335f4d-af36-4a77-96fe-c006e5a41886)

Especially on news related pages with several posts about a trending topic, it would be useful to directly the links domain and being able to select a good source.

Maybe this could be an option, like the voting buttons for compact view.

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-110](https://linear.app/memmyios/issue/MEM-110/show-links-domain-in-compact-list-view)</sub>

**Comment by sgriff96** [comment]
We could probably put it at the end of the title, I believe that's what Apollo did

**Comment by eoddc5** [comment]
tagging as `security` since domain / url can help with anti-phishing stuff

**Comment by bohn002** [comment]
Played with some models, and went back and forth on slack....
Options:
![image](https://github.com/Memmy-App/memmy/assets/410223/956e8ec8-eed0-4d14-a7bc-7e143b71202c)
![image](https://github.com/Memmy-App/memmy/assets/410223/20ec02e0-5cf6-467f-80a6-198e3930f06f)
![image](https://github.com/Memmy-App/memmy/assets/410223/7cefb05f-1cce-467a-afd1-183c27a242ef)

but went with:
![image](https://github.com/Memmy-App/memmy/assets/410223/ca64febf-5019-4ab1-bd15-bd2d11b8ed0f)
![image](https://github.com/Memmy-App/memmy/assets/410223/31a3fec1-3ce4-4cce-8660-2bd84c9a8db6)

updated `LinkHelper`'s `getBaseUrl` to allow for optional subdomain returns...

**Comment by phriedrich** [comment]
Great work @bohn002 

Personally, I like the first one the best.

**Comment by bohn002** [comment]
we decided to put it in the title for now since the author/stamp/instance is a bit crowded in compact view currently. For now :P
