### ISSUE TITLE
[MEM-123] Searching for community with @ at end crashes app.

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#432]
**Describe the bug**
If you try to search for a community and accidentally keep @ at the end of the search term it crashes the app.

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/c24e15a5-2783-4f2e-8fb5-f300d3f1a42b/44948220-7515-485c-819f-9154388d2057)

[Source image](https://github.com/Memmy-App/memmy/assets/19845100/dc9a50bb-e51d-41ec-8f50-f972c2140041)

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/85ebd66d-5ca8-49fb-ab10-299cf2a0ea8c/b583c745-02cd-44f7-9f6c-04042f5e44a4)

[Source image](https://github.com/Memmy-App/memmy/assets/19845100/62413e80-594e-4db6-a363-7373ad38ac71)

Version 0.0.2.17
Clicking submit logs does nothing.

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-123](https://linear.app/memmyios/issue/MEM-123/searching-for-community-with-at-end-crashes-app)</sub>

**Comment by bviefhues** [comment]
I was curious. Confirming, happens here as well.

**Comment by gkasdorf** [comment]
Fixed.
