### ISSUE TITLE
Comment Sorting Bug from Profile

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#433]
**Describe the bug**

If I go to a comment from my profile, then click load all comments instead of just the original comment thread, then try to sort, it only shows the original comment thread again and doesn’t sort all comments.

Following this, there is no way to see all comments again.

**Expected behavior**
Sort all comments if all comments loaded.

**Version**
0.0.2.17 and later

**Additional**
This was previously fixed I believe in 0.0.2.8 see [here](https://lemmy.world/post/942544).

I think it returned after fixing an issue where "load all comments" wasn't showing.

**Comment by ebits21** [comment]
To add to this.

If you click load all comments and pull down refresh, it then reverts to only the original comment thread as well.

You're then stuck in that thread without a way to get back to all comments.

**Comment by eoddc5** [comment]
@ebits21 are you able to share a screenshot or video of this taking place so we can visualize the issue?

**Comment by ebits21** [comment]
Sure.

First video. Click load all comments and they load. When you sort, it reverts back to only the original comment chain. Not all. It should sort all comments if loaded.

https://github.com/Memmy-App/memmy/assets/19845100/9ac6a381-dabd-40ef-a8ea-a3712c06bd94

Second video. Click load all comments and they load. Pull down refresh and only the original comment chain is visible with no way to load all comments. It should continue to show all comments.

https://github.com/Memmy-App/memmy/assets/19845100/a324a295-8137-43a7-936f-f56ccb42a648

As I said before, it was already fixed but reverted at some point.

**Comment by gkasdorf** [comment]
These should all be fixed up now.
