### ISSUE TITLE
HexColor Inputs for Primary and Secondary Colors

### ISSUE THREAD

**Issue by hugpeter** [Memmy-App/memmy#434]
Could we get hex color input options for primary, secondary, tertiary colors to go along side the accent color input?

The ability to specify accent color is incredible! The current themes available are just alright, it would be cool to have those themes but have it fully customizable too.

**Comment by sgriff96** [comment]
May do this at some point but not planning on it super soon.

**Comment by Polyfun** [comment]
I second this please. I only use light themes, and in the memmy light theme the post body text is far too light, as well as unaccented text such as in the bottom menu (Feeds etc). I think this text should default to black to greatly improve contrast with the pale background. Currently it is difficult to read grey text on a pale background.

**Comment by sgriff96** [comment]
> I second this please. I only use light themes, and in the memmy light theme the post body text is far too light, as well as unaccented text such as in the bottom menu (Feeds etc). I think this text should default to black to greatly improve contrast with the pale background.
> 
> Currently it is difficult to read grey text on a pale background, especially in the main Feed view.
> 
> Comparing wefwef on the left, with memmy on the right, you can see that memmy text is a lot paler. This is also true in the post view. <img alt="image" width="1024" src="https://user-images.githubusercontent.com/6322135/251965151-5d24e3f4-4053-4619-92cc-fa6415eb12ce.png"> Thanks for a great app.

We're gonna tweak this, thanks for bringing it up. Also adding some new light themes soon. More hex code inputs are still on hold though

**Comment by sgriff96** [comment]
New secondary text color:
![simulator_screenshot_44C8DDA4-E7B9-4560-9762-346C6BD54A10](https://github.com/Memmy-App/memmy/assets/46509416/ef72f76d-cb89-4f77-ab53-129414318659)
