### ISSUE TITLE
[MEM-112] Expanding/Collapsing Comments Animation Not Synchronised

### ISSUE THREAD

**Issue by harrismcc** [Memmy-App/memmy#436]
**Describe the bug**
When tapping to expand/collapse a comment, the animation is wonky. The vertical size grow/shrink animation is slower than the animation of the replies expanding/collapsing

**To Reproduce**
1. Go to collapsible comment (comment with replies)
2. Tap to collapse, or expand

**Expected behavior**
Should open/close normally with animation

**Screenshots**
https://github.com/Memmy-App/memmy/assets/740503/05167da5-a1f1-44ae-bdb6-648f3048f559

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS17.0
 - Version: 21A5277h

<sub>[MEM-112](https://linear.app/memmyios/issue/MEM-112/expandingcollapsing-comments-animation-not-synchronised)</sub>

**Comment by harrismcc** [comment]
I think the issue is that the LayoutAnimation [here](https://github.com/Memmy-App/memmy/blob/main/components/hooks/post/useComment.ts#L58) only animates the parent comment, while the mount/unmount of the child comments aren't animated. This is what causes the brief overlap of the two.

**Comment by gkasdorf** [comment]
I think you're correct. I've been fiddling with Reanimated in a side project today and think I might have a few ideas on how to make this super sleek. Not too experienced with it, but trying to learn 👍 We'll see what we come up with.

**Comment by harrismcc** [comment]
Nice, haven't heard of Reanimated before but it looks like a great project.

**Comment by eoddc5** [comment]
Pretty sure this was fixed. Not experiencing it

@gkasdorf can you confirm and then close?

**Comment by gkasdorf** [comment]
It's *fixed* in that the animation was disabled for now. The animation is on the project board though for the comment section overhaul, so I think we can close this out.
