### ISSUE TITLE
[MEM-111] Collapsing comments can expand child comments

### ISSUE THREAD

**Issue by NickPod** [Memmy-App/memmy#439]
In the situation where a parent comment is collapsed after you have collapsed a child comment, any grandchild comments that had been hidden are displayed below the collapsed parent comment.

**To Reproduce**

1. Go to a comment thread at least 3 levels deep
2. Click to collapse a middle level comment
3. Observe that middle level comment and lower level comments have collapsed
4. Click to collapse the parent comment to the previously collapsed middle level comment
5. Observe that the parent comment has collapsed, but the previously hidden lower level comments have reappeared.

**Expected behavior**
Collapsing a comment should hide all child comments at any level, regardless of their prior collapsed/expanded status.

**Screenshots**

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/39ec652a-47d3-48d2-aaa4-39ef1115f869/ef429eca-b422-482d-9d8d-6f2122cdedc4)

[Source image](https://github.com/Memmy-App/memmy/assets/32311648/c81fcb53-abe7-4d6a-99ae-7350c789d6ce)

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/864e24b6-9e4e-48eb-9066-4cbf661f79f0/ff14726d-de83-4ead-841d-99ab2fbb603f)

[Source image](https://github.com/Memmy-App/memmy/assets/32311648/eae42b13-ebb5-45b1-a600-74ac5e694a66)

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/d4e5beda-15ed-43e3-a775-75c6667b7e35/cf82f529-a90a-4637-a567-b9a02d5712b2)

[Source image](https://github.com/Memmy-App/memmy/assets/32311648/63a0793c-f903-4f3c-83ed-e3cdca5482aa)

**Smartphone (please complete the following information):**

* Device: iPhone 12 Pro
* OS: iOS 16.5
* Version: 0.0.2 (17)

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-111](https://linear.app/memmyios/issue/MEM-111/collapsing-comments-can-expand-child-comments)</sub>

**Comment by gkasdorf** [comment]
Let me look into improving this logic. I'll do this today.

**Comment by eoddc5** [comment]
@gkasdorf can you confirm this is fixed? It’s not an issue for me. Tried a few threads.

**Comment by gkasdorf** [comment]
Still broken, I'll work on this now.

**Comment by gkasdorf** [comment]
Fixed.
