### ISSUE TITLE
Allow users to delete their own posts

### ISSUE THREAD

**Issue by alsiniz** [Memmy-App/memmy#443]
Accessing my posts via the default web interface I'm able to delete posts I've made. In Memmy there is no such option. 

Navigating to a post via the profile page should allow you to delete a post you've made when you tap on the 3 dots of the post. As of now the only option is to report your own post. 

I'll admit I'm not familiar with the state of Lemmy's API at the moment and whether that's possible but it is a missing feature I'd love to see added.

**Comment by gkasdorf** [comment]
This will be in the next update 🥳

**Comment by sgriff96** [comment]
> This will be in the next update 🥳 


![image](https://github.com/Memmy-App/memmy/assets/46509416/ce3ba6df-b258-48f1-951c-740368a33b87)

**Comment by sgriff96** [comment]
I'm working on this now but i made a sep issue to track, closing this as a time traveling dupelicate
