### ISSUE TITLE
Tap to collapse main text in text posts

### ISSUE THREAD

**Issue by vmavromatis** [Memmy-App/memmy#447]
**Is your feature request related to a problem? Please describe.**
It's a feature that Apollo had.

**Describe the solution you'd like**
When viewing a text post, be able to click the text to collapse it

**Additional context**
This is particularly useful for large text posts, especially if you want to skip the blah-blah and go straight to comments

**Comment by gkasdorf** [comment]
I literally just finished something up about an hour ago that will do this :) will be in the next update.

**Comment by vmavromatis** [comment]
wtf how
