### ISSUE TITLE
[MEM-127] Blur NSFW community avatar/icon

### ISSUE THREAD

**Issue by teej107** [Memmy-App/memmy#448]
**Describe the bug**
I have the blur NSFW content setting enabled. When I go into a NSFW community to block it, their avatar image isn’t blurred. Most of the time a NSFW community avatar itself is NSFW.

**To Reproduce**
1. Enable blur NSFW content.
2. Go into a NSFW community.

**Expected behavior**
The NSFW community avatar to also be blurred.

**Smartphone:**
 - Device: iPhone 12
 - OS: iOS 16
 - Version 0.0.2 (17)

<sub>[MEM-127](https://linear.app/memmyios/issue/MEM-127/blur-nsfw-community-avataricon)</sub>

**Comment by eoddc5** [comment]
@gkasdorf can you confirm this is fixed? Looks like nsfw banners and avatars are not showing for me

**Comment by gkasdorf** [comment]
These are blurred now.
