### ISSUE TITLE
Default account/Persistent account

### ISSUE THREAD

**Issue by Nannerz** [Memmy-App/memmy#450]
**Is your feature request related to a problem? Please describe.**
There is no way to select a default profile/account. By default, when the app is launched it seems to pick the first one on the list. If you change profiles, this does not persist when the app is re-launched. Useful feature for different fediverse instances, ongoing discussions.

**Describe the solution you'd like**
A drop-down to select your default profile, maybe a toggle to persist the last selected profile between app sessions.

**Describe alternatives you've considered**
The only alternative seems to be to manually go in and change the first profile/account in the account menu.

**Additional context**
Maybe related to [MEM-91] Persist user-selected feed when opening app #102

**Comment by ebits21** [comment]
Accounts persist in the latest beta.

**Comment by Nannerz** [comment]
Hm you're right, looks like it should be fixed by https://github.com/Memmy-App/memmy/pull/375

**Comment by Nannerz** [comment]
^
