### ISSUE TITLE
0.1.0.2 No access to Profile Page

### ISSUE THREAD

**Issue by roskelld** [Memmy-App/memmy#453]
**Describe the bug**
When tapping the Profile button I just see a loading spinner run. I can press the Cog to access the settings panel.
NOTE: I've never been able to see my profile since the feature was added. I have a Lemmy.world account if that helps
I can view other users profiles by tapping their name within community posts.

**To Reproduce**
1. Go to Main Screen
2. Click on Profile
3. Watch a cog spin until the universe cools

**Expected behavior**
My wonderful profile appears with all that nice cake day info and links to posts and comments.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS
 - Version 15.7.7

**Logs:**
If you wish to submit any debug logs, you may do so by doing the following:
Log sent from address: steady.bushier.0y@icloud.com

**Additional context**

**Comment by 0ctoqus** [comment]
Don’t know if it would help but I have the same bug. I have an animated profil picture and banner on lemmy.world, that could be the source of the problem

**Comment by gkasdorf** [comment]
@0ctoqus @roskelld 

Are you guys trying to use an email to sign in? Or are you not using the same capitalization in your username to sign in as you have on Lemmy?

In the first instance, I have fixed this issue in the next release. In the second instance, this is partly my fault but also a bug in Lemmy where it *does* matter if you query for the correct capitalization.

@roskelld I think you made some changes to your login earlier to fix a push notification issue, so this might be invalid for you now?

**Comment by 0ctoqus** [comment]
@gkasdorf I used an email to login but I can’t seem to be able to edit it in the edit account -> server credentials section

**Comment by gkasdorf** [comment]
@0ctoqus Glad to hear it works. This is fixed in future updates, but we will also add an easy way to sign out of an account too.

**Comment by roskelld** [comment]
Since signing in with my username and getting the latest version I can confirm the profile now works!

Thanks for all the help.
