### ISSUE TITLE
Searching within the Traverse page doesn't work as expected

### ISSUE THREAD

**Issue by ManikandanUV** [Memmy-App/memmy#454]
**Describe the bug**
No matter what I search, I get irrelevant communities in the results, duplicated multiple times over, but not my desired community. Even if I clear the search, the list doesn't clear, and there is no way for me to use the traverse page unless I close out the app and reopen.

**To Reproduce**
1. Go to Traverse
2. Search for a community

**Smartphone (please complete the following information):**
 - Device: iPhone 12 pro

**Comment by gkasdorf** [comment]
In traverse? Right now, the only thing that Traverse does is search the communities you are subscribed to. You'd need to use Search to find communities.

**Comment by sgriff96** [comment]
Can you include a video?

**Comment by ManikandanUV** [comment]
> In traverse? Right now, the only thing that Traverse does is search the communities you are subscribed to. You'd need to use Search to find communities.

I'm talking about filtering within the list using the search bar at the top.

**Comment by ManikandanUV** [comment]
> Can you include a video? We're unable to reproduce. Also what instance is your account on?

I'm on Lemmy.world. Let me see if I can screen record

**Comment by eoddc5** [comment]
@ManikandanUV the issue is not understood

The video you show do not show you using the search function. You are scrolling through your traverse feed.

**Comment by ManikandanUV** [comment]
> @ManikandanUV is this still taking place after the latest updates?

Hi, sorry for the late reply, but yeah it's still happening. 

![image](https://github.com/Memmy-App/memmy/assets/13487652/08aa145f-8f62-4e52-885b-62a437b986c5)
