### ISSUE TITLE
Setting option to disable collapse on tap

### ISSUE THREAD

**Issue by tpkee** [Memmy-App/memmy#455]
**Is your feature request related to a problem? Please describe.**
I hate that whenever I tap on a comment/post, this collapses

**Describe the solution you'd like**
A setting option that disable the collapse on tap

**Describe alternatives you've considered**

**Additional context**

**Comment by gkasdorf** [comment]
Done. We will add a gesture eventually for this, so you'll be able to do it with the gesture whenever we add that regardless of your setting here.
