### ISSUE TITLE
[MEM-122] Inbox does not show message

### ISSUE THREAD

**Issue by bviefhues** [Memmy-App/memmy#456]
**Describe the bug**
I ran into a case where there was a new message but it was not shown in the inbox.

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/881997f1-ec54-4d0f-8959-426c1fe0bc92/1cefb804-d7ab-4cea-82e9-87edf30ad03c)

[Source image](https://github.com/Memmy-App/memmy/assets/1117300/7d2fdccb-f049-4746-bf66-207530662955)

Restarting the app did show the message in the inbox.

**To Reproduce**
Not sure how to reproduce.

**Expected behavior**
Red message counter and inbox are in sync.

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-122](https://linear.app/memmyios/issue/MEM-122/inbox-does-not-show-message)</sub>

**Comment by bviefhues** [comment]
Ran into the same issue again. Manually refreshing by swiping down showed the message. 

However, that is not expected behavour. I did assume the app would auto-refresh.

**Comment by gkasdorf** [comment]
Yea I'll update it to automatically fetch.

**Comment by eoddc5** [comment]
@gkasdorf I haven’t had any issues with this. Has this been fixed?
