### ISSUE TITLE
[MEM-121] Double tap to zoom out not working

### ISSUE THREAD

**Issue by chowanana99** [Memmy-App/memmy#457]
**Describe the bug**
When you open an image and zoom in, double tapping to zoom out doesn’t work. If you zoomed in by double tapping then zoom out doesn’t work at all. If you zoomed in by pinching then it only partially zooms out.

**To Reproduce**
1. Open image
2. Zoom in
3. Double tap

<sub>[MEM-121](https://linear.app/memmyios/issue/MEM-121/double-tap-to-zoom-out-not-working)</sub>

**Comment by gkasdorf** [comment]
Will work on this today.

**Comment by gkasdorf** [comment]
Fixed this in next update.
