### ISSUE TITLE
Arrow Rotation

### ISSUE THREAD

**Issue by MikaelStave** [Memmy-App/memmy#458]
**Describe the bug**
The rotation on the arrow when swiping on a post gets stuck at a weird angle.

**To Reproduce**
Start swiping to show the down/up arrow. 
Quickly swipe between them.
Stop at one of them.

**Expected behavior**
Show 0deg or 180deg.

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/41327316/ca5501fa-5616-4207-b5f5-d9b212c725cd)

**Smartphone:**
 - Device: iPhone 14 Pro
 - OS: iOS 17 Dev 2
 - Version 0.1.0 (3)

**Comment by sgriff96** [comment]
Hmm yea, that's a little weird. Will look into it eventually, but low priority.
