### ISSUE TITLE
Upvote/downvote buttons orientation gets easily confused

### ISSUE THREAD

**Issue by fer0n** [Memmy-App/memmy#459]
**Describe the bug**
When swiping between the up and downvote option, the arrow orientation is no longer correct

**To Reproduce**
1. Go to any post
2. swipe right and repeat going back and forth between up and downvote 
3. orientation or arrows will be incorrect

**Expected behavior**
Upvote arrow eventually always points up, downvote down 

**Screenshots**
https://github.com/Memmy-App/memmy/assets/20093825/180f6f85-64ed-4b6f-86c0-99b7571e8615

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.4
 - Version 0.1.0 (3)

**Comment by fer0n** [comment]
(Not a bug, but related: there's no way to distinguish between voting up and removing the up vote)

**Comment by sgriff96** [comment]
Not sure which was first but this and #458 are about the same thing, so gonna close this for that.
