### ISSUE TITLE
URLs are not visible in some posts

### ISSUE THREAD

**Issue by ecabr** [Memmy-App/memmy#460]
**Describe the bug**
Links for URLs in posts are not visible in compact mode. Also, URLs are not visible in the post's view (no matter the compact mode).

**To Reproduce**
1. Go to Feed with compact mode.
2. Some posts does not show a URL.
3. Tap some post.
4. Selected post does not show a URL.
5. Same post in website does show a URL.

**Expected behavior**
URLs should be visible and clickable for users.

**Screenshots**

Memmy Feed with compact mode:

![IMG_2440](https://github.com/Memmy-App/memmy/assets/29156147/2b85cc6d-6814-49d1-9ef3-538fca74c3d6)

Memmy showing a post:

![IMG_2441](https://github.com/Memmy-App/memmy/assets/29156147/5b368916-f490-46a1-be72-82efbafb996e)

Lemmy instance website showing same post:

![2023-07-07 17 18 41 lemmy world 4ce5e7d220ee](https://github.com/Memmy-App/memmy/assets/29156147/0cd3bb9d-8f0a-435e-9b52-7a108caf77f0)

Full post in lemmy instance website:

![2023-07-07 17 19 04 lemmy world 0b4052d4624d](https://github.com/Memmy-App/memmy/assets/29156147/2c94321e-409d-42b2-8b5d-e569e7c0d4dc)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.5.1
 - Version 0.0.2

**Logs:**
No logs

**Additional context**
This bug is not for all posts with URLs, but why some URLs are visible and other URLs don't is not clear.

**Comment by sgriff96** [comment]
Can you link that post please?

**Comment by ecabr** [comment]
> Can you link that post please?

Link to the post: https://lemmy.world/post/1151991

**Comment by Taxxor90** [comment]
Another example where I noticed this is the Facebook news that flooded my feed today due to multiple crossposts

On Memmy, there is no link available to follow 

![image](https://github.com/Memmy-App/memmy/assets/45570250/24571fed-0ea7-4207-adf2-8ebfc036f55e)

![image](https://github.com/Memmy-App/memmy/assets/45570250/843a0935-7eb5-4525-9c89-629d901c27a4)

**Comment by GrayBoltWolf** [comment]
Same issue here in compact mode, I'd say 90% of the posts with a link just don't show it at all.


![image](https://github.com/Memmy-App/memmy/assets/4554196/cc327187-9b18-4777-8362-cbe5845f370d)

**Comment by sgriff96** [comment]
Yea not related to compact mode. The way we handle markdown is just not good but we are struggling w the solution. Not much support out there for it in React Native.
