### ISSUE TITLE
Add option to disable upvote/downvote spinning animation

### ISSUE THREAD

**Issue by Hikiru** [Memmy-App/memmy#461]
I personally prefer the instant up/down switch instead of the animation, and I’d like a toggle to disable it. I also think I’d like the animation better if it didn’t overshoot then correct itself, if you know what I mean. That one is kind of minor, but maybe could be added as a “simple” style. Default, Simple, None.

**Comment by Hikiru** [comment]
Speaking of animations, the comment collapse animation looks really weird on large comments with multiple replies. Its also really slow.

**Comment by sgriff96** [comment]
I'm just gonna close this as won't fix for now, we really have way too many important issues to add a toggle for this. FWIW we are working on the comment collapse.
