### ISSUE TITLE
Use post-iOS 14 pull down menu design

### ISSUE THREAD

**Issue by burakdede0** [Memmy-App/memmy#462]
**Is your feature request related to a problem? Please describe.**
Memmy still uses the pre-iOS 14 pull down menu design.

**Describe the solution you'd like**
Using iOS 14 pull down menu design would be more modern.

**Additional context**
Screenshots from Memmy and Files.app.

![photo_2023-07-08_01-03-34](https://github.com/Memmy-App/memmy/assets/29973158/a2425e36-cf8b-4833-ae52-8e062a582bd8)
![photo_2023-07-08_01-04-09](https://github.com/Memmy-App/memmy/assets/29973158/96410891-182f-4964-8084-89a24669cf6b)

**Comment by sgriff96** [comment]
We use https://github.com/expo/react-native-action-sheet which doesn't support this at the moment. Not aware of an ios14 styled equivalent but if you know of one let me know. Closing as `wontfix` for now though.
