### ISSUE TITLE
Posts with 3+ images don’t show more than 2 images in Feed view and 1 image in Post view

### ISSUE THREAD

**Issue by cryocaustik** [Memmy-App/memmy#463]
**Describe the bug**
posts with 3+ images don’t show more than 2 pictures at the feed view and 1 picture within the post view

**To Reproduce**
1. Go to feed with posts having 3 images
2. Notice you can only view two of the three images
3. Tap on post to enter the post view and notice that only a single image is available to view

**Expected behavior**
Ability to view and tap onto 3 images that are in the post

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/15346996/512207b8-0eeb-43b6-817f-487398389528)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 17 beta 3
 - Version TestFlight 0.1.0

**Comment by sgriff96** [comment]
Why is it so important to show 3 images? Because apollo did that? Apollo maxed out at 3 images. This is much easier to just show 2 images for now.

**Comment by cryocaustik** [comment]
I think displaying two is fine on the Feed view, but there is no way to slide/swipe to third image.

Once within the post, Apollo would list would all the links with previews at the bottom of the post/comment.

**Comment by sgriff96** [comment]
Sure, though that's a separate issue really. We are working on a way to show the two images and swipe between them. We're also working on markdown rendering improvements that will hopefully help with displaying all the links at the bottom.
