### ISSUE TITLE
[MEM-120] Let users choose whether links open in in-app or default browser

### ISSUE THREAD

**Issue by kdmcguire** [Memmy-App/memmy#464]
**Is your feature request related to a problem? Please describe.**
I prefer to have links open in my default, chosen browser, rather than an in-app browser. There's a good chance I'm not alone!

**Describe the solution you'd like**
This choice should be available in the app settings. Perhaps in the 'Content' section?

**Describe alternatives you've considered**
Not sure there is an alternative for this particular function.

**Additional context**
N/A

<sub>[MEM-120](https://linear.app/memmyios/issue/MEM-120/let-users-choose-whether-links-open-in-in-app-or-default-browser)</sub>

**Comment by gkasdorf** [comment]
Yea this shouldn't be too hard to do. And you're definitely not alone so I'll figure it out.

**Comment by gkasdorf** [comment]
This is done.

**Comment by kdmcguire** [comment]
That was quick! Much appreciated 🙏
