### ISSUE TITLE
0.1.0.3 Cannot enable Push Notifications

### ISSUE THREAD

**Issue by roskelld** [Memmy-App/memmy#465]
**Describe the bug**
Push notifications won't switch on and the app softlocks showing the spinner. 
NOTE: The graphic for the toggle switches back off while the spinner is showing (maybe just a graphical thing, but visually indicates that the option has been reset).

**To Reproduce**
1. Go to Profile > Cog > Accounts > Change Account Settings 
2. Slide Push Notifications
3. Tap Continue to accept
4. Watch spinner

**Expected behavior**
After pressing Continue the app should enable push notifications and return the user to the Manage Accounts page.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone & Plus
 - OS: iOS15
 - Version 17.7.7

**Logs:**
Emailed logs from steady.bushier.0y@icloud.com

**Comment by gkasdorf** [comment]
Let me see if there's something wrong serverside.

**Comment by gkasdorf** [comment]
Seems to be alright there. Can you give me this info:

What is your instance?
Are you using your username to sign in?

**Comment by roskelld** [comment]
I'm on lemmy.world

Using my email to sign in.

**Comment by gkasdorf** [comment]
Ah that's the issue. I fixed this in more recent builds but they are not released yet.

Can you do this:

1. Add an account to Memmy using your username instead of email. Capitalization also matters because of a bug that was fixed in the Lemmy code but don't think it's made its way into releases yet...
2. Remove the other account
3. Enable push notifications

**Comment by roskelld** [comment]
That worked!

It also kinda gave me some progress with not seeing my profile page too. Instead of an infinite spinner I now see `That content or community was not found`. I guess that's something :D

**Comment by gkasdorf** [comment]
Yea it's an issue on Lemmy's side, even though I probably could be doing a few things better too. Hopefully the PR with the fix gets merged in here soon for Lemmy.
