### ISSUE TITLE
Upvote placement continuity 

### ISSUE THREAD

**Issue by aidanquist** [Memmy-App/memmy#472]
*This is semi-related to issue [423](https://github.com/Memmy-App/memmy/issues/423) but not just about comments I am putting it as a separate issue.
The upvote/downvote location is in several different places. On the feed page, they are on the right side with the with the total vote on the left. 
![image](https://github.com/Memmy-App/memmy/assets/26237599/acb6f0b3-2d90-40ca-b83c-f389a56725ff)

When viewing an individual post the arrows are switched to the left hand with the upvote count and downvote count next to each respective arrow.
![image](https://github.com/Memmy-App/memmy/assets/26237599/8873935b-4951-47e6-9865-a4a65f6d6678)

**Describe the solution you'd like**
Adopt only 1 of these UIs. Have the voting arrows on the left side with the number of upvotes and downvotes separated next to each arrow at all times including the main feed, viewing posts, and comments.

**Describe alternatives you've considered**
Allow users to select what side the voting buttons are on within the settings.

**Comment by sgriff96** [comment]
We're basically copying Apollo with this, only difference is the vote buttons on the post having the vote count instead of it being above

**Comment by sgriff96** [comment]
Oh i guess i didn't ask a question lol, think i meant to add that label somewhere else
