### ISSUE TITLE
Cannot remember Subscribed community on newest update

### ISSUE THREAD

**Issue by dtantono** [Memmy-App/memmy#476]
**Describe the bug**
I usually set my home feed to view posts chronologically from my subscribed communities. But on recent update 0.1.0, after I close the app and start it again. it reverts to all posts.

**To Reproduce**
1. tap the top right (the globe button) on Feed tab
2. Choose subscribed
3. Close the app
4. open the app again
5. it revert back to all posts

**Expected behavior**
on previous update, after I choose view my subscribed community. it will not revert to default after I close the app. 
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2nd generation
 - OS: iOS
 - Version 15.4

**Logs:**
If you wish to submit any debug logs, you may do so by doing the following:
 - Navigate to Settings
 - Tap version number 5 times
 - Press "Send Logs"

This will open an email in your mail app with the logs in the body of the email. 

If you want, you can post them here. However, although there should not be any PII inside of the logs, it may be best to just send them privately. If you do want to post them here, please either find and provide the applicable parts of the logs, or check them for any PII.

**Additional context**

**Comment by gkasdorf** [comment]
To be honest, I am not sure this *was* a feature. I think what might have happened is your default settings got wiped out (there was a change that caused that to happen)

Can you try setting the default sort in settings?

Regardless, I do want to make this be something that gets remembered based on your last session.

**Comment by dtantono** [comment]
Sorry, my bad there is a toggle on the setting and I forgot to turn it on and I will close it

**Comment by dtantono** [comment]
Sorry if I bring the issue back because there is a big accident on many lemmy servers such as lemmy.world. I need to relogin again. So, there is no logout button and I have to uninstall it and reinstall it back. But, the thing is when I want to tap the Profile menu, tap the gear icon on top right, tap content, tap default sort, I want to tap new as you suggested. But, that button is not responsive. What do you think?

 
![6FF772B4-ADF7-40A7-B47F-C0EF0A1D3062](https://github.com/Memmy-App/memmy/assets/29157187/680bdb64-2bdf-4d8a-a24e-1358fd84df27)
![02E29A5C-5C75-41C3-B216-E8FE3A90D157](https://github.com/Memmy-App/memmy/assets/29157187/e868d980-389f-434b-ab7d-8ac49d9cd1aa)


https://lemmy.world/post/1290412

**Comment by sgriff96** [comment]
This should be fixed in next build
