### ISSUE TITLE
In compact feed tap author should go to post instead of author

### ISSUE THREAD

**Issue by vmavromatis** [Memmy-App/memmy#477]
**Is your feature request related to a problem? Please describe.**
I'm quite sure this was also how apollo was working. The main issue here is fat fingers and that 9 out of 10 times, I don't care who is `alaxitoo` or `Nindelofocho` etc I have made way too many mistakes clicking on author name instead of post or comment icon. If I REALLY want to view the author's profile, I can still get to it via the post view. So instead make the tap author go to inside the post. 

<img width="397" alt="image" src="https://github.com/Memmy-App/memmy/assets/8668731/bd6fc0fc-fe65-43db-b24a-068736e23a5c">

Above request is just for compact view. Normal view can remain the same.

Thank you!

**Comment by erikgeiser** [comment]
I accidentally went to the author profile a couple of times, too. There is only so much space to tap in compact mode and wanting to directly jump to an author profile from the feed is pretty rare I think so I support this feature request.

**Comment by gkasdorf** [comment]
Done.
