### ISSUE TITLE
Upvote swipes show inconsistent colours/states

### ISSUE THREAD

**Issue by br337** [Memmy-App/memmy#483]
**Describe the bug**
I am not sure if this really is a bug, or if it's intended, but it's been definitely confusing me. When you swipe on a post from left to right you first go through the upvote slide which shows as orange, then through the downvote slide which also shows as orange, and when you then start going back the upvote slide now suddenly shows up as blue. After that, if you try the slides on the same post the colour state seems to stay the same. 

**To Reproduce**
1. Go to the front page
2. Slide a post from left to right through the upvote and downvote slide, then slide back to the initial state. Do all of this without releasing
3. Try doing it again on the same post and see that the feature now behaves differently (by showing a different colour order)

**Expected behavior**
Upvote should stay orange, downvote should stay blue, no matter the sequence in which they show up.

**Video**
https://github.com/Memmy-App/memmy/assets/49288125/fdfdd684-6885-453b-83d6-3b516f4f3106

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 
 - Version 16.5.1

**Comment by gkasdorf** [comment]
This is fixed. Version is being released to app store now.
