### ISSUE TITLE
Manage account button not functional

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#484]
In 0.1.0(4) the new manage accounts drop down is not functional until I load the profile tab, then it works.

**Comment by gkasdorf** [comment]
Fixing now, thanks. Build released in a few minutes.

**Comment by ebits21** [comment]
> Fixing now, thanks. Build released in a few minutes.

Issue fixed but now if you don't load the profile first, then there is no back to profile button on the top left of the manage settings screen.

No way to get back to profile.

Works fine if you load profile first.
