### ISSUE TITLE
App icon color does not change

### ISSUE THREAD

**Issue by bviefhues** [Memmy-App/memmy#485]
**Describe the bug**
The app does not change icon color to red or green. 

**To Reproduce**
1. Change app icon color in settings to red or green
2. Go to home screen
3. Icon is still blue

Even terminating and re-opening the app does not fix this. 

**Expected behavior**
A red or green app icon. 

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 16.5.1
 - Version 0.1.9 (4)

**Comment by gkasdorf** [comment]
You *might* need to try restarting the app. It's apparently a bug in iOS (Apollo used to tell users to just restart the app after the first icon change, might need to do the same here)

**Comment by bviefhues** [comment]
@gkasdorf I did force-quit and re-start. Does not work.

**Comment by gkasdorf** [comment]
Do you mind trying a reinstall? There might be some changes I need to make, but from what I see it is working correctly. I'll look into it though here in a bit.

**Comment by Hikiru** [comment]
Remove it from your home screen and add it back

**Comment by eoddc5** [comment]
This is a non issue
