### ISSUE TITLE
[MEM-126] No back to profile button in manage settings

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#486]
Issue #484 fixed, but now if you go directly to manage settings, there is no back to profile button _unless you go to the profile page first_.

You get stuck with no way to get to profile.

<sub>[MEM-126](https://linear.app/memmyios/issue/MEM-126/no-back-to-profile-button-in-manage-settings)</sub>

**Comment by gkasdorf** [comment]
Lol yea. I removed this in the next build up. I'll figure it out tomorrow but don't have time now. Didn't want to leave the bug in there. 

I'm leaving this issue open so we can work on it later today.

**Comment by sgriff96** [comment]
This is fixed
