### ISSUE TITLE
[MEM-125] Default sort New is broken in Settings

### ISSUE THREAD

**Issue by bviefhues** [Memmy-App/memmy#487]
**Describe the bug**
It is not possible to set default sort new in Settings. Seems New and Cancel is mixed up. See Screenshot.

**Screenshots**

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/d6b23d75-de24-40d0-a652-12efce14cc82/e33279bd-002d-4bfb-9227-7befc3880761)

[Source image](https://github.com/Memmy-App/memmy/assets/1117300/05cb1139-12fb-406f-ba6c-4b56b4334e0b)

**Smartphone (please complete the following information):**

* Device: iPhone 11 Pro
* OS: iOS 16.5.1
* Version 0.1.0 (4)

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-125](https://linear.app/memmyios/issue/MEM-125/default-sort-new-is-broken-in-settings)</sub>

**Comment by bviefhues** [comment]
Tapping Cancel crashes the app.

**Comment by gkasdorf** [comment]
Oh that doesn't look right! I'll fix that up today, my mistake.

**Comment by bviefhues** [comment]
@gkasdorf you guys are iterating so amazingly fast. That is not a mistake, rather an iteration oppportunity.

**Comment by gkasdorf** [comment]
Fixed.
