### ISSUE TITLE
Comment Jump Button

### ISSUE THREAD

**Issue by QuarterSwede** [Memmy-App/memmy#488]
Would love to see a comment jump button added to _jump to the next parent comment_ in a post. Haven’t seen any other Lemmy/kbin app do that yet. Lemmy has grown big enough that it’s needed in certain communities.

**Comment by gkasdorf** [comment]
I think I’m going to play with this later today :)GavinSent from my iPhoneOn Jul 8, 2023, at 5:50 AM, QuarterSwede ***@***.***> wrote:﻿
Would love to see a comment jump button added to jump to the next parent comment in a post. Haven’t seen any other Lemmy/kbin app do that yet. Lemmy has grown big enough that it’s needed in certain communities.

**Comment by QuarterSwede** [comment]
Oh, you’re a saint 👼.

**Comment by sgriff96** [comment]
Dupe of #284
