### ISSUE TITLE
Swipe to upvote

### ISSUE THREAD

**Issue by Bawt818** [Memmy-App/memmy#490]
The swipe to upvote/downvote feature seems to be a bit buggy. This is true both for comments and posts and is very consistent. When I swipe to the right on a post/comment the upvote arrow and background color seems to be messed up or reversed. This is especially true if this is my second interaction with that comment. They appear to be somewhat related to what has been done previously.

I would also suggest adjusting the distance required for the swipe to work for bigger screens. I feel like it should be half as long for my screen size (10.5”).

Thanks for the app!

Example:
1. Swipe to downvote a comment
2. Start swiping to the right again to change and see in order: 
blue down arrow (let go to upvote)
orange down arrow (let go to remove the downvote)
3. While still holding swipe back and the left section changes to blue up arrow which upvotes

![IMG_0168](https://github.com/Memmy-App/memmy/assets/98644434/aee2fa1d-2324-44da-b600-3f493f3a2789)

**Device**
 - Device: iPad [NPDY2B/A]
 - OS: [iPadOS 16.5.1 (20F75)]

**Comment by ebits21** [comment]
I think this is fixed with the new slider in beta.

**Comment by sgriff96** [comment]
Yep this is fixed in beta. Believe we are waiting on apple to approve a new release to the app store. Closing for now.
