### ISSUE TITLE
Make Share button not automatically download image

### ISSUE THREAD

**Issue by martinjose** [Memmy-App/memmy#491]
**Describe the bug**
When clicking the "Share" button while viewing an image, it immediately displays the "Downloading image..." modal and never completes. It is then impossible to continue using the app without force closing.

**To Reproduce**
1. Launch Memmy
2. Open any image from a post.
3. Select the "Share" button.
4. The "Downloading Image..." modal appears permanently.

**Expected behavior**
The system's Share API dialog should appear upon selecting the "Share" button.

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/16141594/657b20e8-3a38-4aa3-a2e3-1745e2227cf2)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1 20F75
 - Version 0.1.0 (11)

**Logs:**
Logs were emailed.

**Comment by sgriff96** [comment]
I think this is a bit of a technical limitation at the moment? @gkasdorf would know more though.

**Comment by martinjose** [comment]
@sgriff96 I did some further testing and found that the issue I am referring to only occurs when clicking on an image thumbnail from the post list while in compact view. At that point the application gets stuck on "Downloading Image..." and becomes unresponsive. Memmy never transitions to the actual share dialog. I have to force close the app to resume using it.

**Comment by eoddc5** [comment]
I cannot replicate this. My phone completes the share request from compact (and regular) modes. @martinjose are you still seeing this issue?

**Comment by eoddc5** [comment]
Setting as critical priority in the case that this is able to be replicated by others

This is ann app crash behavior if it’s actually verified to be a bug and should be fixed asap

“On hold” until validated with reporter and others @sgriff96 @gkasdorf can you two try to replicate?

**Comment by gkasdorf** [comment]
This is actually resolved in the latest version I believe. There was an issue in compact view where the image would not download, however this should be fixed. @martinjose can you download the latest version and see if this still happens?
