### ISSUE TITLE
Error uploading to Imgur when adding pic to comment.

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#495]
When trying to add a picture to a comment, get 'Error uploading to Imgur' immediately.

Occurs before image selection.

0.1.0.11 beta

**Comment by ebits21** [comment]
This was fixed by re-installing the beta based on advice from another user.

🤷🏻‍♂️

**Comment by gkasdorf** [comment]
Weird. Did you happen to send any debug logs of this before reinstalling?

**Comment by ebits21** [comment]
No sorry
