### ISSUE TITLE
Request: Swiping far to the left should bookmark post, especially in compact mode.

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#497]
**Is your feature request related to a problem? Please describe.**

In compact mode there is no way to bookmark a post.

**Describe the solution you'd like**
Swiping further left on a post than reply should allow for bookmarking the post.

**Describe alternatives you've considered**
A button in compact mode, but I don't think there's room.

**Additional context**
I believe Apollo also did this (at least as an option).

**Comment by sgriff96** [comment]
Dupe of #231
