### ISSUE TITLE
Add button to search field to initiate search in case keyboard is not currently shown.

### ISSUE THREAD

**Issue by jerdrb** [Memmy-App/memmy#498]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to execute a search from the text currently in the search field is via the keyboard button.

**Describe the solution you'd like**

This should also include a button in the search text field, so that a user does not need to deactivate the keyboard if it was already dismissed.

**Describe alternatives you've considered**

Another advanced feature could be to perform live search results as the user types, though this could be additional overhead and the user could decide to not want to perform the search after they've populated the field.

**Comment by sgriff96** [comment]
Do you mean like a "Search" button to initiate the search, if the keyboard is hidden? Not quite following atm

**Comment by jerdrb** [comment]
Yes. See googles interface or DuckDuckGo. Both have a button to press if the "enter" key or search button on the keyboard are not used.

**Comment by sgriff96** [comment]
What we have currently is a common iOS design pattern. I don't think a single Apple app does this. Gmail doesn't either, etc. I can't think of a case where I would have the keyboard away either when searching unless i accidentally clicked it away. For these reasons, closing this issue.
