### ISSUE TITLE
Is there a way to edit out links in titles?

### ISSUE THREAD

**Issue by michikade** [Memmy-App/memmy#502]
**Is your feature request related to a problem? Please describe.**
Memmy’s titles show the text and doesn’t support links so any post from a Mastodon user looks like a mess:

![image](https://github.com/Memmy-App/memmy/assets/6156381/f4bf79f1-8000-4a3f-bb78-990a63df4f8c)

**Describe the solution you'd like**
Is there a way to edit out the links and just show it as text in titles?  Just for readability’s sake.  I don’t know if titles can be made to actually have clickable links so if it could parse out the markdown that would be helpful.

**Additional context**
I’m pretty sure this is just a Mastodon posting to Lemmy communities issue.

**Comment by sgriff96** [comment]
Yea we just need to handle this better. Strip out the link url but keep the text of the link
