### ISSUE TITLE
Context Menu for Posts from Post Feed views

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#506]
Please add the ability to open the post context menu from the post feed view. 

This should be accessible by long pressing and also a 3-dot menu in the upper right of the post card. 

The context menu should contain the following actions…

1. Upvote
2. Downvote
3. Save
4. Hide
5. Report
6. Block User
7. Block Community
8. Subscribe to Community

**Comment by eoddc5** [comment]
medium priority based on capabilities to add contextual actions

**Comment by Bcrabbers** [comment]
I’d love to see this. An ability to longpress the community or user name from the feed (eg, All) to have those contextual menu options would be great!

**Comment by Genfood** [comment]
> medium priority based on capabilities to add contextual actions

Just out of curiosity, does this mean that the “chosen” framework doesn't support a context menu via peek and pop?  
I really loved this feature in Apollo.

**Comment by sgriff96** [comment]
Blocked by #663

**Comment by gkasdorf** [comment]
Being worked on now, for the record. 👍
