### ISSUE TITLE
Unable to Upvote/Downvote posts from Profile

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#509]
When visiting a profile, go to the Posts for that user, try to upvote/downvote posts they have made.

**Comment by Felix-Staud** [comment]
I will have a look at this

**Comment by gkasdorf** [comment]
@Felix-Staud UserPostsScreen, line 25 needs to be passed the `setPosts` prop with value `profile.setPosts`

**Comment by gkasdorf** [comment]
Technically UserSavedPostsScreen would need to be passed the same, but this whole component can really be removed. It's copy-pasta from UserPostsScreen. It would be better to simply pass a parameter to this screen like `isSavedPosts` and set the header accordingly with `isSavedPosts && navigation.setOptions({title: "Saved Posts"})` in a `useEffect`

**Comment by Felix-Staud** [comment]
> Technically UserSavedPostsScreen would need to be passed the same, but this whole component can really be removed. It's copy-pasta from UserPostsScreen. It would be better to simply pass a parameter to this screen like `isSavedPosts` and set the header accordingly with `isSavedPosts && navigation.setOptions({title: "Saved Posts"})` in a `useEffect`

I can do that.

I'mma hijack this conversation for a quick question:

My `main` branch is broken (synced just now):
<img width="811" alt="image" src="https://github.com/Memmy-App/memmy/assets/50131232/ed610d45-f513-46fd-b920-b9b913f67a7e">

**Comment by gkasdorf** [comment]
Oh damn, can you do me a favor and import useNavigation in that file inside of the PR?

**Comment by Felix-Staud** [comment]
Unfortunately there is 2 origins for these imports:
<img width="527" alt="image" src="https://github.com/Memmy-App/memmy/assets/50131232/4421174b-25b2-4e9b-bfc7-4440399abdc2">
I assume its `.../native`

Same goes for the type:

<img width="698" alt="image" src="https://github.com/Memmy-App/memmy/assets/50131232/6954f991-7eca-44dd-9750-e74a71fc676f">
 I guess it's `@react-navigation`

**Comment by gkasdorf** [comment]
Use the one from /native and the one from the scoped package. Honestly not sure why you are seeing both of those for the latter, doesn't show up that way for me and I use WebStorm as well. But yea, the top import for both. Thanks

**Comment by Felix-Staud** [comment]
> Use the one from /native and the one from the scoped package. Honestly not sure why you are seeing both of those for the latter, doesn't show up that way for me and I use WebStorm as well. But yea, the top import for both. Thanks

IntelliJ is sometimes a pandoras box for me. I've had (local) java classes not being recognised way too many times...
