### ISSUE TITLE
Option to disable endless scrolling

### ISSUE THREAD

**Issue by broizter** [Memmy-App/memmy#512]
It might seem counter intuative but it would prevent "doomscrolling" that a lot of us end up doing. I think having to press next page would eventually send a signal to the brain to stop scrolling when you're just scrolling for the sake of it.

**Describe the solution you'd like**
An option in the settings page to disable endless scrolling and enable pages instead like the web version of Lemmy.

**Comment by bzcorn** [comment]
Perhaps it could also be nice to have the ability to have X number of posts per day before a warning pops up?

**Comment by broizter** [comment]
> Perhaps it could also be nice to have the ability to have X number of posts per day before a warning pops up?

It's a good idea but personally I would prefer per hour instead. I guess ideally there would be a setting that's fully customizable so you can go with whatever kind of limit you prefer. More complex to implement though. Probably.

**Comment by sgriff96** [comment]
I think we just won't implement this right now sorry, though I understand the struggle lol
