### ISSUE TITLE
Add Settings Menu to main/home screen

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#513]
**Describe the solution you'd like**

The settings icon added to the bottom right of the home screen.  

I feel that the “Traverse” section could be moved to upper left as a menu/left drawer of sorts. 

The bottom icons would then be ordered as follows:

Feed, Inbox, Profile, Search, Settings

**Comment by bviefhues** [comment]
Sharing another view here. I absolutely want Traverse in the bottom tabs. 

Settings is not important enough for a prime spot in the bottom tabs, in my opinion. 

Alternatives:

Combine Feed and Traverse Apollo style to free a bottom tab. 

Put settings in the top left.

**Comment by harryprayiv** [comment]
I agree that settings is buried.  Often it is hard to find.  


I also think the account section should be decoupled from the settings page and coupled to the account switching element instead (wefwef and Apollo have this more dialed in, though still not perfect, IMO).  I am not a fan of the current account switching aspect only living in the feed tab too but that's a different issue.

**Comment by sgriff96** [comment]
> I agree that settings is buried. Often it is hard to find.
> 
> I also think the account section should be decoupled from the settings page and coupled to the account switching element instead (wefwef and Apollo have this more dialed in, though still not perfect, IMO). I am not a fan of the current account switching aspect only living in the feed tab too but that's a different issue.

This will be in the next build to at least make it easier to access the Accounts page from the switcher. We are considering something like a long press on the Profile button also opening the account switcher.

![CleanShot 2023-07-09 at 16 05 02](https://github.com/Memmy-App/memmy/assets/46509416/bf1657d4-92dd-4b0a-b80c-ddc9602c6f64)

**Comment by theycallmebeez** [comment]
I feel pressing the Profile icon should allow changing accounts from profile page. I also think long pressing to have a quick toggle would be nice. 

I do not personally think there needs to be an account switcher on the main feed. I don’t think this would be highly used. 

I think that space would be better used to open a quick menu to toggle between favorite communities.

**Comment by ebits21** [comment]
> > I agree that settings is buried. Often it is hard to find.
> 
> > 
> 
> > I also think the account section should be decoupled from the settings page and coupled to the account switching element instead (wefwef and Apollo have this more dialed in, though still not perfect, IMO). I am not a fan of the current account switching aspect only living in the feed tab too but that's a different issue.
> 
> 
> 
> This will be in the next build to at least make it easier to access the Accounts page from the switcher. We are considering something like a long press on the Profile button also opening the account switcher.
> 
> 
> 
> ![CleanShot 2023-07-09 at 16 05 02](https://github.com/Memmy-App/memmy/assets/46509416/bf1657d4-92dd-4b0a-b80c-ddc9602c6f64)
> 
> 

Long pressing to change profiles would be great

**Comment by harryprayiv** [comment]
> Long pressing to change profiles would be great

Definitely.  It would make things less intuitive but, like swipe voting, it would cleanup the interface significantly.
