### ISSUE TITLE
Block Users doesn’t seem to work

### ISSUE THREAD

**Issue by michikade** [Memmy-App/memmy#516]
**Describe the bug**
When attempting to block a user, the toast does not pop up saying the block was success and the web’s settings do not list the user as blocked.

**To Reproduce**
1. Go to any user
2. Click on the … menu
3. Click block user
4. See error (or nothing)

**Expected behavior**
The toast should pop saying user was blocked successfully (or unsuccessfully) like it does with communities.  The user should also show blocked on the web.

**Screenshots**
I attempted to block myself on one instance from a user on another instance to show this bug so I’m not being rude to someone else in the video:

https://github.com/Memmy-App/memmy/assets/6156381/1ce790d6-dac4-4004-a2a0-00885041b491

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17 db 3
 - Version 0.1.0 (11)

**Comment by gkasdorf** [comment]
Fixed. Will be in next build.
