### ISSUE TITLE
Can’t switch accounts

### ISSUE THREAD

**Issue by phareous** [Memmy-App/memmy#517]
**Describe the bug**
I’m logged into lemmy.world, beehaw, and lemm.ee. When I switch between them the feed often won’t update, and there is no error given

i emailed the debug log

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone [model] iPhone 12 mini 
 - OS: [e.g. iOS8.1] 16.5.1

**Logs:**
If you wish to submit any debug logs, you may do so by doing the following:
 - Navigate to Settings
 - Tap version number 5 times
 - Press "Send Logs"

This will open an email in your mail app with the logs in the body of the email. 

If you want, you can post them here. However, although there should not be any PII inside of the logs, it may be best to just send them privately. If you do want to post them here, please either find and provide the applicable parts of the logs, or check them for any PII.

**Additional context**

**Comment by sgriff96** [comment]
TestFlight or App Store version?

**Comment by phareous** [comment]
Test flight

**Comment by sgriff96** [comment]
Please include a video, I can't reproduce this

**Comment by phareous** [comment]
0.1.0  (11)

**Comment by phareous** [comment]
I’ll have to figure out how to do a video on iphone but here are some screenshots 
![IMG_3543](https://github.com/Memmy-App/memmy/assets/1590943/06362d9d-f0a1-43b5-baba-0a6a54904f98)
![IMG_3542](https://github.com/Memmy-App/memmy/assets/1590943/b6ed1268-dd66-479e-bc7d-41f50a9f6574)
![IMG_3541](https://github.com/Memmy-App/memmy/assets/1590943/c60e0b8f-286c-4ffc-b9cd-dca5c6f1ec97)

**Comment by phareous** [comment]
Well in trying to record it, it started working. It appears beehaw wasn’t updating but now it is. I wonder if it might be helpful to have some spinning icon or something when it is refreshing the feed so that you know it is trying to do something

**Comment by Polyfun** [comment]
I think I had the same problem, where one account was lemmy.world, and the other one was https://feddit.uk. The feed for second account would not update and when I went into a post, it would display “Error getting replies” or something similar. I deleted the https://feddit.uk account, then added it again without the protocol prefix, I.e. feddit.uk. This seems to have fixed the problem.

**Comment by FL350** [comment]
@Polyfun Thanks, that resolved the issue for me. I had added the HTTPS in the URL. Might be worth stripping that from inputs. 

I noticed I couldn’t edit my credentials though. No keyboard would pop up. I had to delete the account and start over. Not sure if that’s by design so I won’t put a ticket in for it.

**Comment by gkasdorf** [comment]
@FL350 It *should* be stripping that out anyway. I'll look to see why that might not be happening.

**Comment by eoddc5** [comment]
Is this still happening with the newest updates or has this been fixed? @gkasdorf @phareous

**Comment by phareous** [comment]
I had to update the accts after that hack but it works. It needs to give an error when it fails instead of silently just doing nothing and a spinner would be helpful too since it might take 5 seconds or more to refresh the feed sometimes

**Comment by eoddc5** [comment]
@phareous can you make the above into a separate enhancement request?
