### ISSUE TITLE
Specific default sort option for communities

### ISSUE THREAD

**Issue by enghseb** [Memmy-App/memmy#521]
While browsing the feed, top by something like 1, 6 or 12 hours is a great experience. But going into a specific community, it's not. Because many communities have very little content. So you'd rather want it sorted by something like new (otherwise some communities end up empty, almost looking like a bug). But right now you have the same sort option for both. 

This could be solved by letting us have different sort options for the feed, and for communities we visit. 

Another solution, is to have Lemmy remember the last sort option we've chosen for a specific community. But that might require more work.

**Comment by gkasdorf** [comment]
This is done.
