### ISSUE TITLE
Replace 'moment.js' with 'dayjs'

### ISSUE THREAD

**Issue by Felix-Staud** [Memmy-App/memmy#525]
**Is your feature request related to a problem? Please describe.**
`moment.js` is not even recommending itself anymore (see https://momentjs.com/docs/#/-project-status/).

**Describe the solution you'd like**
I personally had very good experience with day.js https://day.js.org/.
_Might also be more secure not sure though if any of them are a security threat._

**Describe alternatives you've considered**
[Luxon](https://moment.github.io/luxon/#/) - no experience
[date-fns](https://date-fns.org/) - not a fan (personally)
[js-joda](https://js-joda.github.io/js-joda/) - not a fan of java based to js projects

**Additional context**
<img width="423" alt="image" src="https://github.com/Memmy-App/memmy/assets/50131232/d7e4758a-0944-4645-be1f-84ac67c2aade">

**Comment by sgriff96** [comment]
Sounds like a good idea. If anyone can help with this that would be great, don't have the bandwidth atm.

**Comment by gkasdorf** [comment]
Yea, probably would get rid of a few issue that we are having with moment anyway.

**Comment by Felix-Staud** [comment]
I can address it

**Comment by bohn002** [comment]
Took a stab at it, hope that was ok? Love the app and just wanted to contribute something.

**Comment by gkasdorf** [comment]
This is finished. Thanks @bohn002 🥳
