### ISSUE TITLE
[MEM-81] Collapsing posts

### ISSUE THREAD

**Issue by tcripe4** [Memmy-App/memmy#53]
**Is your feature request related to a problem? Please describe.**

being able to collapse posts

**Describe the solution you'd like**

A similar solution like Apollo would be great. Just clicking on the post would collapse it

**Describe alternatives you've considered**

**Additional context**

<sub>[MEM-81](https://linear.app/memmyapp/issue/MEM-81/collapsing-posts)</sub>

**Comment by gkasdorf** [comment]
Thanks, added to roadmap.

**Comment by gkasdorf** [comment]
Done.

**Comment by tcripe4** [comment]
@gkasdorf 
Sick thanks
