### ISSUE TITLE
Default comment sort option

### ISSUE THREAD

**Issue by R3vXX** [Memmy-App/memmy#530]
**Is your feature request related to a problem? Please describe.**
When going into large posts (ie communities that do daily or weekly discussion threads) it’s frustrating to have to change the comment sort to new every time I pull up the post.

**Describe the solution you'd like**
A global, default comment sort option in content settings like we have for post sorting. 

**Describe alternatives you've considered**
Sorting choice persistence for specific posts might also make this less frustrating.

**Comment by ktgd** [comment]
This was added in #445 and will be in the next app store release. Thank you
