### ISSUE TITLE
Edit comment feature doesn't submit edit.

### ISSUE THREAD

**Issue by roskelld** [Memmy-App/memmy#533]
**Describe the bug**
The edit comment feature allows you to write the edit, but after submitting it the edit is rejected and the original comment remains. 

**To Reproduce**
1. Go to a previously published comment. 
2. Click on the ... button in top right of comment. 
3. Click on 'Edit Comment' button
4. Write edit. 
5. Click on 'Submit'
6. See that published comment does not show edit. 

**Expected behavior**
Comment should show edited version. 

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: 15

**Additional context**
Just to confirm that the edit is dropped I tried editing the comment again to see if the edit was there and it wasn't a case that the published view was using a cached version of the original. The edit is not in the comment though and is dropped, so looks like the edit is never getting submitted or is being rejected.

**Comment by sgriff96** [comment]
I believe it's sometimes a state issue. The edit goes through but the comment view doesn't get updated. Sometimes this happens to me and if i go to my profile and look at the comment it is updated. Can you confirm that's not happening? Maybe edit on the app and then check on the website to make sure?

**Comment by roskelld** [comment]
Yes. Can confirm by looking at the comment via my profile I see the edited comment. Refreshing the thread after making an edit does not update to show so there is an issue there. 

Also, due to the second part this creates another issue. If I edit a comment and then edit it again before seeing the updated comment go live, the first edit is stomped on. 

In this test I edited the comment multiple times but on the third I did not go to my profile to see the third edit live before making the fourth edit and as you can see the third edit does not exist in the post. 
https://lemmy.world/comment/1036940

**Comment by sgriff96** [comment]
Thank you for checking. I'll look into it today hopefully

**Comment by bviefhues** [comment]
Had this earlier today. Collapsing and un-collapsing did show the edit.

**Comment by gkasdorf** [comment]
@sgriff96 For the record, the issue isn't that it isn't submitting the edit. It does, but the comment does not get updated (same with deleting a comment).

My guess is that FlashList isn't updating the comments since it isn't actually changing the props. Probably need to add a switch to `extraData` with a `setRefreshList(prev => !prev)`.

I'll go ahead and do this if you want.

**Comment by sgriff96** [comment]
> @sgriff96 For the record, the issue isn't that it isn't submitting the edit. It does, but the comment does not get updated (same with deleting a comment).
> 
> 
> 
> My guess is that FlashList isn't updating the comments since it isn't actually changing the props. Probably need to add a switch to `extraData` with a `setRefreshList(prev => !prev)`.
> 
> 
> 
> I'll go ahead and do this if you want.

Yep that's what i figured
