### ISSUE TITLE
“Mark Read on Image View” + “Hide Read” doesn’t work

### ISSUE THREAD

**Issue by lazyjiji** [Memmy-App/memmy#534]
**Describe the bug**
With both “Mark Read on Image View” and “Hide Read Posts of Feed” enabled, pressing the “Hide Read” button on bottom right while viewing feed will hide other posts, but not ones where just the image was clicked in to. Must click in to the post itself or vote for the hide to work. 

**Expected behavior**
When clicking in to the photo itself, then exiting it, should mark the post as read so it will be hidden with the button. 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 16.5.1
 - Version 0.1.0 (11) TestFlight Beta

**Logs:**
If you wish to submit any debug logs, you may do so by doing the following:
 - Navigate to Settings
 - Tap version number 5 times
 - Press "Send Logs"

**Comment by gkasdorf** [comment]
Known issue. We will get to it. Thanks.

**Comment by lazyjiji** [comment]
Thank you, I looked through the open bugs but hadn’t seen it. Sorry!

**Comment by gkasdorf** [comment]
@lazyjiji No problem, it wasn't an open bug I don't think, just something that I had noticed. Gonna work on it now.

**Comment by gkasdorf** [comment]
Fixed now.
