### ISSUE TITLE
Italics render as bold in comment text.

### ISSUE THREAD

**Issue by roskelld** [Memmy-App/memmy#535]
**Describe the bug**
Adding italics to comment text via the I button shows as bold in the published comment render. 
The italics button wraps text in between `**` (two sets of asterisk) when it should be `_` (an underscore). 

**To Reproduce**
1. Go to a thread and add a comment. 
2. Click on the I (italics) button and type in text. Click on the I button to close the italics. 
3. Submit comment. 
4. See error in published comment. 

**Expected behavior**
Text should show as _italics_ and not **italics** 

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/18073522/918dada2-eb99-40d5-b1ef-9876e13d4c96)

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: 15

**Comment by theycallmebeez** [comment]
The italics button adds two asterisk and then you are supposed to enter your text inside of that. Or select your text then press italics to make it italic. 

In markdown you can use single asterisk on each side of text to make italic.

**Comment by roskelld** [comment]
Ah, I wasn't aware of the single `*` wrapper. Then that's not obvious from the UX as the text entry caret is left on the right side of the `**` requiring the user to manually move it to the inside, which isn't exactly easy on a touch screen device. 

Just testing the UX of the GitHub app on iPhone and that adds two `_` and injects the caret in-between to allow you to keep on typing, then you need to tap on the right to type standard. Also, Github uses `_` as an italic marker, which does help make it more distinctive from bold when not using a WYSIWYG input.

**Comment by sgriff96** [comment]
Github uses a different kind of markdown than lemmy

**Comment by eoddc5** [comment]
@sgriff96 so should we close as not planned?

**Comment by lazyjiji** [comment]
It may be helpful to change it to work like in Apollo where after you click the italics/bold option, the text cursor is placed within the modifiers so the user doesn’t have to manually move the cursor between the asterisks. If that’s possible.

**Comment by sgriff96** [comment]
@eoddc5 yea. @lazyjiji I'd recommend making a separate enhancement request for that.
