### ISSUE TITLE
Answer a comment

### ISSUE THREAD

**Issue by kingmath** [Memmy-App/memmy#537]
I would like to be able to reply directly to a comment.

**Describe the solution you'd like**
A click on a button reply opens an input field. In this I can write text to reply to the comment.

**Describe alternatives you've considered**

I clicked on the three dots. Here you can only copy the text, copy the link or report the comment.

**Additional context**

![IMG_1627](https://github.com/Memmy-App/memmy/assets/16158664/1e46c74b-3987-4319-ace9-62353e2ec8b5)

![IMG_1628](https://github.com/Memmy-App/memmy/assets/16158664/9e5adeab-3f81-4158-bb0d-86667ec10863)

**Comment by sgriff96** [comment]
In the App Store build you can swipe left on a comment to reply, and in the Test Flight build there are also buttons to reply, upvote, and downvote. This will be in the App Store eventually.
