### ISSUE TITLE
Current Username Should Be Visible Everywhere.

### ISSUE THREAD

**Issue by harryprayiv** [Memmy-App/memmy#541]
Overall the app is great but it could use some polishing on the interface.

Specifically the subject of this issue is: 

**Right now, when I am in any tab other than the feed one, I can't tell which username I am currently switched to.**  

I like the way that Apollo and wefwef have it at the top left and the accounts stuff is a popover but maybe a better solution for your design is to actually have the username listed instead of the generic "profile" text on the button.  This could be a challenge because of the sheer length of some usernames (not to mention the fact that many people have a few of the same username across many instances, necessitating the instance to be listed there too).

**Comment by sgriff96** [comment]
What do you mean wefwef has it at the top left?

**Comment by gkasdorf** [comment]
@sgriff96 I was thinking about adding this to the bottom tab instead of just "Profile", but the issue I am concerned about is name length. It wouldn't be a huge deal if it was guaranteed to be a different username, but they very well could have gkd@lemmy.ml and gkd@lemmy.world, so just displaying `gkd` would be pointless.

Using both the username and instance could easily result in some weird stuff like username4032@lemmy.world. Super long.

Thoughts on how else to do this?

**Comment by sgriff96** [comment]
> @sgriff96 I was thinking about adding this to the bottom tab instead of just "Profile", but the issue I am concerned about is name length. It wouldn't be a huge deal if it was guaranteed to be a different username, but they very well could have gkd@lemmy.ml and gkd@lemmy.world, so just displaying `gkd` would be pointless.
> 
> 
> 
> Using both the username and instance could easily result in some weird stuff like username4032@lemmy.world. Super long.
> 
> 
> 
> Thoughts on how else to do this?

Don't think i like making it under profile for the reasons described. I think just maybe long pressing profile to see the account picker and current account is good enough. I was gonna work on this tonight

**Comment by harryprayiv** [comment]
Good point about the long usernames. 

The way wefwef currently does it is not to have the word 'profile' but instead the instance you are logged into.  Maybe a hybrid of that approach plus the username currently logged in at the top left (or the user icon??) at top left.

**Comment by harryprayiv** [comment]
> What do you mean wefwef has it at the top left?

I was mistaken.  Voyager (formerly wefwef) has that users menu at the top left only available when you're in the profile page.

**Comment by sgriff96** [comment]
Closing as not planned, we do plan on doing _something_ with the username but this issue's not quite relevant
