### ISSUE TITLE
User Avatar Size in Comments View

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#546]
Please make the user avatar size the same as the “default user icon” to preserve alignment. 

See example below. The user with avatar and the user without avatar are not aligned. 

![IMG_0875](https://github.com/Memmy-App/memmy/assets/382845/1839efc2-4579-4c92-910b-ac1d2ea8e6fb)

**Comment by sgriff96** [comment]
Pretty sure i just changed this by accident lol
