### ISSUE TITLE
Community Moderators in Sidebar

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#547]
As a Memmy user, I’d like to see the Mods for a Community when viewing the sidebar/about. 

Example from mlem below. 
![IMG_0876](https://github.com/Memmy-App/memmy/assets/382845/a7fea653-9e1e-45d2-a063-b8405a157a86)

**Comment by theycallmebeez** [comment]
Can use ‘getCommunity’ and check the 
/moderators attribute.

**Comment by gkasdorf** [comment]
This is done.
