### ISSUE TITLE
Cakeday Still Incorrect 

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#550]
The cake day date is incorrect. This user has been on Lemmy for 3 years but the cake day says January 2023, which is neither their actual cake day or their upcoming cake day… so I’m not quite sure what the date is supposed to indicate. 

![IMG_0877](https://github.com/Memmy-App/memmy/assets/382845/8b51215b-dfa8-4b6a-ada5-62d3de4ae613)

**Comment by gkasdorf** [comment]
Fixed. It will try to just be the user's birthday instead. We already show how old the account is, so we don't need to show the original sign up year.
