### ISSUE TITLE
Account logout button

### ISSUE THREAD

**Issue by Felix-Staud** [Memmy-App/memmy#553]
**Is your feature request related to a problem? Please describe.**
Once logged into an account you can't log out of it.

**Describe the solution you'd like**
A button to delete/logout of an existing account

**Describe alternatives you've considered**
Creating a duplicate account this being able to delete the existing one.

**Additional context**
![image](https://github.com/Memmy-App/memmy/assets/50131232/1f746eac-b79c-4110-8161-604d23a54e5d)

**Comment by feyder213** [comment]
After the recent hacks and invalidations of cookies on lemmy.world and others it makes it apparent that a logout option is needed, or alternatively the ability to delete a single account from the app. Also the wording on the delete button maybe could be changed to remove, or delete from app. I had trepidations about using it worrying it might delete my account on lemmy itself.

**Comment by sgriff96** [comment]
We should rename it to say "Remove account" instead of delete as well

**Comment by Felix-Staud** [comment]
> We should rename it to say "Remove account" instead of delete as well

it says logout now. guess thats fine
