### ISSUE TITLE
Clicking "Manage Accounts" from account selector drop-down doesn't open the screen

### ISSUE THREAD

**Issue by ktgd** [Memmy-App/memmy#561]
**Describe the bug**
After selecting the "Manage Accounts" option in the drop-down, the accounts window opens. However, clicking on "edit accounts" on this screen doesn't open the proper screen.

**To Reproduce**
1. Click "Manage Accounts"
2. Click "edit account"
3. Nothing pops up 
4. Go to profile tab. The proper window opens here.

**Expected behavior**
The edit account screen should open from the original screen.

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS16.5.1
 - Version 0.1.0 (14)

**Comment by Felix-Staud** [comment]
I'm not 100% fond of the UI yet: may is an what drop down you are talking about ? I wasn't able to find it

**Comment by sgriff96** [comment]
Oh damn it. I know the problem. I hate how navigation works in mobile dev 😥

**Comment by Felix-Staud** [comment]
@sgriff96 so this is fixed in main ?

**Comment by sgriff96** [comment]
> @sgriff96 so this is fixed in main ? 

I have a branch with the fix that I'll merge today
