### ISSUE TITLE
Link at top of comment cannot be tapped

### ISSUE THREAD

**Issue by chrismarquardt** [Memmy-App/memmy#566]
**Describe the bug**
Link at top of comment doesn’t react to tap. Possibly iOS beta-related even though I believe I also ran into this on 16.5 

**To Reproduce**
1. Go to https://lemm.ee/comment/903488
2. Find the comment by stardust that starts with the link „They’re made out of meat“ (as of posting this it’s at the top)
3. Try to tap that link 

**Expected behavior**
Website opens

**Screenshots**
![IMG_3820](https://github.com/Memmy-App/memmy/assets/2527608/d4a50013-feab-439a-9bcd-1f610be32d13)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 pro 
 - iOS 17 beta 3
 - Lemmy 0.1.0 (14)
 - using Dark theme

**Comment by sgriff96** [comment]
Looks like this only happens with "Use Default Browser" set to on.

**Comment by gkasdorf** [comment]
This could have been an issue with some link parsing too, wondering if this is still happening?

**Comment by gkasdorf** [comment]
Links are fixed now.
