### ISSUE TITLE
Screen darkens when going out of image view

### ISSUE THREAD

**Issue by br337** [Memmy-App/memmy#568]
**Describe the bug**
When swiping down to exit image view, the screen transitions to black. When doing this quickly, the app gives the effect of a flash. This is much more noticeable in light mode than in dark mode. This can become very irritating to the eye when the user uses light mode.

**To Reproduce**
1. Select a light mode theme
2. Go to the front page
3. Press on an image to enter image view 
4. Swipe down slowly to exit image view
5. See how screen darkens until leaving image view

**Expected behavior**
A smoother transition, maybe fading out.

**Video**

https://github.com/Memmy-App/memmy/assets/49288125/ffb37bdd-66c5-475a-aa32-4bd3a0ead913

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS
 - Version: 16.5.1

**Comment by gkasdorf** [comment]
@br337 Are you saying that you think the background of the viewer should be white whenever using a light theme?

**Comment by gkasdorf** [comment]
@br337  Still a work in progress but is this more what you're thinking?


https://github.com/Memmy-App/memmy/assets/127079571/f4ca25c1-6a3c-4dcd-bc75-889f40c24527

**Comment by br337** [comment]
Yes. That would be what I was thinking about. Looks awesome.
