### ISSUE TITLE
Unable To Add Account From Feed

### ISSUE THREAD

**Issue by ainen** [Memmy-App/memmy#579]
**Describe the bug**
When attempting to add an account from the Feed, the “Add” button does nothing. 

**To Reproduce**
1. Go to “Feed” tab
2. Tap on account switcher at the top
3. Choose “Manage Accounts”
4. Tap “Add”

**Expected behavior**
The “Edit Account” page should show up. 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17 Beta 3
 - Version 0.1.0 (14)

**Additional context**
If you navigate to the “Profile” tab while experiencing this bug, you are automatically moved to the “Edit Account” page.

**Comment by ktgd** [comment]
Should be fixed in the next release.
