### ISSUE TITLE
Subscriptions not working

### ISSUE THREAD

**Issue by graham-pyett** [Memmy-App/memmy#583]
**Describe the bug**
I have my app set to show subscribed as the default, but over the past day or so whenever I open the app I see “No posts found. Maybe you should get a conversation started?”  If I change my view to “all” and then pull down to refresh, then I see posts from everywhere. Changing back to “subscribed” and refreshing doesn’t update it again to be only my subscriptions 

![IMG_5110](https://github.com/Memmy-App/memmy/assets/47046755/f148a579-a7c5-40c7-b888-9058d440e5d0)

![IMG_5111](https://github.com/Memmy-App/memmy/assets/47046755/a105c958-6596-49ec-81c3-de840ad31b7f)
(I’m not subscribed to Linux or food porn, makes sense as it’s on “all”)

![IMG_5112](https://github.com/Memmy-App/memmy/assets/47046755/b16e076d-0a30-4266-b184-7bca0b1bf033)
(Same content despite now being on “subscribed”)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max 
 - OS: [e.g. iOS16.5]
 - Version [e.g. 0.0.1 (14)]
 - I also noticed that I was one version behind when I took the screenshots, but the issue persists despite updating

**Comment by ebits21** [comment]
Does re-installing the app work? There's I had a similar issue with no subscriptions in traverse.

I think related to the lemmy.world hacking issues and resetting the token.

**Comment by JayKayUk** [comment]
Yes, reinstalling fixed it

**Comment by eoddc5** [comment]
this issue was due to Lemmy world issues, fix is by logging out and back in, or uninstalling and reinstalling

not a memmy issue

**Comment by ktgd** [comment]
It looks like this was related to the tokens being reset by lemmy.world so I'm going to close this. If this is still not working, please re-open this issue.
