### ISSUE TITLE
Account problems after JWT cycle

### ISSUE THREAD

**Issue by jenkshields** [Memmy-App/memmy#584]
**Describe the bug**
My instance (beehaw) cycled JWTs after the recent vulnerability and required all users to log in again.

Opening Memmy shows “no posts found” which is expected - signing back in via going to the account page, tapping edit account, and saving fixes this problem temporarily, but not consistently. Reopening the app later shows the same “no posts” until ‘logging in’ again.

I wonder if actually logging out might solve this problem, but I can’t seem to find how!

**To Reproduce**
1. Have an account on beehaw (or presumably another instance who took similar actions after the recent vulnerability)
2. Open Memmy
3. ‘Sign in’ again by going to accounts, edit account, and hitting save
4. Return to timeline to see posts
5. Close the app, and return to timeline to see problem again

**Expected behavior**
Re-logging in via saving on the edit account page would solve this issue permanently 

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: ios17db3
 - Version 0.1.0 14

**Comment by ktgd** [comment]
Duplicate of #560 
A PR has been submitted meaning this should be fixed in the next release.

**Comment by jenkshields** [comment]
Aroha mai, should have checked this wasn’t reported already!
