### ISSUE TITLE
Long-press community or username for contextual options

### ISSUE THREAD

**Issue by Bcrabbers** [Memmy-App/memmy#589]
As I'm scrolling down All and looking for communities to join (or occasionally block), instead of tapping on the community name, and then tapping subscribe then tapping out (or tapping the 3 dots to block), it would be great to long press the community name and have a contextual menu show up giving me options like subscribe/unsubscribe, block, sidebar/info, etc.

Likewise for users: long press their name to send message, block, or (when the feature gets added) follow.

**Comment by Bcrabbers** [comment]
Closing this as there’s previous similar request

**Comment by Felix-Staud** [comment]
@Bcrabbers please be so kind and link those “precious similar requests” in here

**Comment by Bcrabbers** [comment]
> @Bcrabbers please be so kind and link those “previous similar requests” in here

Good call. Here ya go…
This posts essentially requests the same function:
https://github.com/Memmy-App/memmy/issues/506
