### ISSUE TITLE
Default Sort "new" crashs the app

### ISSUE THREAD

**Issue by homer1993** [Memmy-App/memmy#594]
**Describe the bug**
I was recently having trouble logging into my lemmy instance, so I deleted the app and am in the process of reconfiguring it. I noticed that when I select the "Default Sort", "new" and "cancel" are swapped. If I click on "new" because I want to select it, it causes a cancel (because it's the button for it, but it's wrongly named). If I click on "cancel", the app closes, probably because it's accessing a non-existent place.

**To Reproduce**

App > Profile > Settings > Content > Default Sort 
Open the Default Sort option shows the current options. 

**Expected behavior**
"cancel" and "new" buttons are switched, cancel cancels the settings, new can be chosen. 

**Screenshots**

![IMG_1279](https://github.com/Memmy-App/memmy/assets/51082485/3a482eeb-ccab-4d3a-9988-24979e0babde)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: 16.5.1
 - Version 0.1.0(14)

Ive checked the situation on my iPad, where I have version 0.0.2(16) installed. Their the default sort order works just fine. So the bug occured something after 0.0.2.

**Comment by sgriff96** [comment]
@eoddc5 this is fixed in `main` but i think will keep getting reported on since its not deployed

**Comment by gkasdorf** [comment]
Just going to keep this open since we don't want it to be reported again. It is fixed though and will be available in next version.

**Comment by bagobones** [comment]
For me selecting new does nothing and selecting cancel causes a crash.

**Comment by eoddc5** [comment]
@gkasdorf fixed now, then?

**Comment by eoddc5** [comment]
this is now fixed in 0.2.0
