### ISSUE TITLE
Add account not working from top 

### ISSUE THREAD

**Issue by phareous** [Memmy-App/memmy#611]
**Describe the bug**
If you go to manage accounts via the top drop-down and click Add, it does nothing

**To Reproduce**

**Expected behavior**

**Screenshots**

https://github.com/Memmy-App/memmy/assets/1590943/6f13c92c-99a7-4fc1-a642-477a6c5e9e0a

**Smartphone (please complete the following information):**
 - Device: iPhone [model]

**Logs:**
If you wish to submit any debug logs, you may do so by doing the following:
 - Navigate to Settings
 - Tap version number 5 times
 - Press "Send Logs"

This will open an email in your mail app with the logs in the body of the email. 

If you want, you can post them here. However, although there should not be any PII inside of the logs, it may be best to just send them privately. If you do want to post them here, please either find and provide the applicable parts of the logs, or check them for any PII.

**Additional context**

**Comment by eoddc5** [comment]
this works for me

**Comment by gkasdorf** [comment]
This has been fixed in latest build. Will be available with the next app store release, probably tomorrow.

**Comment by phareous** [comment]
Doesn’t work for me? Did you look at the video?

also I discovered that even though the Add button won’t work if I click on the profile icon on the bottom then it goes to the screen for me to enter the credentials

**Comment by phareous** [comment]
I mean seriously if you aren’t going to take bug reports seriously then I’ll just move on to helping test a different app, there are like 8 of them. No need to waste my time if you don’t care about fixing your app
