### ISSUE TITLE
New Posts Cuts Off Suddenly

### ISSUE THREAD

**Issue by Frorayz** [Memmy-App/memmy#614]
**Describe the bug**
Sort by new posts should be scrollable but it just cuts off

**To Reproduce**
1. Go to home
2. Sort by new
3. See behavior

**Expected behavior**
Like Reddit I expected to see new posts, not a handful and that's it 

**Screenshots**
https://github.com/Memmy-App/memmy/assets/32178410/297573a6-c072-45c6-815f-23cc2f34854d

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: 16.5.1
 - Version 0.1.0 (14)

**Comment by eoddc5** [comment]
@gkasdorf this is fixed in 0.2.0?

**Comment by gkasdorf** [comment]
I don't really know what to do about this one, because if we switch the sort it's going to have some weird consequences. But I suppose that's the only way. Will look into it.

**Comment by sgriff96** [comment]
It's behaving as expected - there are no more new posts to look at. We shouldn't do anything different than that.
