### ISSUE TITLE
Push notifications setting not sticking in UI

### ISSUE THREAD

**Issue by phareous** [Memmy-App/memmy#616]
**Describe the bug**
Push notifications setting did not stay turned on in UI when I added a second account

**To Reproduce**

1. Added lemm.ee account.
2. Went back into settings and turned on Push Notifications
3. Added beehaw account
4. When it returned to the screen, push notifications was turned off for lemm.ee. 
5. Turning it back on just results in a never-ending spinner (perhaps because it is really already enabled, but the app just isn't showing that)
6. If I force-quit the app, and relaunch, the setting is turned on. So it appears it really did enable it, it just didn't reflect it in the local UI/cache
7. I repeated this test by enabling notifications on beehaw.org, and adding a new lemmy.world account, and I got the same erroneous results where notifications for beehaw did not show enabled

**Smartphone (please complete the following information):**
 - Device: iPhone [model] iphone 12 mini
 - OS: [e.g. iOS8.1] 16.15.1
 - Version [e.g. 22] 0.2.0 (1) testflight

**Comment by eoddc5** [comment]
Can you provide a screen recording of this taking place?

Push notification selection is showing no issue for me.

**Comment by phareous** [comment]
I'm not sure how to do a recording of this without giving away my passwords. Also it did not happen when I tried it again, which means there may have to be certain conditions - ie the first time you start the app, or adding accounts that have not had the notifications on before. If you want to close it and see if someone else has it happen to them that is fine

**Comment by eoddc5** [comment]
We can keep this open for now and see if anyone else has similar issues

**Comment by CDeLeon94** [comment]
Also indefinite spinner when trying to enable push notifications on my beehaw account

**Comment by CDeLeon94** [comment]
Tried enabling push notifications on another instance, and it worked. Problem solvedeems to be beehaw specific

**Comment by eoddc5** [comment]
ok so this seems to be a beehaw thing, and not memmy

@gkasdorf any clue on this one? if you want to peek at it, otherwise I can close it as an external bug
