### ISSUE TITLE
Floating up arrow button on traverse feed

### ISSUE THREAD

**Issue by eoddc5** [Memmy-App/memmy#618]
Traverse list would also benefit with a floaty up arrow button that appears when you scroll down. Click it to force a return to the top. 

This would be good to add on, especially if the traverse button is removed in favor of the traverse drawer

**Comment by ebits21** [comment]
How about one tap of traverse tab scrolls to top of subscriptions if the tab is in focus and scrolled down.

If it's at the top already, then give search focus?
