### ISSUE TITLE
long press on traverse icon, while in traverse tab, selects the search bar and launches the keyboard

### ISSUE THREAD

**Issue by eoddc5** [Memmy-App/memmy#620]
Since there’s a search bar on the traverse tab, easier access to that bar could be added by holding/long press on the traverse button. 

This then selects the bar, which opens the keyboard for easier typing

This could be launched from the traverse tab only (if possible) or if you’re anywhere else it would bring you to the traverse tab and then open the keyboard up?

Also this depends if we’re keeping the traverse button and not a drawer

**Comment by ebits21** [comment]
How about one tap of traverse tab scrolls to top of subscriptions if the tab is in focus and scrolled down (like the feed tab).

If it's at the top already, then give search focus?

More similar to what people expect to happen when the feed tab is tapped with the scroll behaviour.
