### ISSUE TITLE
Current account in manage accounts screen should reflect last selected account.

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#621]
**Is your feature request related to a problem? Please describe.**
Current account in the manage accounts screen is always set to the first account you added.

**Describe the solution you'd like**
If the user selects another account, the current account should reflect that change.

**Additional context**
![image](https://github.com/Memmy-App/memmy/assets/19845100/0ba8143e-5890-4741-a986-7470ef1d09de)

![image](https://github.com/Memmy-App/memmy/assets/19845100/04998d75-e6a1-455c-82e9-59e471a8327b)

Edit: Better pics

**Comment by eoddc5** [comment]
Picture only shows 1 account so that makes sense. BUT you’re right about the behavior

I have two accounts. My second account is being used (first is non lemmy world failover) but the “current account” shows my first one

Though this seems a purely visual bug

**Comment by ebits21** [comment]
Added better pics.

**Comment by gkasdorf** [comment]
Fixed
