### ISSUE TITLE
Error If Cancelling Add Image To Comment

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#628]
**Describe the bug**
If you attempt to add a picture to a comment, then press cancel, get "Error Uploading to Imgur"

**To Reproduce**
1) Reply with comment.
2) Add image button.
3) Hit cancel.

**Video**

https://github.com/Memmy-App/memmy/assets/19845100/30964879-3f6f-486a-9b30-22adbbe0b4b6

**Comment by eoddc5** [comment]
reproducible

**Comment by Felix-Staud** [comment]
Same thing happens when creating a new post

**Comment by ebits21** [comment]
> Same thing happens when creating a new post

Hmm not for me. Previously I noticed #495 adding pics to comments but went away with re-install.

**Comment by Felix-Staud** [comment]
Should be fixed with the merge of #689
