### ISSUE TITLE
Constantly partially logged out

### ISSUE THREAD

**Issue by drguitarum2005** [Memmy-App/memmy#635]
**Describe the bug**
When I click on “traverse”, I can see many communities that in subscribed to. If I go back to the feed and click my account at the top and click on my only account, it partially logs me out. It still shows my account at the top but my traverse list is gone and I can’t reply or do any actions. I also can’t use the “manage accounts” to do anything. “Edit account” is grayed out. I have to go through settings and get to my account password, delete it, re-enter it, and then I’m finally logged back in fully. 

**To Reproduce**
1. Go to feed
2. Click on my account name at the top
3. Click on my account in the drop down
4. Go go traverse - empty list
5. Reply to a post - unable to
6. Click on “manage accounts” - can’t edit account 

**Expected behavior**
Re-clicking your active account shouldn’t log you out partially 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.6
 - Version 0.1.0 (14)

**Logs:**
If you wish to submit any debug logs, you may do so by doing the following:
 - Navigate to Settings
 - Tap version number 5 times
 - Press "Send Logs"

This will open an email in your mail app with the logs in the body of the email. 

If you want, you can post them here. However, although there should not be any PII inside of the logs, it may be best to just send them privately. If you do want to post them here, please either find and provide the applicable parts of the logs, or check them for any PII.

**Additional context**

**Comment by eoddc5** [comment]
are you using Lemmy.world?

**Comment by drguitarum2005** [comment]
> are you using Lemmy.world?

Yes

**Comment by eoddc5** [comment]
theres been a ton of issues with their server and interactions. I can let @gkasdorf or @sgriff96 be smarter than me and talk about it , but if you are in the discord channel there is a lot of info being put out there

unfortunately, it is not a Memmy issue to fix

but also

fortunately, it is not a Memmy issue to fix
