### ISSUE TITLE
Some images opened directly from feed can’t be closed with swiping

### ISSUE THREAD

**Issue by Taxxor90** [Memmy-App/memmy#637]
**Describe the bug**
On some of the image/meme posts I can’t close the gallery view with a swipe and have to use the x at the top of the screen.

When I first open these posts and then open the image from there, I can swipe up to close it.
But this doesn’t work when I open it directly from the feed view (compact mode). Here up and down swiping does nothing and left/right swiping only moved the image a bit.

**To Reproduce**
Example post 
https://lemmy.world/post/1401317

Open the image by directly clicking it from the Feed view of retrogaming@lemmy.world (post is 28m old at the time of this issue if it helps finding it in the feed)

You can only close the image with the „x“.

Open the post and then click on the image.
You now can swipe up to close it.

**Expected behavior**
Gallery should always close on swipe

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.5.1
 - Version 0.1.1(2)

**Comment by eoddc5** [comment]
this is known and being worked on by @gkasdorf , though im unsure if there is another issue representing it.

ill keep this open unless I find another and close this as dupe.
