### ISSUE TITLE
View webm content in-app

### ISSUE THREAD

**Issue by jenkshields** [Memmy-App/memmy#639]
**Is your feature request related to a problem? Please describe.**
Some (all? Unsure!) instances using pictrs utilise the webm format for animated gifs. Currently it doesn’t look like Memmy can display these, and neither can safari in-app without downloading.

**Describe the solution you'd like**
It would be great if these could be viewed in-app, but I admit I’m not 100% if this is possible.

**Additional context**
Example post: https://beehaw.org/post/1072253

**Comment by gkasdorf** [comment]
I think I see how to do it. I'll check into it tomorrow. I noticed that a lot of webps go around so that would make sense if pictrs is converting them.

**Comment by gkasdorf** [comment]
Should be okay now.
