### ISSUE TITLE
Mark as Read On Scroll

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#646]
**Is your feature request related to a problem?**

Seems to be very frequently requested to have the option to mark as read when the post is scrolled by.

**Additional context**
Frequently requested [here](https://feddit.de/post/1552710) and [here](https://lemmy.world/post/1422095).

**Also**
It seems like maybe this is being worked on but an enhancement issue was never opened?

**Comment by eoddc5** [comment]
So when you’re in a feed and you are scrolling down, you want each post that you pass to become read? Even if you don’t interact with it?

**Comment by ebits21** [comment]
Additional context from #149

![image](https://github.com/Memmy-App/memmy/assets/19845100/2ba6f6e0-7c28-4f37-97c4-7dccf642ec55)

Not sure what happened if anything.

**Comment by ebits21** [comment]
In case someone looks this up.

![image](https://github.com/Memmy-App/memmy/assets/19845100/993faabb-ddb6-4f39-94a7-779234f41ae3)

**Comment by pitrisss** [comment]
I read the conversation above. Is it possible to send API call which would mark more posts as read? If yes, in that case it could be send with next post that is open or after reaching certain threshold.

**Comment by sgriff96** [comment]
> I read the conversation above. Is it possible to send API call which would mark more posts as read? If yes, in that case it could be send with next post that is open or after reaching certain threshold.

What do you mean `mark more posts as read`? The problem is the API does not support marking multiple posts as read on scroll. Since it doesn't do that, we'd have to either send a single request for each post on scroll or like you suggested, keep them saved and send many at once. We'd get rate limited by lemmy doing that, so then we'd have to throttle it ourselves and send them slowly. It's just not worth the effort right now. Hopefully they just add mark multiple posts as read as an option in the API.

**Comment by pitrisss** [comment]
> > I read the conversation above. Is it possible to send API call which would mark more posts as read? If yes, in that case it could be send with next post that is open or after reaching certain threshold.
> 
> @pitrisss What do you mean `mark more posts as read`? The problem is the API does not support marking multiple posts as read on scroll. Since it doesn't do that, we'd have to either send a single request for each post on scroll or like you suggested, keep them saved and send many at once. We'd get rate limited by lemmy doing that, so then we'd have to throttle it ourselves and send them slowly. It's just not worth the effort right now. Hopefully they just add mark multiple posts as read as an option in the API.

Yes, this is what I meant, send one request marking multiple posts. So it’s not supported 🙂. I’m sorry, I was not able to find any API doc whatsoever, so I directly asked.

**Comment by sgriff96** [comment]
@pitrisss no worries, the docs are not great for the API right now lol. I doubt the devs have time to maintain them.

**Comment by gkasdorf** [comment]
@ebits21 This is complete
