### ISSUE TITLE
Explanation Dialog of Hide Read Posts Icon After Selecting 'Hide Read Posts on Feed' Option

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#647]
**Is your feature request related to a problem?**

Many users select the 'Hide Read Posts on Feed Option' but are confused what the hide read posts floating button is. This is a frequently [asked question](https://lemmy.ca/post/1423328).

**Describe the solution you'd like**
A pop up dialog that explains the feature and shows the icon to explain what it is, after the option is selected in settings.

**Additional context**
![image](https://github.com/Memmy-App/memmy/assets/19845100/005c751e-2f0e-456b-899c-789792ffa238)

Suggest a dialog with explanation and picture of icon after selecting this.

![image](https://github.com/Memmy-App/memmy/assets/19845100/d85641cd-483c-4f62-9fb4-b326a6e71e92)

**Comment by sgriff96** [comment]
I think additionally we should just always have it showing instead of the hide animation currently

**Comment by eoddc5** [comment]
@sgriff96 can you add and assign @Joshua-Davis-rose`

**Comment by joshua-davis-rose** [comment]
@sgriff96 Please assign this ticket to me. Thanks!
