### ISSUE TITLE
Clicking Link Crashes App.

### ISSUE THREAD

**Issue by sc0ttwood** [Memmy-App/memmy#648]
So I found a link that crashes the app, below is the post and the video.

Video:
https://share.icloud.com/photos/005HYaf2NU8--6SNMd0_5kLLQ

Post:
https://lemmy.world/post/1414332

**Comment by eoddc5** [comment]
Can you upload the video to GitHub if you want us to see it

i don’t want to join your iCloud album

**Comment by sc0ttwood** [comment]
Git Hub doesn't allow videos so here:

**Comment by eoddc5** [comment]
Yes it does 

https://github.com/Memmy-App/memmy/assets/10222895/3c7f4e10-30e8-4d36-ab98-d8b8341b73c4

**Comment by sc0ttwood** [comment]
> Yes it does
> 
>  RPReplay_Final1689282852.mp4

How? Because I can't get it to embed. And nothing I do gets it to do it. Weird.

**Comment by eoddc5** [comment]
https://github.com/Memmy-App/memmy/assets/10222895/73ba2696-df02-4d95-a38c-5847de80d53d

**Comment by eoddc5** [comment]
> > Yes it does
> > RPReplay_Final1689282852.mp4
> 
> How? Because I can't get it to embed. And nothing I do gets it to do it. Weird.

**Comment by br337** [comment]
You can just drag and drop the video from your computer into the text box.
