### ISSUE TITLE
Cannot Post Due To Language?

### ISSUE THREAD

**Issue by Frorayz** [Memmy-App/memmy#650]
**Describe the bug**
Trying to post but this errors comes up 

![image](https://github.com/Memmy-App/memmy/assets/32178410/811a6dd7-624b-45c7-a278-5ec38d7fc216)

Pretty sure my language is set to English.

**To Reproduce**
Not sure how to reproduce 

**Smartphone (please complete the following information):**
 - Device: iPhone XS MAX
 - OS: 16.5.1
 - Version 0.2

**Logs:**
Sent

**Comment by eoddc5** [comment]
Unfortunately this is an annoying bug on lemmy itself

We’ve tried everything to fix this on our end but it’s reported happening on other apps, web page, etc

https://github.com/LemmyNet/lemmy/issues/3150
