### ISSUE TITLE
Ability to hide the username in feed view

### ISSUE THREAD

**Issue by Jaffex** [Memmy-App/memmy#657]
**Is your feature request related to a problem? Please describe.**
When using the app I wouldn't want any bystanders to snatch my username by shoulder surfing.
Currently, there doesn't seem to be a way to hide the username being displayed very prominently at the very top when browsing the feed.

**Describe the solution you'd like**
I think it would be very cool to have a simple setting in the appearance section that disables displaying the username at the top of the feed.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Felix-Staud** [comment]
@Jaffex although probably not that urgent I took it upon me to implement it

**Comment by eoddc5** [comment]
@Felix-Staud i wouldn’t waste time fixing this. 

We’re working on modifications to location/behaviour/visuals already which will come out in the future
