### ISSUE TITLE
Replace Hex Color Input with React Native Color Picker Library

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#658]
**Describe the solution you'd like**

There is a nice react native color picker here - https://github.com/instea/react-native-color-picker

![](https://github.com/instea/react-native-color-picker/blob/master/doc/preview_iphone.png)

It would be cool to use this for the hex color input and eventually if there is a “custom theme engine” to choose both primary and secondary theme colors. 

**Describe alternatives you've considered**

An alternative would be other color pickers available or keeping manual hex input.

**Comment by ebits21** [comment]
Would be nice. Normal people don't know hex codes.

**Comment by sgriff96** [comment]
It hasn't been updated in 3 years so didn't feel like using it. It's plenty easy to pick a hex code on google and put it in Memmy for now if someone cares enough.
