### ISSUE TITLE
Theme Colors Not Applied in New Post or Pop-Up Menus

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#659]
**Describe the bug**

The proper theme colors are not applied to the 'Cancel' or 'Submit' buttons in the New Post screen.

Edit: is it also possible to add theme colors to pop up menus?

**Screenshots**

This is with the Dracula pink theme.

![image](https://github.com/Memmy-App/memmy/assets/19845100/12790912-da83-4936-a2e1-c37b4301788a)

** not sure if pop ups can be themed, at least the text.

![image](https://github.com/Memmy-App/memmy/assets/19845100/4c08b298-154e-424f-810a-ca6b7d13a732)

**Additional context**
#625 was fixed for the manage/edit accounts screens but not New Post.

0.3.1

**Comment by sgriff96** [comment]
Pop up menus will be resolved with the new context menu change I'm working on.
