### ISSUE TITLE
Memmy don’t ask permission to save image

### ISSUE THREAD

**Issue by fmflurry** [Memmy-App/memmy#664]
**Describe the bug**
Memmy don’t ask for photo permission when trying to save an image with new image viewer when pressing floppy disk icon. The haptic feedback is provided tho as if something happened.

**To Reproduce**
1. Ensure memmy has no photo permission
2. open an image in memmy
3. Try to save by pressing floppy disk icon

**Expected behavior**
Memmy asks for permission otherwise it won’t be able to save the photo.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS16.5.1
 - Version : 0.3

**Comment by gkasdorf** [comment]
Hmm, I'll look. *Are* we able to ask for permission again after the first decline? I'm not sure, will need to check.

If we can't, it should at least tell you though that you need to go enable the permissions.
