### ISSUE TITLE
Community Sidebar Enhancements - Community Stats

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#670]
**Describe the solution you'd like**

As a user browsing a community, I would like the sidebar to be enhanced to add additional community statistics, so that I am able to understand the stats/activity of the community. 

Community Stats Example

![image](https://github.com/Memmy-App/memmy/assets/382845/e6b42086-2946-468b-928e-3a50caa6ea75)

**Comment by eoddc5** [comment]
has some overlap with another you made #547  - but ill dump this into mod epic

**Comment by sgriff96** [comment]
Updated to be just for community stats since beez already made a mod list issue

**Comment by theycallmebeez** [comment]
thanks, I lost track of that one 🤦‍♂️

**Comment by bohn002** [comment]
Got this one. Waiting for the community query PR to merge but should be very similar
