### ISSUE TITLE
Community "Description" header is translating into German

### ISSUE THREAD

**Issue by eoddc5** [Memmy-App/memmy#672]
go into any community, select about, review "Beschreibung" 

![image](https://github.com/Memmy-App/memmy/assets/10222895/9c5fd5e1-4c14-4f1a-a58c-accfca79f2bb)

**Comment by eoddc5** [comment]
what did you do @Felix-Staud  🤣

**Comment by Felix-Staud** [comment]
This part of the Memmy app is now properly of the Bundesrepublik Deutschland /s

**Comment by Felix-Staud** [comment]
@eoddc5 easy fix for anyone not worth a PR

https://github.com/Memmy-App/memmy/blob/b2a7cd01fcf13b7dafb16b00d6caf62e5f01674f/src/plugins/i18n/locales/en.json#L364 It’s basically hardcoded into the en.json file. Happens 🤷‍♂️😁

**Comment by gkasdorf** [comment]
Fixed.

**Comment by Felix-Staud** [comment]
For documentational purposes:
This is also fixed in the /memmy-translations repo
https://github.com/Memmy-App/memmy-translations/commit/15e9c7b6163787a1c211b9bc0e1c4b31a8131144
