### ISSUE TITLE
Instance blocking capability 

### ISSUE THREAD

**Issue by tranquilcarbon** [Memmy-App/memmy#673]
**Is your feature request related to a problem? Please describe.**

I would like to request the ability to add an instance to a blocklist. This is because I like to keep a safe for work feed, turning on the NSFW hide toggle does get rid of a majority of the posts but some still get through because they are not marked as NSFW.

**Describe the solution you'd like**

I would like the ability to block a instance, this could be done by having a section in settings where instances can be typed in.

**Describe alternatives you've considered**

A alternative solution would be to keep a list of NSFW instances and local federation an opt-in for the user. This means any user that wants these instances to appear in their feed can still have it.

**Additional context**

**Comment by Felix-Staud** [comment]
I think this partly exists now with Version 0.5.5:

Filters allow for filtering instances
![image](https://github.com/Memmy-App/memmy/assets/50131232/02064604-9d71-4e6d-9d69-101865d5913b)
