### ISSUE TITLE
Cannot view full image if it if too tall

### ISSUE THREAD

**Issue by PawanHegde** [Memmy-App/memmy#677]
**Describe the bug**
Some part of the image gets cropped

**To Reproduce**
1. Open https://kbin.social/m/lemmyshitpost@lemmy.world/t/198730
2. Open the image
3. Try to see the dialogue at the top of the image

**Expected behavior**
The full image is visible. 

**Screenshots**
https://github.com/Memmy-App/memmy/assets/3167291/46811a4b-fcfd-4dcc-a588-77c51a6aa510

**Smartphone:**
 - Device: iPhone 12
 - OS: iOS 16.5.1
 - Version 15

**Comment by gkasdorf** [comment]
![Screenshot 2023-07-14 at 11 27 25 PM](https://github.com/Memmy-App/memmy/assets/127079571/e13b6db6-26a7-4189-8f20-70eeef891291)

The latest updates have an improved (mostly still a work in progress) image viewer where this shouldn't happen anymore.
