### ISSUE TITLE
[! NSFW IMAGE!] NSFW Toggle has no effect, NSFW content still displays.

### ISSUE THREAD

**Issue by tranquilcarbon** [Memmy-App/memmy#685]
**Describe the bug**

When I log into my sh.itjust.works instance I see NSFW posts despite the fact that hide NSFW is toggled on. I have verified that the problem occurs with both the iPad and iPhone version and have fresh installed the app to verify that the problem is not due to corruption.

**To Reproduce**

1. Install lemmy
2. Log into sh.itjust.works, make sure hide NSFW is enabled.
3. Go to the “all” mode on the top right of the screen
4. Scroll until you see a NSFW post.

**Expected behavior**

NSFW posts should not appear when the hide NSFW toggle is enabled.

**Screenshots**
![IMG_0126](https://github.com/Memmy-App/memmy/assets/97110350/57e1a5c7-5fb8-4507-83c2-ee664fc956f3)

**Smartphone (please complete the following information):**
 - Device: iPad Air 3
 - OS: iOS 16.5.1 (20F75)
 - Version 0.3(1) testflight

**Logs:**
If you wish to submit any debug logs, you may do so by doing the following:
 - Navigate to Settings
 - Tap version number 5 times
 - Press "Send Logs"

This will open an email in your mail app with the logs in the body of the email. 

If you want, you can post them here. However, although there should not be any PII inside of the logs, it may be best to just send them privately. If you do want to post them here, please either find and provide the applicable parts of the logs, or check them for any PII.

**Additional context**

**Comment by gkasdorf** [comment]
Oh, interesting. Let me look at what might have happened there. I think the better options while I'm at it is to just change to using the Lemmy-account-specific toggle for this instead of hiding it manually in-app.

Thanks.

**Comment by gkasdorf** [comment]
So here's a question: Did this happen *with* the hide NSFW setting enabled on the actually Lemmy instance as well? If that's the case then this shouldn't have happened at all.

I'm unable to reproduce getting NSFW to show in my feed with the hide toggled just in-app, although I also have NSFW enabled in the browser PWA. Curious what might have been the cause of this.
