### ISSUE TITLE
Unable to set up local development environment

### ISSUE THREAD

**Issue by grbull** [Memmy-App/memmy#687]
**Describe the bug**

Hi, today I pulled from master, installed all the dependencies and when I try to run the "start" and "web" commands I get the following error:

`Unable to resolve "colord" from "node_modules/@pnthach95/react-native-root-view-background/lib/module/index.js"`

**To Reproduce**

Debian 12
Node 18
Yarn 1.22.19 (maybe this is the issue?)

1. Clone the repository
2. Install the dependencies with either `yarn install` or `yarn install --frozen-lockfile`
3. Run either `npm start` or `npm run web`
4. Get the following error:
`Unable to resolve "colord" from "node_modules/@pnthach95/react-native-root-view-background/lib/module/index.js"`

**Expected behavior**
I would expect to be able to get Memmy running in development mode.

~~**Screenshots**~~

~~**Smartphone (please complete the following information):**~~
 - Device: iPhone [model]

~~**Logs:**~~
If you wish to submit any debug logs, you may do so by doing the following:
 - Navigate to Settings
 - Tap version number 5 times
 - Press "Send Logs"

This will open an email in your mail app with the logs in the body of the email. 

If you want, you can post them here. However, although there should not be any PII inside of the logs, it may be best to just send them privately. If you do want to post them here, please either find and provide the applicable parts of the logs, or check them for any PII.

**Additional context**
I would like to contribute.

**Comment by Felix-Staud** [comment]
I don't know if the exact error is connected to that but running the App outside of MacOS Is pretty much impossible

**Comment by grbull** [comment]
Ah fair enough, I didn't realize MacOS was a requirement! Thanks for the quick response.

**Comment by Felix-Staud** [comment]
> Ah fair enough, I didn't realize MacOS was a requirement for development! Thanks for the quick response.

Yeah we should probably add a requirement into the Readme file
