### ISSUE TITLE
Custom font size setting ignores different font sizes within posts

### ISSUE THREAD

**Issue by Taxxor90** [Memmy-App/memmy#690]
**Is your feature request related to a problem? Please describe.**
Choosing a custom font size also removes different font sizes within posts, headings that are supposed to be 2-3x the size are now just as small as the rest of the text.

Because of this I'd like to keep the system font size but with that the posts in feed view are too big. Despite having set my system font size to the smallest, the font size in compact feed view is way bigger than when I set it to custom and have the slider right in the middle.

Depending on how long the post titles are, I get 4-5 visible posts in compact feed view with the system font size and 6-7 with the custom font size.

**Describe the solution you'd like**
Have the font size option be separated in feed, post and comments so that the compact view could really be compact with the custom font size while also having the actual posts keeping their text format with the system font size.

**Describe alternatives you've considered**
An alternative would be to make the custom font size still respect different font sizes within a post.
For example headings with size 20 and text with size 10 would change to 18/9 when making the font size smaller instead of changing everything to size 9.
But I think it's a good idea in general to have a separate option for the size of post titles anyway.

As there is an "alpha" label next to the font size options I don't know what is already planned for this.

**Comment by chrismarquardt** [comment]
+1

**Comment by sgriff96** [comment]
Can you post some screenshots and steps to reproduce? I haven't noticed this but maybe I haven't been seeing many posts with headings and different font sizes

**Comment by Taxxor90** [comment]
Well the steps to reproduce would be to view any post that has different font sizes in it^^ 
The admin of lemm.ee does this regulary, for example in the sticky welcome post
https://lemm.ee/post/26

Web view
![Screenshot 2023-07-15 214842](https://github.com/Memmy-App/memmy/assets/45570250/44bfc581-62e9-4a70-90af-a58c05d2c303)

Post view and feed view with system font size
![IMG_3147](https://github.com/Memmy-App/memmy/assets/45570250/7271356a-1622-4c73-8508-8b7e14c7c288)
![IMG_3150](https://github.com/Memmy-App/memmy/assets/45570250/cb3612d0-4380-4d1b-98c5-212e3a7aad3d)


Post view and feed view with  custom font size
![IMG_3148](https://github.com/Memmy-App/memmy/assets/45570250/f2b4927c-6fbe-4590-81bb-3fc5f423d39e)
![IMG_3149](https://github.com/Memmy-App/memmy/assets/45570250/08149591-0cd1-4a17-924e-f9fec76ce1b5)

**Comment by sgriff96** [comment]
Typically it's good manners to list out exactly the steps to reproduce, so us devs can easily reproduce the problem right away without having to figure out from context of the description exactly what you have set. But I see the problem, it's just how we calculate markdown font size.

**Comment by Taxxor90** [comment]
Oh and I think I've found the bug with System font size:

1. The title size in feed view is reverse of what you set as system fonz size. I've juzst set it to the biggest size possible and every drop down menu and button got big fonz sizes, but the post titles got very small. That's why I have these big font size in the image above when I use system font size because it's set to the smallest and thus the titles get the biggest font size.  
2. The size inside the actual posts doesn't respond at all to the system font size changes. When I change it and switch back to the app and do a refresh of the post, I can see bigger or smaller font sizes(depending on what I've set) for a small moment and then it's reverting to the same size you see in the screenshot above.

**Comment by Taxxor90** [comment]
Screenshot comparison of largest and smallest system font size (notice how the button text is changing as it should while post titles are reversed)
![IMG_3151](https://github.com/Memmy-App/memmy/assets/45570250/57db823b-5c85-40b5-a306-b6070104517b)

Screen recording of behaviour when changing system font size
https://drive.google.com/file/d/1tE4T7NX-oByBg3bK8LQOzjJywnEq_Tfa/view?usp=sharing

**Comment by gkasdorf** [comment]
Font sizes are now standardized and should be consistent throughout the app.
