### ISSUE TITLE
Opening app does not take you back to where you left off in the post feed

### ISSUE THREAD

**Issue by ericschmar** [Memmy-App/memmy#691]
**Describe the bug**
After using the app, navigating off the app (not force closing), then at a later time, opening the app back off does not take you back to where you were in the post feed. 

**To Reproduce**
1. Use Memmy
2. Go to your Home Screen (don't force kill the app)
3. Wait 30m
4. Open Memmy 

**Expected behavior**
I expect the post feed to be where I left off. 

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.5.1
 - Version 0.3 (1)

**Comment by eoddc5** [comment]
Not really a bug or issue? I think that’s just the app behavior sorting cache out

**Comment by ericschmar** [comment]
It should be an issue because other apps are able to stay open in the background and when returning to the foreground, you are back where you left off.
