### ISSUE TITLE
Opening Multiple of Same Post

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#692]
**Describe the bug**

Multiple post views can be opened from the post feed. 

**To Reproduce**
1. Go to Post Feed
2. Spam Click on the post. 
3. Multiple of the same post open, user must click back to close each instance to return to the feed view. 

**Screenshots**

**Comment by theycallmebeez** [comment]
https://github.com/Memmy-App/memmy/assets/382845/d370e12e-dfaa-4ff2-b630-645749dc63cd

**Comment by eoddc5** [comment]
@gkasdorf looks like you can make the post open twice if you click like that. 

Wonder what’s allowing the second launch

**Comment by theycallmebeez** [comment]
@eoddc5 I added a screen recording (above). Most I’ve been able to spam open is 3.

**Comment by gkasdorf** [comment]
Shouldn't be a big issue now since the render times are signiciantly less.
