### ISSUE TITLE
Tap on blurred NSFW image opens post instead of image

### ISSUE THREAD

**Issue by SivarCalto** [Memmy-App/memmy#695]
If blur NSFW content is active, tapping on a blurred image from the home view opens the post instead of the unblurred image, and I have to tap again on the blurred image to finally see it.

If the blur option is off, tapping the image from home opens the image as it should, and not the post.

**Comment by eoddc5** [comment]
Can you post a video of this? if possible to find something nsfw but not nudity? Maybe “gonemild” would be an easy find. 

This is not how it works for me.

**Comment by SivarCalto** [comment]
Hope this works.

**Comment by gkasdorf** [comment]
Oh Compact view huh? Might know why that's happening, will work on it now.

**Comment by eoddc5** [comment]
that makes sense - its fine on normal mode, checked compact and can reproduce this

**Comment by gkasdorf** [comment]
Fixed now. Will close out when merged.
