### ISSUE TITLE
Keyword filtering

### ISSUE THREAD

**Issue by alex171** [Memmy-App/memmy#704]
**Is your feature request related to a problem? Please describe.**
In my feed there are posts I don’t want to see, like stuff about Elon Musk and SpaceX

**Describe the solution you'd like**
I want the possibility to filter certain Keywords or phrases. Somewhere in the settings, under content, an option to add keywords to a list. Posts containing a keyword from the list stay hidden in the feed.

**Describe alternatives you've considered**

**Additional context**
Keyword Filtering was a great feature in Apollo

**Comment by sgriff96** [comment]
Not possible with the current lemmy API afaik. We'd have to do it on Memmy's side which would be expensive and not worth it atm. If they add it to the lemmy API we'd definitely be open to adding this though.

**Comment by lavalleeale** [comment]
Hey, would giving users the choice not be a good idea? I see there is already nsfw filtering ( https://github.com/Memmy-App/memmy/blob/dd638bf5a0d69cc4fff3f6d342c1856de58bde0c/src/helpers/LemmyHelpers.ts#L25 ) which could be adapted for filters as well? The performance would be bad if the user filters out popular keyword but there could be a warning inside the app. As the developer of Lemmios we have this feature and used sparingly the performance impact is negligible

**Comment by gkasdorf** [comment]
@lavalleeale I've gone ahead and rewritten this to handle it. Thanks!
