### ISSUE TITLE
Put a "share post" button near the bookmark button

### ISSUE THREAD

**Issue by Max17U** [Memmy-App/memmy#705]
**Is your feature request related to a problem? Please describe.**
Whenever i want to share the link to a post, i always have to first open the post itself by tapping the title of the post and then tap on the share button. Tapping directly on the image and then on the sharing button will share only the image itself, not the link to the post.

**Describe the solution you'd like**
I think putting a "share post" button near the bookmark button would be the best solution. That button would let me share the link to the post, not the image (if there is) of the post.

**Describe alternatives you've considered**
That's it. Thanks :)

**Additional context**
Picture with example (and cat bonus!)

![photo_2023-07-16_11-28-01](https://github.com/Memmy-App/memmy/assets/74881393/dca4d203-dd0b-4e63-a5e0-08f6860362ce)

**Comment by gkasdorf** [comment]
![Screenshot 2023-07-16 at 2 40 39 AM](https://github.com/Memmy-App/memmy/assets/127079571/ee1b4136-771a-4225-aa3a-17c7a49618a0)

Today we converted over to these, so we will put something like this in the post as well for sharing, blocking the user, or blocking the community 👍

**Comment by Max17U** [comment]
> 

So if I understood correctly, in the feed page (while scrolling all the posts) there will be a button in each post that opens a "menu" like that, and it will contain also a "share post" button?

**Comment by gkasdorf** [comment]
Well, I suppose it might be easier to put it just with the other buttons. We will need to see how to make it look nice though without getting too cluttered.

**Comment by Max17U** [comment]
Yeah definitely :) I'll wait and see ! By the way thanks for your work!

**Comment by sgriff96** [comment]
Can do this now by long pressing or tapping the ... button on a feed item
![image](https://github.com/Memmy-App/memmy/assets/46509416/48f1fc4f-67e0-4d77-b105-780227033823)
