### ISSUE TITLE
Add a gesture to collapse

### ISSUE THREAD

**Issue by tpkee** [Memmy-App/memmy#707]
**Is your feature request related to a problem? Please describe.**
If collapse on tap is disabled, to collapse you have to go in the comment's options 

**Describe the solution you'd like**
Add a gesture to collapse. Something where if you swipe a lot on the right, you collapse otherwise you comment

**Describe alternatives you've considered**

**Additional context**

**Comment by eoddc5** [comment]
This seems like it is just more effort to do than tap the comment. 

What’s the use case for this?

**Comment by tpkee** [comment]
> This seems like it is just more effort to do than tap the comment.
> 
> What’s the use case for this?

When I scroll I often mis-tap comments and they collapse, more so for me it's hard to click on links and I collapse by mistake a lot

**Comment by sgriff96** [comment]
We more need to tweak the hit slop area of the clickable things inside a comment tbh. I agree it's too easy to collapse right now, but with some fine tuning I think it would be a non issue.

**Comment by tpkee** [comment]
> We more need to tweak the hit slop area of the clickable things inside a comment tbh. I agree it's too easy to collapse right now, but with some fine tuning I think it would be a non issue.

oh yeah, it would definitely help! Like, setting a z-index higher for the clickable elements would _probably_ alleviate the problem
