### ISSUE TITLE
Minor Traverse Tweaks: Favorite and Subscriptions Counts and Padding.

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#708]
**Describe the solution you'd like**
Beside the Favorites and Subscriptions titles I would like a count of number of favorites and subscriptions.

I would also like the padding between Subscriptions and the post above to match the padding between the search box and favorite title. Looks cramped.

**Additional context**
![image](https://github.com/Memmy-App/memmy/assets/19845100/a11aaac1-d866-4065-8b76-055de9bdfe4f)

Mock-up done on my phone, sorry.

**Comment by eoddc5** [comment]
Both good ideas

**Comment by joshua-davis-rose** [comment]
I have a couple other traverse list items to handle so I can pick this one up at the same time.

**Comment by ebits21** [comment]
Seems good!
