### ISSUE TITLE
Hide read posts only in feed

### ISSUE THREAD

**Issue by pitrisss** [Memmy-App/memmy#710]
**Is your feature request related to a problem? Please describe.**
I would like a feature, where we could toggle if we want to hide read posts only on feed, or everywhere, similarly as apollo had it. This means that whenever we open specific community only, we could see the read posts, but on feed it would be hidden.

**Describe the solution you'd like**
A switch in settings which would toggle this option.

**Comment by eoddc5** [comment]
@gkasdorf is this something we can do?

**Comment by ktgd** [comment]
This shouldn't be too hard and was something I've been meaning to add. I'll work on it here in a bit.
