### ISSUE TITLE
Support pict-rs

### ISSUE THREAD

**Issue by bviefhues** [Memmy-App/memmy#729]
**Describe the solution you'd like**
App should support Lemmy's own pict-rs image store backend. Upload should transparently adapt images to the instance max filesize for images. 

Offer an UI for selecting between imgur and pict-rs for new image posts.

**Comment by gkasdorf** [comment]
Yea we've been discussing this and it will happen once I get the time.

**Comment by gkasdorf** [comment]
Pictrs is now supported.
