### ISSUE TITLE
Tab bar text too long in German

### ISSUE THREAD

**Issue by bviefhues** [Memmy-App/memmy#731]
**Describe the bug**
Tab bar texts are too long in German, Screenshot:

![image](https://github.com/Memmy-App/memmy/assets/1117300/c60decb2-b0bb-4472-b95c-cdd0c44c92b8)

iPhone 11 Pro

Suggest removing the icon texts, except for the username.

**Comment by eoddc5** [comment]
I dont think we will be removing the text, but can look at how to fix this issue

**Comment by Semmelstulle** [comment]
Same here. It's not recommend removal of tab titles though. I'd just translate it "Optionen" instead of "Einstellungen" - should be short enough

**Comment by bviefhues** [comment]
Maybe also "Posteingang" to "Eingang"

**Comment by eoddc5** [comment]
theres also a run on in "posteingang" > "username" , looks like theyre going to collide, and if the username was even longer, what would happen?

**Comment by bviefhues** [comment]
@eoddc5 Yes, "Feed" is fine. The word is localized. German Wikipedia has an [article](https://de.m.wikipedia.org/wiki/Feed).

**Comment by gkasdorf** [comment]
I implemented those changes. If you have other things that should be edited, feel free to let me know or you can also make changes if you want to. You should be able to just go to the actual file in question on GitHub (at this link https://github.com/Memmy-App/memmy/blob/main/src/plugins/i18n/locales/de.json) and just hit the edit button. Submit a PR with the changes.

Up to you, thanks!
