### ISSUE TITLE
Filtering Traverse should remove unused alpha-indexes

### ISSUE THREAD

**Issue by joshua-davis-rose** [Memmy-App/memmy#736]
**Is your feature request related to a problem? Please describe.**
With the addition of the alpha indexing on Traverse and then filtering, any unused alpha indexes show as empty, which run into each other. If the filter returns no communities the list just shows the indexes and no message saying the results are empty. 

**Describe the solution you'd like**
Filtering Traverse should remove any unused alpha indexes. If there are no returned communities the "no communities" message should be displayed.

**Additional context**
![IMG_D01B4AACA46E-1](https://github.com/Memmy-App/memmy/assets/3818037/9cfdfbb1-ba9d-43b2-b7de-f066004ec53e)

**Comment by joshua-davis-rose** [comment]
This is cleaning up something I left behind. Once triaged I'll take this ticket.

**Comment by eoddc5** [comment]
You can always just start working before I get to prioritizing @joshua-davis-rose your

**Comment by joshua-davis-rose** [comment]
Don't worry, I did @eoddc5

**Comment by theycallmebeez** [comment]
this can be closed out, working as intended in v 0.5 (5) 🤘
