### ISSUE TITLE
Profile Doesn't Load after adding new account

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#741]
**Describe the bug**

Profile page doesn’t open after adding new account until force close the app and re-open. 

**To Reproduce**
1. Go to Add Account/Profile.  
2. Click on Profile
3. No account profile loads until force close and reload app. 

![](https://media.discordapp.net/attachments/1118520596909797429/1130628039210967130/image0.jpg)

**Comment by gkasdorf** [comment]
I wasn't able to reproduce this. Did the feed load correctly after switching accounts? What instance is this?
