### ISSUE TITLE
Subscriber Count is Decimal on Search Page

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#743]
**Describe the bug**

Search for community. Subscriber count is decimal. 

![image](https://github.com/Memmy-App/memmy/assets/382845/e7fd39ed-b1d0-4957-a0b1-b0522d9b8359)

**Comment by theycallmebeez** [comment]
Also possible to format/parse the community title like this so the community name is more prominent and the instance is listed below and less emphasized?

![image](https://github.com/Memmy-App/memmy/assets/382845/c3def2b4-8c0d-42dc-ad17-3cd80975a195)

**Comment by gkasdorf** [comment]
This was fixed already here: https://github.com/Memmy-App/memmy/issues/734

Could you open a new issue for the other recommendations? Thanks!
