### ISSUE TITLE
[Minor Visual] Option to Hide Username in Bottom Bar

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#744]
**Describe the solution you'd like**

Add a visual option to hide username in bottom nav bar and just show a”Profile” or “Account” text label. 

**Describe alternatives you've considered**

Option to show instance name instead of username.

**Comment by eoddc5** [comment]
closing this as wontfix. profile names are here to stay, esp with the way the switcher works now

**Comment by theycallmebeez** [comment]
can this at least be discussed? some people don’t want it to show for privacy reasons and others don’t like how it looks. has nothing to do with being able to switch accounts.
