### ISSUE TITLE
Usernames under profile icon cut off

### ISSUE THREAD

**Issue by eoddc5** [Memmy-App/memmy#748]
Suggestion is to lower font size before truncating

For certain lengths, keep font size as is

When length of name truncates with … , suggestion to lower font size to fit the username in the space

At a certain length, username will need to truncate, even with decrease font size.

**Comment by eoddc5** [comment]
it probably will not change to anything other than the profile name, but the profile name will be optimized to appear better in this area

**Comment by QuarterSwede** [comment]
> The bottom navigation bar also is kinda wonky looking with longer usernames. It abbreviates them with a . I'd like an option like Apollo had, to just say "Account" there.

This is the apparent answer. I even looked for a setting that would hide username in bottom bar. Just because mine is long.
