### ISSUE TITLE
“Quick Jump” Scroll Bar in Traverse Drawer

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#749]
**Describe the solution you'd like**

As a user who wants to navigate/scroll quickly through the Traverse/Community drawer, I would like a “Quick Jump” scroll area along the right side of the drawer to jump between Favorites and each Alpha heading. 

![image](https://github.com/Memmy-App/memmy/assets/382845/72faa451-9856-4986-9a82-7763bd868ba5)

**Comment by eoddc5** [comment]
some tweaks are going to be made on the traverse drawer

we can look into how to best implement an alphabetized list like that...problem with how it is now is that it would be easy to click out of the drawer if youre trying to scroll where the mock up is located.

@gkasdorf @sgriff96 thoughts?

**Comment by theycallmebeez** [comment]
@gkasdorf @sgriff96 - 

`npm install react-native-section-alphabet-list`

**Comment by sgriff96** [comment]
2yo package not maintained anymore

**Comment by sgriff96** [comment]
Honestly doubt we'd implement this any time soon
