### ISSUE TITLE
Traverse drawer when swiping back

### ISSUE THREAD

**Issue by bviefhues** [Memmy-App/memmy#752]
**Describe the solution you'd like**
When tapping a community from the traverse drawer, that community opens. However when swiping back, one ends on the feed, not on the pulled out traverse drawer. 

I suggest going back to the pulled out traverse drawer in that case since that is consistent with expectation.

**Comment by eoddc5** [comment]
This is the expected outcome

The traverse drawer lives to the left of the feed

Swiping right from anywhere a community or post will bring you back to the feed. Swiping right from the feed will bring you to community traverse menu.
