### ISSUE TITLE
Incorrect Community Subscriber Count

### ISSUE THREAD

**Issue by sc0ttwood** [Memmy-App/memmy#756]
As I was on c/weirdwheels I realised that I had 4,000 subscribers, I thought that was odd as I only had 1,000 a couple of days ago so I looked into it.

Turns out the subscriber count is broken. Below you will see the count has a 3,000 difference.

App:
![image](https://github.com/Memmy-App/memmy/assets/138073160/540d4e87-f40a-4b2c-8fd8-5a71962c99a0)

Web:
![image](https://github.com/Memmy-App/memmy/assets/138073160/99ed7eb2-ee1c-4505-b0ee-2c81c739c03b)

**Comment by ebits21** [comment]
Always 3k for me and others in community search.

![image](https://github.com/Memmy-App/memmy/assets/19845100/57e3fde0-c5c0-40bb-97ec-226171c7ef06)

**Comment by theycallmebeez** [comment]
Can confirm.

**Comment by bobcarroll** [comment]
#750 fixes this
