### ISSUE TITLE
Too Large Vote Buttons in Comments

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#757]
**Describe the bug**
Since the last update the vote buttons are very large in comments, but not feed view.

**Expected behavior**
Same size as feed view

**Screenshots**

![image](https://github.com/Memmy-App/memmy/assets/19845100/01ec7484-bfe5-4921-a821-47e81bf0ad90)

**Additional context**
4.2

**Comment by sgriff96** [comment]
lol oops. I am working on this now in #665
