### ISSUE TITLE
Integrate lemmy-search as an alternative option for searching. 

### ISSUE THREAD

**Issue by marsara9** [Memmy-App/memmy#758]
The built-in search for Lemmy is rather slow, compute intensive and requires exact matches to find content.

As an alternative I've built lemmy-search (https://www.github.com/marsara9/lemmy-search) / https://www.search-lemmy.com that takes the load off the existing servers, supports complex queries and filters, and is relatively fast.

I've also had a handful of users reaching out if it can be added to the third party apps...

But API documentation can be found on the site itself.

Ideally a toggle would exist on the current search page to toggle between the existing built-in implementation and this alternative API. 

Features for the alternative search option would include (all free via the API):
* Filtering results by Instance, Community or Author. 
* Searching within a target date range
* A toggle to include for NSFW or not

The exact contract can be found here: 
* https://www.search-lemmy.com/help/api/search/posts
* https://www.search-lemmy.com/help/api/search/communities

There's two main APIs:
* `/api/search/posts?query=<query string>&home_instance=<user's logged in stance>&page=<page #>`
Which will return a set of posts that match the query string.  The posts will already be sorted based on their page rank and contain enough data to show a preview and reconstruct a URL to that post on the user's home-instance.
and:
* `/api/search/communities?query=<query string>&home_instance=<user's logged in stance>&page=<page #>`
Which will return a set of communities that contain posts matching the search query.  The communities will be ranked by the number of matches. (As if the user searched for posts but grouped them all by the community they belong to and then sorted them).  There will again be enough data in the result to reconstruct a URL to take the user to that community's landing page on their home instance.

**Comment by marsara9** [comment]
Oh heads up. Forgot I hadn't pushed this update yet. But currently there are two search APIs, one for searching posts and another for communities.  I plan on combining these two in an update tonight. After such there will be a new `mode` query parameter to switch between posts and communities.  But otherwise everything I mentioned above is accurate. I'll also have the API documentation updated as well.

**Comment by slrgt** [comment]
it would be great if Memmy automatically searched for posts while typing in the title of a new post so users could see a dropdown menu of similar posts to prevent duplicate posts from being made when one already exists.

**Comment by gkasdorf** [comment]
This is awesome. I'll look at this more closely later today. Thank you!

**Comment by marsara9** [comment]
Not sure if any development has started on this, but I wanted to give a heads up that I'll be introducing a breaking API change in the near future as I begin allowing searches to span the entire lemmy-verse. (and adding comment data to the index)

Long story short the search API will return the `actor_id` of the post but you'll need to call `<home-instance>/api/v3/resolve_object?a=<actor_id>` to get the post that the user searched for (after they tap on it), or at least to get the internal id. As I'll no longer be returning the `remote_post_id` in the search results.  All other data will still be there however.

**Comment by eoddc5** [comment]
@sgriff96 @gkasdorf check out latest by @marsara9
