### ISSUE TITLE
Add configurable post age filter

### ISSUE THREAD

**Issue by Xabis** [Memmy-App/memmy#761]
The Lemmy algorithm has been surfacing years-old content in "hot", which is causing annoyance and confusion.

A way of blocking these client side would be a boon, until when/if a fix is ever made server side.

Even without this specific ongoing issue, being able to reduce the "active" list down to the past half day would help, as "top x" is not always ideal, and posts can live several days in active.

**Comment by eoddc5** [comment]
This is not going to be something that’s fixed. Will need to wait for Lemmy to adjust their algorithms
