### ISSUE TITLE
12ft.io (and maybe other) links get messed up

### ISSUE THREAD

**Issue by alex171** [Memmy-App/memmy#768]
**Describe the bug**
Links to 12ft.io are improperly displayed/ cut off. 
here is an example of such a link:
 https://12ft.io/https://www.heise.de/news/Videostreaming-Wow-fuehrt-Basis-Abo-mit-Werbung-ein-9220938.html

Memmy displays it like this:

`
[Link ohne Datenklaumauer](https://12ft.io/https://www.heise.de/news/Videostreaming-Wow-fuehrt-Basis-Abo-mit-Werbung-ein-9220938.html)
`

I have added screenshots of the example. Expected behavior vs. behavior in memmy

the problem seems to be the second https: in the link.

**To Reproduce**
See description and screenshot

**Expected behavior**
Link should not cut off

**Screenshots**
![IMG_6419](https://github.com/Memmy-App/memmy/assets/28484494/7081c9bb-484a-4fbc-b738-c20a30976532)
![IMG_6418](https://github.com/Memmy-App/memmy/assets/28484494/bef5e445-eeed-4472-bac9-a7a023971971)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 pro 
 - OS: 16.5.1(c)
 - Version 20F75

**Comment by gkasdorf** [comment]
Link markdown issues are good to go now.
