### ISSUE TITLE
Remove View Saved Posts from user profiles

### ISSUE THREAD

**Issue by hungryca-t** [Memmy-App/memmy#771]
**Is your feature request related to a problem? Please describe.**
There doesn’t seem to be a clear purpose for the View Saved Posts option on **other** user profiles. It’s always blank. You can only view your own saved posts. 

**Describe the solution you'd like**
Remove the View Saved Posts button under user profiles other than your own. 

**Describe alternatives you've considered**
Just not clicking the button, since it serves so apparent purpose. 

**Additional context**
I’m honestly not sure if this is intended to be a future feature—being able to view others’ saved posts. I personally would prefer others not to be able to view my own saved posts.

**Comment by sgriff96** [comment]
Lol oops yea good idea
