### ISSUE TITLE
Email Debug Log Not Functional

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#776]
**Describe the bug**
Nothing happens if you click "Email Debug Log" in settings.

**Expected behavior**
Email dialog popup.

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/19845100/2e3730be-3b61-44e1-a275-93da85b8e1ed)

**Additional context**
I've noticed this for awhile and just saw another user report it. I have seen the email dialog pop up with an actual error message before.

**Comment by eoddc5** [comment]
It works for me. 

https://github.com/Memmy-App/memmy/assets/10222895/c40c1f69-50a5-4ebe-8d7e-8438b4357ee3

**Comment by ebits21** [comment]
Hmm

https://github.com/Memmy-App/memmy/assets/19845100/f593faf0-e1be-4565-b8ab-8a55ba9f48b1

My problem now is I just accidentally cleared the log so now I want to just after a bug warning.

I need a bug.

**Comment by ebits21** [comment]
Ok so here's what it is.

I use the gmail app and not the native mail app. I imagine I'm not alone. 

When I added my account to the native mail app it works now.

Is there any way to check for this and display an error message or something?

**Comment by eoddc5** [comment]
Oh weird. Must be a way to allow non mail app.

**Comment by gkasdorf** [comment]
I think we can do this but I'm not sure how attachments would work. For example, you can use `Linking.openURL("mailto://") to do this, but I'll need to see if we can include an attachment there. Definitely agree that there's probably a lot of people who don't use Apple Mail.

**Comment by gkasdorf** [comment]
Needed some additional configuration, but this might have been the fix. After the next update can you please @ me in this and let me know? With the extra configuration it *might* send you to a different mail client but I'm not sure. Thanks.

@ebits21

**Comment by ebits21** [comment]
@gkasdorf Unfortunately, still having the same issue with the last update.

Still need to be logged into the native app.
