### ISSUE TITLE
Hide NSFW button not working

### ISSUE THREAD

**Issue by hugpeter** [Memmy-App/memmy#777]
Hide NSFW button does not hide the content from feeds. 

**To Reproduce**

Toggle on button,
Go back to feed with sort type of new or top hour and refresh.
Scroll down through feed and eventually a NSFW post shows up. 
**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: ios 16.5
 - Version latest in test flight

**Comment by eoddc5** [comment]
I think there’s something to do with how communities and posts mark nsfw. The hide toggle generally toggles most, but not all 

Is this something fixable by memmy or is it a lemmy issue? @gkasdorf

**Comment by hugpeter** [comment]
For more info, if i toggle off nsfw from the Lemmy instance itself that seems to work, so whatever memmy is doing, it must not being doing the exact same logic that the lemmy code is doing.

**Comment by gkasdorf** [comment]
Working now.
