### ISSUE TITLE
Provide Indicator for Bot Accounts

### ISSUE THREAD

**Issue by ctsallen** [Memmy-App/memmy#778]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a bug. Merely an enhancement request.

**Describe the solution you'd like**
Some form of icon/indicator for Bot accounts. Lemmy instances frequently have accounts that are bots; such as the incredibly useful https://lemmy.world/u/L4s.  Bots in and of themselves are fine, but on other Lemmy apps (mlem uses a server icon) and on the standard website (denoted with a B next to the name), there is iconography to denote that the user is a bot account.

**Describe alternatives you've considered**
There is no alternative. Even clicking into the user on Memmy, the description text, which sometimes explains the bots purpose, is not presented. 

**Additional context**
An example screenshot from the mlem app:
![Screenshot 2023-07-20 at 12 09 49 PM](https://github.com/Memmy-App/memmy/assets/87030885/5b51de4a-b163-4c0e-9347-5e6d7767a26b)

**Comment by sgriff96** [comment]
How interesting, wonder if the lemmy api provides this info.

**Comment by ctsallen** [comment]
I've run across it while building my Go-based Lemmy instance tool and it looks like it's derived from: https://github.com/LemmyNet/lemmy/blob/main/crates/db_schema/src/source/person.rs - the 'bot_account' bool.

**Comment by sgriff96** [comment]
@ctsallen thanks will add it then if its that easy

**Comment by sgriff96** [comment]
Done
