### ISSUE TITLE
Missing translation placeholders

### ISSUE THREAD

**Issue by br337** [Memmy-App/memmy#779]
**Describe the bug**
There are multiple translation placeholders missing around the app. These are the ones that I found that are missing. Along these ones, I have also found one which uses the singular form of "Comments" instead of the plural form when multiple comments are present under a post.

**Screenshots**
![Simulator Screenshot - iPhone 14 - 2023-07-20 at 20 48 48](https://github.com/Memmy-App/memmy/assets/49288125/7dddcda8-4b43-46bf-ba23-dfb06320ea6d)
![Simulator Screenshot - iPhone 14 - 2023-07-20 at 20 48 55](https://github.com/Memmy-App/memmy/assets/49288125/c5f728e4-1dca-4bab-8989-a7b9efe5df82)
![Simulator Screenshot - iPhone 14 - 2023-07-20 at 20 49 01](https://github.com/Memmy-App/memmy/assets/49288125/b57f0788-7eb2-4b5d-9cce-ec040fa05a6e)
![Simulator Screenshot - iPhone 14 - 2023-07-20 at 20 49 10](https://github.com/Memmy-App/memmy/assets/49288125/181372f8-cadb-4208-b80b-d038f0e0b8c6)
![Simulator Screenshot - iPhone 14 - 2023-07-20 at 20 49 27](https://github.com/Memmy-App/memmy/assets/49288125/f26af34e-c165-41de-920a-d09d96074222)
![Simulator Screenshot - iPhone 14 - 2023-07-20 at 20 49 47](https://github.com/Memmy-App/memmy/assets/49288125/170235cf-6066-4d0c-86a5-c0c306bfc057)
![Simulator Screenshot - iPhone 14 - 2023-07-20 at 20 52 44](https://github.com/Memmy-App/memmy/assets/49288125/d60cd985-ed8c-4ad4-9cf9-4258acbdf443)
![Simulator Screenshot - iPhone 14 - 2023-07-20 at 20 51 51](https://github.com/Memmy-App/memmy/assets/49288125/327b8b41-74ea-449c-a2fd-f0cbb55a8426)
![Simulator Screenshot - iPhone 14 - 2023-07-20 at 20 50 56](https://github.com/Memmy-App/memmy/assets/49288125/90a21e48-386e-4294-af01-f74a90797103)
![Simulator Screenshot - iPhone 14 - 2023-07-20 at 20 50 02](https://github.com/Memmy-App/memmy/assets/49288125/f36a9ab7-1010-4124-bbfc-3359e79538a8)

And here is the wrong use of "Comments". Here the header is using comments in the singular form, whereas it should be in the plural form, as there are 3 comments:
![Simulator Screenshot - iPhone 14 - 2023-07-20 at 20 51 42](https://github.com/Memmy-App/memmy/assets/49288125/a4ae67cb-5b60-429d-8451-5f4ba5fc2e1e)

**Comment by Felix-Staud** [comment]
All those missing drop-down menu (context menu) translations should be fixed with https://github.com/Memmy-App/memmy/pull/836

**Comment by Felix-Staud** [comment]
@eoddc5 it wouldn't close the issue but some of them will be fixed. Some is still have to look into

**Comment by Felix-Staud** [comment]
@br337 ai I went through all those screenshots and added the missing ones (A lot were already covered by the context-menu-redo.)
The only thing I didn't translate, on purpose, is the app-icon names. I feel like those are "custom names" and you can see the app-icon right next to it anyway.
