### ISSUE TITLE
Link thumbnail should bring up browser

### ISSUE THREAD

**Issue by enghseb** [Memmy-App/memmy#785]
When you're in compact mode and click an image, the image viewer is brought up. Likewise, when a linked is clicked, the browser should open. 

Right now if you clink a thumbnail that's a link, you go into the comments and have to press the post again.

**Comment by eoddc5** [comment]
@gkasdorf unsure if this is an enhancement or by design 

I’ll let you figure out what the best way to handle this particular issue is.

**Comment by sgriff96** [comment]
Yea this should open the link if you click the link icon.

**Comment by gkasdorf** [comment]
I'll handle this real quick.
