### ISSUE TITLE
Can't Visit Old Comment Chain From Profile in 5.3

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#786]
**Describe the bug**
If tapping on comments from profile nothing happens in 5.3.

Expected that the post and comment chain will open after.

**Screenshots**
https://github.com/Memmy-App/memmy/assets/19845100/a0a56ddc-3cd0-44b3-92e7-5e9008111e17

**Comment by eoddc5** [comment]
Confirmed

**Comment by ebits21** [comment]
Ny behaviour has changed now that I have unread comments in my inbox. 

Now clicking a comment in inbox loads the post with all comments loaded, not just the expected comment chain.

https://github.com/Memmy-App/memmy/assets/19845100/c2739679-5ba2-427f-aab0-c2eebd6303fe

Weird.

**Comment by gkasdorf** [comment]
Fixing this here in a few.
