### ISSUE TITLE
No Voting Buttons or Swipe in Inbox Comments or Comments Accessed From Profile.

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#787]
**Describe the bug**
Comments in the users profile or Inbox do not have upvote/downvote buttons or upvote/downvote swipe ability.

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/19845100/d54c599b-3ca5-42f6-b8b1-2ff021bd0695)

![image](https://github.com/Memmy-App/memmy/assets/19845100/a4d9e3f1-6f92-4188-b4a8-10d91dd8cd05)

**Additional context**
5.3

**Comment by eoddc5** [comment]
Confirmed

**Comment by eoddc5** [comment]
Known issue and will be fixed

**Comment by gkasdorf** [comment]
Fixed now.
