### ISSUE TITLE
Cannot Read Property 'comments' of Undefined.

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#789]
**Describe the bug**
If a comment is deleted, get Undefined error when refreshing comment feed.

**To Reproduce**
1. Delete comment
2. Refresh
3. See error

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/19845100/c647fe91-072b-4e81-a255-0995cd39e7f0)

https://github.com/Memmy-App/memmy/assets/19845100/a34327e3-1e61-4cab-87df-e20029d923d7

**Additional context**
5.3

**Comment by eoddc5** [comment]
I’m getting the same error randomly as well

This has shown up before with some wonkiness with the api I think

**Comment by gkasdorf** [comment]
Noted. Thanks.

**Comment by gkasdorf** [comment]
All of these state issues are fixed.
