### ISSUE TITLE
Compact View: Font scales opposite to system Text Size setting

### ISSUE THREAD

**Issue by fouram** [Memmy-App/memmy#790]
**Describe the bug**
Changing the text size on my device to a larger size makes the compact view text size shrink, and if I set Text Size smaller, it will enlarge text size on Compact View. Effectively doing the exact opposite of what I want.

**To Reproduce**
1. Go to Settings->Display&Brightness->Text Size
2. Increase text size
3. Open Lemmy and use Compact view
4. Text is smol

**Expected behavior**
Text scales with system Text Size as expected

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/533951/f678f4ae-3599-4fde-97cd-b5c18c29f4f5)![image](https://github.com/Memmy-App/memmy/assets/533951/8ced3a0a-44ff-4571-a7c8-008ce97f9728)
![image](https://github.com/Memmy-App/memmy/assets/533951/70417ecd-ade2-44bb-a7c6-b05c083d4314)![image](https://github.com/Memmy-App/memmy/assets/533951/2568a4a9-24e5-45ce-88aa-f164f08cdc86)
![image](https://github.com/Memmy-App/memmy/assets/533951/a9a37920-73d1-4bc7-9a38-d8b50f3d6cf4)![image](https://github.com/Memmy-App/memmy/assets/533951/e6fd5565-97ec-4ddd-b50b-0a8edaa78877)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.5.1 (c)
 - Version 0.5 (3)

**Logs:**
Please let me know if they'd be useful in this case.

**Additional context**

**Comment by eoddc5** [comment]
Have you interacted with the app slider for font scaling to see what might be causing a conflict? Just curious. 

@fouram

**Comment by Taxxor90** [comment]
I've mentioned the same issue here 
https://github.com/Memmy-App/memmy/issues/690#issuecomment-1636875091

If you're using the app slider, every text scales according to what you set.

If you're using the system font size, text inside of posts(post itself as well as comments) don't respont to system font size changes, they'll stay the default font size.
User names, instance names etc in feed view also doesn't respond to changes in system font size and the titles respond the opposite way.

**Comment by sgriff96** [comment]
Hmm, annoyingly seems like Large post size seems to also not respect system font size either.

**Comment by fouram** [comment]
I attempted to use the in-built font size slider and it works, so there is a workaround currently.

![image](https://github.com/Memmy-App/memmy/assets/533951/822d791d-14c2-4538-b797-24bcbb177bbf)

**Comment by gkasdorf** [comment]
Font sizes are good now.

**Comment by fouram** [comment]
Thank you!
