### ISSUE TITLE
Can't load Profile nor Search Tab.

### ISSUE THREAD

**Issue by sc0ttwood** [Memmy-App/memmy#792]
I checked my profile when I realised that I couldn't load my profile as it gave a extremely long loading time, so I restarted the app. This unfortunately gave me an error (see below).

The search tab is a different story, it only loaded once despite restarting the app constantly as it always gave me an infinite load screen.

Profile Error:
![image](https://github.com/Memmy-App/memmy/assets/138073160/cd8e4641-78c0-45e4-b7ae-31708e132ae0)

Search Tab Loading:
![image](https://github.com/Memmy-App/memmy/assets/138073160/4a8446dd-11e9-4845-b414-c1e702329ac6)

**Comment by eoddc5** [comment]
What app version are you on

I’m having no problem with either of the actions in this post

**Comment by ebits21** [comment]
Hmm similar error to #789

**Comment by eoddc5** [comment]
@gkasdorf or @sgriff96 can you confirm your search and profile are fine? If so we can close this

**Comment by sgriff96** [comment]
I'm having no problem on lemm.ee, lemmy.world, or lemmy.ml. Closing.
