### ISSUE TITLE
Graphical issues after landscape to portrait

### ISSUE THREAD

**Issue by LazaroFilm** [Memmy-App/memmy#794]
**Describe the bug**
Major graphics issues after coming back from landscape mode on iOS. 

**To Reproduce**
Go to landscape then back to portrait in a comment section. 
**Expected behavior**
Expected to not be all messed up
**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/18351100/4a3c9f2a-8690-47c3-ac73-1072951d94f5)
**Smartphone (please complete the following information):**

iPhone 14 Pro
16.5.1

**Comment by eoddc5** [comment]
I’m pretty sure landscape is not even supposed to be on / not supported 

Probably will be turned off in future builds

**Comment by LazaroFilm** [comment]
If landscape is t supported, explain this: 

![image](https://github.com/Memmy-App/memmy/assets/18351100/0d05ee1f-fe40-4209-a0f1-96d23e85f417)
