### ISSUE TITLE
Some communities cannot be visited.

### ISSUE THREAD

**Issue by enghseb** [Memmy-App/memmy#807]
- [X] have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

Happens since the last update, some communities have stopped working at all. I cannot visit them from either the subscription/traverse page, or by searching for them. The window just flickers instead of showing content. 

Video showing of the bug (Memmy was restarted by closing the app in the app switcher seconds before)

https://streamable.com/b36ha0

As can be seen some communities work (Football) and some don't (Sweden, ABoringDystopia) even though they all are on Lemmy.world. It does not matter if I let the page load for longer, it does not show. It does not matter if I'm signed in to Lemmy.world or Lemm.ee either.

**Comment by sgriff96** [comment]
Can't reproduce. Can you try reinstalling the Memmy app?

**Comment by eoddc5** [comment]
No issues here either. Just tried both Sweden and the dystopia ones

No issues. 

Can you confirm it’s an actual issue or a small hiccup? Will close soon if we don’t hear back @enghseb

**Comment by gkasdorf** [comment]
@enghseb Also, two questions if that doesn't fix it:

1. What instance is this?
2. What are your NSFW settings both for the app and for the site? There was an issue like that in the past but I think it was fixed.

**Comment by enghseb** [comment]
> No issues here either. Just tried both Sweden and the dystopia ones
> 
> 
> 
> No issues. 
> 
> 
> 
> Can you confirm it’s an actual issue or a small hiccup? Will close soon if we don’t hear back @enghseb 

It works after a reinstall. 
So you can close! My bad.

**Comment by gkasdorf** [comment]
@enghseb No prob! Let us know if it happens again 👍

**Comment by enghseb** [comment]
> @enghseb No prob! Let us know if it happens again 👍 

It actually came back after only an hour or so (couple of minutes after I switched my default sorting to top by 6 hours). It stops if I switch the sorting to new instead. But comes back if I leave the page and go back. I then have to switch the sorting to new again. 

I cannot 100% say how to reproduce it. But seems sorting is the issue here. Only seems to happen in communities where no posts have been done during the last 6 hours (when that's my default sort that is)
