### ISSUE TITLE
[Bug]: swipe to vote switch triggers “back”

### ISSUE THREAD

**Issue by Felix-Staud** [Memmy-App/memmy#810]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

https://github.com/Memmy-App/memmy/assets/50131232/9be9159f-dbeb-4a2f-881a-6013dada4919

### Expected Behavior

The switch should change its state without sending you back

### Version

0.5 (3)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 14

**Comment by Felix-Staud** [comment]
This is caused by [`ScreenGestureHandler`](https://github.com/Memmy-App/memmy/blob/dd638bf5a0d69cc4fff3f6d342c1856de58bde0c/src/components/common/Navigation/ScreenGestureHandler.tsx#L30). `swipeToVote` changes causes it to re-render thus throwing us back into the main screen of settings as the component [wraps around the whole Stack of the Bottom navigation](https://github.com/Memmy-App/memmy/blob/dd638bf5a0d69cc4fff3f6d342c1856de58bde0c/Stack.tsx#L563).

**Comment by gkasdorf** [comment]
Fixed.

**Comment by Felix-Staud** [comment]
> Fixed.

I gosh your solution makes so much more sense 😂
