### ISSUE TITLE
[Bug]: Unable to Set Theme 

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#812]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Go to settings and set/change theme. Theme is not changed. Stays on default theme. 

### Expected Behavior

Theme changes as intended. 

### Version

0.5 (4)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iphone 13

**Comment by ebits21** [comment]
Temporarily works again if you toggle match system light/dark theme.

**Comment by theycallmebeez** [comment]
if you do set the theme (only way you can is enabling when it follows system theme) - not all elements are themed properly 

![image](https://github.com/Memmy-App/memmy/assets/382845/bdc27a17-e3ab-4cd9-8004-b4d6d8e98c04)

**Comment by gkasdorf** [comment]
Fixed.
