### ISSUE TITLE
Tapping on a comment from Profile does nothing

### ISSUE THREAD

**Issue by michikade** [Memmy-App/memmy#814]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Go to profile.
Tap ‘View Comments’
Tap on any comment
Nothing happens.

### Expected Behavior

Tapping on a comment should take you to the post in which the comment was made.  This was behavior that happened up until 0.5

### Version

0.5 (4)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iPhone 14 Pro

**Comment by ebits21** [comment]
#786 duplicate
