### ISSUE TITLE
Unread messages marker not updated

### ISSUE THREAD

**Issue by bviefhues** [Memmy-App/memmy#819]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Get new message. 

Mark message as read in another client

Notice that the unread indicator (red dot in tab bar) is still there. 

![IMG_1403](https://github.com/Memmy-App/memmy/assets/1117300/5888b982-aaca-4cb2-a99b-946587963c45)

### Expected Behavior

No red dot if mailbox is read. 

### Version

0.5 (4)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 11 Pro

**Comment by eoddc5** [comment]
Ongoing known issue
