### ISSUE TITLE
Can not access the app.

### ISSUE THREAD

**Issue by sc0ttwood** [Memmy-App/memmy#821]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Can not load the app as I keep getting this error.

### Expected Behavior

Open app -> Get Error -> Close Window -> Get Error -> Close Window -> Get Error -> Get Angry

### Version

0.5(4)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 13

**Comment by sc0ttwood** [comment]
There was no category for adding photos so here:

![IMG_2395](https://github.com/Memmy-App/memmy/assets/138073160/dde13559-9669-4ca2-ac56-a81a74b6aacc)

**Comment by sgriff96** [comment]
What instance are you on?

**Comment by eoddc5** [comment]
Known issue
