### ISSUE TITLE
[Bug]: Refresh State When Switching Accounts

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#832]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

When switching accounts, the state of current view is not refreshed for the new account and leads to errors when trying to vote, save, comment on posts in the feed or comments within posts. 

User must manually refresh state to clear the issue and continue browsing as normal. 

### Expected Behavior

Refresh the state of app overall, especially the current view, for the new account. Scroll to top of feed/comments and refresh. 

### Version

0.5 (5)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

13

**Comment by theycallmebeez** [comment]
This also includes state for communities. When switching accounts then opening a community page it shows the state for prior account (subscribed or not) and the new account cannot subscribe.

**Comment by gkasdorf** [comment]
Fixed now. Sorry for the delay, been busy past few days.

**Comment by theycallmebeez** [comment]
> Fixed now. Sorry for the delay, been busy past few days.

No need to ever apologize. Looking forward to this fix.
