### ISSUE TITLE
[Bug]: Minor Visual Tweak (User Alignment)

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#834]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

In the community sidebar (About) and in comment threads when collapsing comments, the user icons are not aligned. 

The default icon is aligned slightly (maybe 1 or 2px) to the right from users with profile pics/avatars set. 

Example screenshots below. 

![IMG_0972](https://github.com/Memmy-App/memmy/assets/382845/480f675a-2483-42ee-bb71-497efe9b84de)
![IMG_0973](https://github.com/Memmy-App/memmy/assets/382845/4ac9348c-8f5e-4cac-8382-1ef5f15faa60)

### Expected Behavior

All icons are aligned to the same left position. 

### Version

0.5 (5)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

13

**Comment by gkasdorf** [comment]
Should be better now.
