### ISSUE TITLE
Gap in content on feed

### ISSUE THREAD

**Issue by Wxfisch** [Memmy-App/memmy#835]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Scroll through subscribed feed and notice that after a page or two worth of posts there are large gaps between posts shown. 

### Expected Behavior

Posts should have the same padding between them, and it should be relatively small. Instead, the posts show a large gap between after about a page of scrolling. This seems to happen on all filters. See this screenshot as an example:
![IMG_1043](https://github.com/Memmy-App/memmy/assets/25209272/dd0de9f8-7bcb-44ea-9990-dc0979663b8a)

### Version

0.5 (5)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iPhone 14 pro

**Comment by eoddc5** [comment]
Known issue. Thanks for putting it down here as a tracked issue

**Comment by theycallmebeez** [comment]
Question to OP, when you scroll past the gap in content does it repeat old posts or are they new posts?

**Comment by Wxfisch** [comment]
It is new posts, but it will only show two or three then another gap. Doesn’t seem to be a state issue

**Comment by selkuth** [comment]
I’m having this issue too. I see old posts after the gaps though, the same posts in the same order repeating over and over.

**Comment by gkasdorf** [comment]
I've experienced this myself. Will investigate.

**Comment by CaptainCoble** [comment]
I have the same issue. I have get repeats after the gap.  Is seen in both compact mode view and regular.

**Comment by gkasdorf** [comment]
I think I might see the issue. Let me try to fix it up.

**Comment by gkasdorf** [comment]
This is fixed now.

**Comment by selkuth** [comment]
Fixed in the next release? It’s still happening in the latest TestFlight release.
