### ISSUE TITLE
[Feature]: Profile Photo in Tab Bar

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#837]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

If the user has a profile photo set, add an option to use the photo as the profile icon in the tab bar (bottom bar). 

This is a nice way to distinguish accounts visually. 

### Solution

Described above. 

### Alternatives

Yes, the alternative would be to not add the feature or to only add the profile photo in the account chooser.

**Comment by sgriff96** [comment]
Help wanted: display Profile avatar when there is one, but also add a setting to toggle it.

**Comment by dsl101** [comment]
@eoddc5 you can assign this to me. Useful to explore the new codebase & get familiar

**Comment by gkasdorf** [comment]
Merged in now. Thanks @dsl101 !
