### ISSUE TITLE
[Bug]: opening community with no content causes app to blink until I exit community 

### ISSUE THREAD

**Issue by asala6675467** [Memmy-App/memmy#839]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

https://github.com/Memmy-App/memmy/assets/71223258/28c8be6a-c992-44af-804d-c94969811cdd

### Expected Behavior

I expect it to show no posts instead of blinking like this. 

### Version

0.5(5)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 12 Pro

**Comment by ebits21** [comment]
I've had this too.

**Comment by hugpeter** [comment]
Yea, its doing it if you click on the community from a post in /all too. 

https://github.com/Memmy-App/memmy/assets/26207788/443be7bd-5c96-4a1c-b9fb-860840a834eb
