### ISSUE TITLE
[MEM-86] [Feature request] Moving the back button

### ISSUE THREAD

**Issue by JayKayUk** [Memmy-App/memmy#84]
Hi! Would it be possible to make an option to move the “back” button down? Maybe to the bottom navbar? Since gestures are used for upvoting and replying it’s sometimes hard to go back to the feed. Plus, I’ve never understood why the back button is in the top left, the furthest away when you’re using your phone with one hand.

Of course if it’s not possible because of apples UI and swift I understand. 

Thanks for the great app, I’d help you out but I don’t know swift or have a Mac haha

<sub>[MEM-86](https://linear.app/memmyapp/issue/MEM-86/[feature-request]-moving-the-back-button)</sub>

**Comment by gkasdorf** [comment]
Let me first test out giving some extra space to not trigger a swipe action and see if that helps. Once I start working on redesigns, I might find some way to integrate the back button better.

I know it's still further on the left of the screen, but would tapping the "Feed" icon to go back one screen be of any better help?

**Comment by JayKayUk** [comment]
Yeah more space would make it easier I think. 

I just tried the feed button and it works. Don’t know if it’s the last update or I should’ve known the feed button goes back to the feed… duuuh. Thank either way :)
