### ISSUE TITLE
[Bug]: Direct Messages Don’t Show

### ISSUE THREAD

**Issue by asala6675467** [Memmy-App/memmy#843]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

I receive a alert when I got a DM, but it does not show up in inbox.  Found DM in other app (Voyager)

### Expected Behavior

Should list new DM 

### Version

.5(5)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

12 Pro

**Comment by sgriff96** [comment]
We just don't have that built in yet, use #339 to track progress
