### ISSUE TITLE
[Bug]: All communities have 3k subscribers

### ISSUE THREAD

**Issue by drguitarum2005** [Memmy-App/memmy#844]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Search for any community and note that each one shows to have 3k subscribers

### Expected Behavior

Subscriber count should show actual subscribers
![IMG_0317](https://github.com/Memmy-App/memmy/assets/15187807/86f51607-f163-4561-8327-a88d5ec22677)

### Version

0.4 (2)

### App Store or TestFlight?

App Store

### iOS Version

17.x Beta

### Device

iPhone 14 pro max

**Comment by ebits21** [comment]
Already fixed in beta
