### ISSUE TITLE
[Bug]: There is currently a post on All sorted by hot that makes the app crash

### ISSUE THREAD

**Issue by EdwinLundmark** [Memmy-App/memmy#846]
### Check for open issues

- [x] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Use an account on Lemmy.world and go on All sorted by hot then scroll down. The post is also on firefox@fedia.io and it’s posted by shub.

### Expected Behavior

No crashing

### Version

0.5

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 13

**Comment by EdwinLundmark** [comment]
@Felix-Staud [Here is a link](https://lemmy.world/post/2130343) 

I can’t view the post in Memmy so here it is in browser
![IMG_1579](https://github.com/Memmy-App/memmy/assets/69322077/488958e7-208a-4895-a757-d5f43c7361a6)

**Comment by eoddc5** [comment]
This seems incredibly specific so hopefully it’s not an ongoing issue

Lemmy.world is down atm though so I’ll have to wait to test

**Comment by eoddc5** [comment]
I’m not having this problem at all. Have you been able to replicate it again or was this a one time issue you encountered? @EdwinLundmark

**Comment by EdwinLundmark** [comment]
@eoddc5 Yes, it crashes every time I scroll to the post. It’s not on all anymore but you can find it at Firefox@fedia.io

**Comment by theycallmebeez** [comment]
does the app have crash logs or analytics built in that can be shared with the developers?

I searched this post and do not encounter the reported behavior on v 0.5 (5) but there could be a different scenario when browsing via All > Hot. 

The post is 10 hours old as of right now, so not sure best way to find said post in All > Hot.

**Comment by eoddc5** [comment]
It’s not an issue for me. I’ll tag @sgriff96 and @gkasdorf for review
