### ISSUE TITLE
[Bug]: Post & Comment Like count is incorrect

### ISSUE THREAD

**Issue by arjunabrol** [Memmy-App/memmy#848]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

All I did was deleted a post in the middle via the lemmy.world website. Then the like count got messed up on the app. 

### Expected Behavior

The like count should be accurate 

### Version

TestFlight 0.5 (5)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iPhone 11 Pro

**Comment by sgriff96** [comment]
Need more details, how is it wrong? Is it when you downvote or upvote then cancel the vote the vote count shows 0?

**Comment by arjunabrol** [comment]
I’m talking about my profile. Please refer screenshots. On 26-Jul-2023, at 12:19 AM, Sean Griffin ***@***.***> wrote:﻿
Need more details, how is it wrong? Is it when you downvote or upvote then cancel the vote the vote count shows 0?

**Comment by sgriff96** [comment]
There are no screenshots

**Comment by arjunabrol** [comment]
![IMG_0265](https://github.com/Memmy-App/memmy/assets/32477769/df31ebb1-6eaf-4982-b3f7-1055199f8564)
![IMG_0264](https://github.com/Memmy-App/memmy/assets/32477769/c00551c7-1e1c-4db4-a04c-7a2eef8e2927)

**Comment by sgriff96** [comment]
This is just what the API returns when displaying your profile. I would guess there's some federation issues. I've tested on other apps and they display the exact same counts as well.
