### ISSUE TITLE
Can’t remove/add save when post is opened

### ISSUE THREAD

**Issue by iceHtwoO** [Memmy-App/memmy#853]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

When saving a post or removing the save while the post is opened you can’t click it another time to change it again. 

### Expected Behavior

Save can be changed without having to reopen post.

### Version

0.4 (2)

### App Store or TestFlight?

App Store

### iOS Version

17.x Beta

### Device

iPhone 14 pro

**Comment by sgriff96** [comment]
Fixed in test flight
