### ISSUE TITLE
[Bug] : Removed “sort by new [posts]”

### ISSUE THREAD

**Issue by AllergicToGrass** [Memmy-App/memmy#872]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Latest update removed “sort by new [posts]” and replaced it with “sort by new comments”

### Expected Behavior

I’d still like the option to sort by new posts.

### Version

0.5.0.10

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 14 Pro

**Comment by nqnx** [comment]
Same, would like to have the option back. That is even a killer criteria for a client for me.

**Comment by Felix-Staud** [comment]
Don't worry, this wasn't on purpose but just a simple human error. Probably my fault (sorry)

**Comment by Felix-Staud** [comment]
In fact the option is still there (the one with the alarm icon) it's just carrying the wrong translation

**Comment by nqnx** [comment]
No worries and thanks for the update! Memmy is already great
