### ISSUE TITLE
[Feature]: When tapping on a previously made comment, open the original post

### ISSUE THREAD

**Issue by AllergicToGrass** [Memmy-App/memmy#873]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

When viewing a comment you have previously made, tapping on it should take you to the post where you originally made that comment. (I think this feature was there previously but has been removed at some point)

### Solution

- Tap “Profile” on bottom nav bar
- Tap “View Comments”
- Tap on a previously made comment

*feature*
- Open the post the comment was made in

### Alternatives

- Tap “Profile” on bottom nav bar
- Tap “View Comments”
- Tap the 3 dots on a previously made comment

*feature*
- Tap “go to post”

**Comment by Mereo** [comment]
This is one of the most important features to have, as I often want to go back to my previous discussions that I have participated in to see if I can reply to new comments.

**Comment by ebits21** [comment]
Dupe #786
