### ISSUE TITLE
[Bug]: Font size for username, time and community does not scale with the rest

### ISSUE THREAD

**Issue by SivarCalto** [Memmy-App/memmy#876]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

This makes compact view awkward and less compact, as post titles are way smaller than the above mentioned (see picture). In options, I set the smallest font size possible, so NOT system wide font size. 
![IMG_6473](https://github.com/Memmy-App/memmy/assets/139655500/485dee7d-6a17-4665-b4c7-e7d95d436d43)
![IMG_6474](https://github.com/Memmy-App/memmy/assets/139655500/f63fd975-f62f-40e2-9c39-48fcb7e103b1)

### Expected Behavior

Font Site for community, time and user name should scale down like post titles and content. 

### Version

0.5.0 (11)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 12 mini

**Comment by SivarCalto** [comment]
Same thing in the comments btw… this is now the second smallest font size. 
![IMG_6475](https://github.com/Memmy-App/memmy/assets/139655500/6f18ac82-554a-4a8e-921d-b4b35c242d0f)

**Comment by gkasdorf** [comment]
Good now.
