### ISSUE TITLE
[Bug]: Unable to log-in with my account from Kbin.social

### ISSUE THREAD

**Issue by Affection4036** [Memmy-App/memmy#881]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

I've just got notified by another user that there is a great app to browse Kbin, I headed to the App store and downloaded the Memmy app.
After the installation I select:

1. I have an Account
2. Already have a server? > Login
3. And add the following information on the log-in screen:
- Server: kbin.social
- Login: username, all lowercase characters but includes a '_'
- Password: Generated password, generated password, only includes uppercase, lowercase and numbers. It has 20+ characters.

It shows the error shown below:
![IMG_4185](https://github.com/Memmy-App/memmy/assets/15652274/e14fc22c-4f6c-4689-9a08-0618bb0c389a)

I have version 0.4 (latest version) on an iPhone XS Max running iOS 16.5.1

### Expected Behavior

The expected behaviour is go to a next menu or a pop-up telling me that the log-in attempt was succesfull. 

### Version

0.4

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPhone XS Max

**Comment by eoddc5** [comment]
This is a Lemmy client so it won’t allow logging in to kbin accounts. You’ll be able to browse kbin content though
