### ISSUE TITLE
[Bug]: Switching Accounts - Wrong Account Submits Reply/Posts Comment

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#882]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Hey Team, really appreciate the latest update release and you addressing the "Account Switch/Refresh State" for the post feed - https://github.com/Memmy-App/memmy/issues/832.  This is working nicely on the post feed and after switching accounts the votes, comments, etc. work as expected. 

The same issue happens when switching accounts if you have a post open (comment feed).  In this case, switching accounts does not refresh the logged in user and if you reply to the post it submits as the user that was first logged in, not the user that was switched to.

### Expected Behavior

When switching account, the user that was selected should be the user replying/commenting, voting, saving, blocking, etc.

### Version

v 0.5.0 (11)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iPhone 13

**Comment by eoddc5** [comment]
@gkasdorf @sgriff96 can we force a total app refresh when accounts are switched? this will probably solve any issues pertaining here about "which account is seeing/posting what"

account switcher refreshes app anew, account switched to takes over and no history of the previous account is cached.

this will lose where you are. but will solve any weirdness, and would be expected similarly to logging out and logging in a new account

**Comment by theycallmebeez** [comment]
If the user opens a post and then switches accounts to comment from a different account, I do not think refreshing the entire app would deliver the expected experience and would leave them at the top of their Post Feed for the new account.

**Comment by sgriff96** [comment]
> If the user opens a post and then switches accounts to comment from a different account, I do not think refreshing the entire app would deliver the expected experience and would leave them at the top of their Post Feed for the new account.

We have to though, switching accounts to a different instance would completely change all the ids of the post, comments etc. so replying would not work.

**Comment by gkasdorf** [comment]
Fixed.
