### ISSUE TITLE
Most Comments Sort Duplicated (Mislabeled?)

### ISSUE THREAD

**Issue by ebits21** [Memmy-App/memmy#884]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Sort post has sort by most comments listed twice. I think one is mislabeled.

![IMG_7924](https://github.com/Memmy-App/memmy/assets/19845100/30c0d072-f438-4629-aae2-f7d493aa8492)

### Expected Behavior

Different label

### Version

5.0 (11)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 12

**Comment by sgriff96** [comment]
Yep mislabeled but i believe @Felix-Staud was going to put up a pr for it

**Comment by Felix-Staud** [comment]
This will be fixed in the next version:
https://github.com/Memmy-App/memmy/pull/878
