### ISSUE TITLE
[Bug]: [EPIC] Next Comment button needs work

### ISSUE THREAD

**Issue by eoddc5** [Memmy-App/memmy#885]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

General ticket to capture any duplicates reported by users for issue complaints for the "Next Comment Button" being wonky

This is a BETA feature, so this is to be expected to be funky. Will be improving the button and how it works over time.

### Expected Behavior

General ticket to capture any duplicates reported by users for issue complaints for the "Next Comment Button" being wonky

This is a BETA feature, so this is to be expected to be funky. Will be improving the button and how it works over time.

### Version

0.5 

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iPhone 14 Pro

**Comment by gkasdorf** [comment]
This *should* be fixed up now.
