### ISSUE TITLE
Bug: can reply to deleted comments and see the comment

### ISSUE THREAD

**Issue by shofhna** [Memmy-App/memmy#886]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Hello, on latest update version
You can see deleted  comment by user or by moderator just try to reply to comment and you will see it

### Expected Behavior

Not possible to reply on deleted comment

### Version

0.5.0(11)

### App Store or TestFlight?

App Store

### iOS Version

17.x Beta

### Device

Iphone 11 pro

**Comment by eoddc5** [comment]
can you post a screenshot or recording so we can see this in action?

**Comment by sgriff96** [comment]
Closing since we got no response from issue creator
