### ISSUE TITLE
[MEM-88] Make text selectable (for copy/paste)

### ISSUE THREAD

**Issue by JeremyLeland** [Memmy-App/memmy#89]
I would like to be able to select text in posts and comments to copy and paste elsewhere. 

Currently, tapping and holding on text doesn’t do anything. I would expect it to select the text under the tap (as it does elsewhere in iOS). 

I realize this may complicate tapping to collapse/expand comments, so it may not be as straightforward as I’m describing (Apollo doesn’t select text directly either, but it brings up a context menu with an option that eventually lets you select text.)

<sub>[MEM-88](https://linear.app/memmyapp/issue/MEM-88/make-text-selectable-for-copypaste)</sub>

**Comment by gkasdorf** [comment]
There's an option currently in the little "..." to copy the post text. I'll experiment more with a better way to do this. I'll also add a onLongPress to the comment for this option to pop up regardless of whether you do the ... or long press. Thanks!

FYI, more options to this screen will be coming as well, such as edit and delete. Will be done soon.

**Comment by sallyFoster** [comment]
![image](https://github.com/Memmy-App/memmy/assets/104597302/6dc2f635-3f8e-460d-9af6-ac3ce30cade7)

When I tap the .. there is no option to copy the text of the post

**Comment by gkasdorf** [comment]
I'm adding this in with mod tools. Should be finished tomorrow.

**Comment by sallyFoster** [comment]
I saw that you released an update today, but it still didn't have the option 😢. Also why did you change the way upvotes and downvotes looked for comments? That way was way cooler and unique.

**Comment by gkasdorf** [comment]
@sallyFoster Should be done today.

What do you mean by the way the upvotes were displayed? I don't think there were any changes there?

**Comment by sallyFoster** [comment]
Before, you could see both upvotes and downvotes in comments. It showed them separately. Now it adds them both and shows the result of the addition.

**Comment by eoddc5** [comment]
> Before, you could see both upvotes and downvotes in comments. It showed them separately. Now it adds them both and shows the result of the addition.

There’s a toggle for combining scores

turn that off

**Comment by gkasdorf** [comment]
^ Yup, under "Appearance -> Display Total Score"

**Comment by eoddc5** [comment]
> I saw that you released an update today, but it still didn't have the option 😢. Also why did you change the way upvotes and downvotes looked for comments? That way was way cooler and unique.

Please have some flexibility with the dev team who is working on this on the side. There’s no obligation that devs (who are working in their spare time, for free) to do any specific feature requests besides what they see fit to do

@gkasdorf mentioned he would be working in this and said “should be finished tomorrow”. Likely there is an issue, something else (or life) took precedence

**Comment by eoddc5** [comment]
> ![image](https://user-images.githubusercontent.com/104597302/257104381-6dc2f635-3f8e-460d-9af6-ac3ce30cade7.png)
> 
> When I tap the .. there is no option to copy the text of the post

Sorry ANOTHER reply

Can you update your app. You’re on quite an old one. 


![image](https://github.com/Memmy-App/memmy/assets/10222895/dee225ac-6f6d-450d-97db-b13482cdfccc)

**Comment by sallyFoster** [comment]
That is for comments. It has been there for a while. I am referring to posts.

**Comment by sallyFoster** [comment]
@eoddc5 My bad, since I saw an update that was just released today in the App Store, I thought that maybe they fixed the issue in their end, and a bug that they were not aware arose.

**Comment by sallyFoster** [comment]
@gkasdorf My bad, I didn't mean to rush you or anything. I just thought that you might have released the change, but that an unexpected bug that you were not aware of, caused it to not show. 

Thank you so much for this app!! It is the bomb!! I like it wayyy more than Reddit!! ❤️

**Comment by ftatateeta** [comment]
@gkasdorf  I added a copy to clipboard menu button for posts and comments in my fork. Should I make a PR for it?

**Comment by gkasdorf** [comment]
> @gkasdorf  I added a copy to clipboard menu button for posts and comments in my fork. Should I make a PR for it?

Yes!
