### ISSUE TITLE
[Bug]: Inbox message reappear as unread

### ISSUE THREAD

**Issue by dsl101** [Memmy-App/memmy#892]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

New reply in Inbox, swipe left to mark as read. Message disappears and tabbar notification clears. After about 15 seconds, the unread notification and message reappear.

I've switched accounts, logged out and in again, etc. Account is on feddit.uk.

### Expected Behavior

Messages marked as read would stay read.

### Version

0.5.0 (13) and previous TestFlight version

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

SE 2022

**Comment by ebits21** [comment]
I've noticed this too. Only happens if you swipe to mark a certain comment as read.

Marking all as read with the button works fine.

**Comment by gkasdorf** [comment]
Thanks. This will be fixed tomorrow.
