### ISSUE TITLE
[Bug] Multiple items are duplicates if you continue to scroll in the feed

### ISSUE THREAD

**Issue by machie27** [Memmy-App/memmy#893]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Open the hot feed.
Scroll to the bottom, wait for items to load. 
Check that this set is already present. 
scroll down and let new set of items load. 
Now you have a different set. 
Scroll down again.
Now there the same set as above

To note: I have two accounts in memmy

### Expected Behavior

No duplicates of posts in the selected feed

### Version

0.5.0.13

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iPhone 12 Pro

**Comment by sgriff96** [comment]
Explanation makes no sense.

You are probably just seeing reposts if you are seeing the same post multiple times

**Comment by machie27** [comment]
No I don’t:
See screenshots first and after scrolling. Same post, even with the same other item below about cricket. Definitely after scrolling:
![image](https://github.com/Memmy-App/memmy/assets/6714617/c96ab2a0-cbe0-4835-a72a-bda0dbdf77bb)
![image](https://github.com/Memmy-App/memmy/assets/6714617/fde7a806-f4aa-4818-8c12-69f977553b04)

**Comment by machie27** [comment]
I’ll update this tomorrow when I’m back at the computer. Definitely same dataset. See if the api call maybe returns the same dataset or that it’s a caching problem of some sort. Its in the night here now and I’m working from my phone

**Comment by machie27** [comment]
Bug is there. Try scrolling for 10 minutes and you’ll get duplicates. Same order and same posts. Not crosspost. Have not come across this on other lemmy apps or the website itself

**Comment by krims0n32** [comment]
Seeing a lot of duplicates as well in the subscribed/hot view. Exact same post by exact same user in exact same community with exact same post timestamp appears multiple times. Definitely looks like a bug.

**Comment by sgriff96** [comment]
Should be fixed in next build
