### ISSUE TITLE
[Bug]: On "Hubs" screen, clicking into site details generates missing unique key error

### ISSUE THREAD

**Issue by gitbrent** [Memmy-App/memmy#895]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

# Steps

1. Go to Hubs screen
2. Click on a server (the ">" symbol) 
3. Error shown on screen and in terminal

![Screenshot 2023-07-29 at 20 50 53](https://github.com/Memmy-App/memmy/assets/7218970/24dbe6ef-6eb4-457b-8b5f-8b9a98642e50)
![Screenshot 2023-07-29 at 17 16 40](https://github.com/Memmy-App/memmy/assets/7218970/4659df0e-4bfa-4631-a6de-a7647c300692)
![Screenshot 2023-07-29 at 17 17 56](https://github.com/Memmy-App/memmy/assets/7218970/c5ad7a8d-de50-4a6c-8b69-17c3d16573f6)

### Expected Behavior

Elements produced by array.map should always have `key` properties.

The VStack React.Fragments produced here do not:

https://github.com/Memmy-App/memmy/blob/23dce84f07a5b26754152d7cc95d5c34d47af384/src/components/common/Table/MTable.tsx#L28-L33

### Version

1.0.0

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone SE 3rd gen (expo simulator)

**Comment by eoddc5** [comment]
Hey @gitbrent theres no version 1.0.0. 

Just want to verify what build you’re on for testing out

**Comment by eoddc5** [comment]
This should only be an informational error during dev (which makes sense you see it)

doesn’t exist on the full running app

**Comment by gitbrent** [comment]
Ah, okay. Thought i'd found something easy to work on. :)
