### ISSUE TITLE
[Bug]: “Show more comments…” showing on collapsed comments

### ISSUE THREAD

**Issue by Hikiru** [Memmy-App/memmy#897]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Collapse a comment
![IMG_6147](https://github.com/Memmy-App/memmy/assets/18605854/69a34a01-2933-46c8-ac19-8505ac25ed6c)

### Expected Behavior

Don’t show “Show more comments…” on collapsed comments

### Version

0.5.0

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 13

**Comment by gkasdorf** [comment]
Oh wow that looks crazy lol. Thanks.
