### ISSUE TITLE
[Bug] blue down arrow symbol blocks other elements. 

### ISSUE THREAD

**Issue by deroverda** [Memmy-App/memmy#899]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

When scrolling all the way down to the bottom comment the blue down arrow is blocking the reply, up and downvote buttons. I will attach a screenshot. 

### Expected Behavior

The blue down arrow symbol shouldn’t be visible when the user is already at the bottom of a comment section. 

### Version

0.5.0.11

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPhone SE (2nd generation)

**Comment by deroverda** [comment]
![IMG_3627](https://github.com/Memmy-App/memmy/assets/70813982/844e926e-2b81-4c94-9cf6-5363922b721c)

**Comment by deroverda** [comment]
I was wrong about replying. That works since it's not blocked. But up/down vote doesn't work as you can see.

**Comment by eoddc5** [comment]
This is known. Working on a fix to that button

**Comment by deroverda** [comment]
> This is known. Working on a fix to that button 

Sorry. Should have searched better. First time I encounter this.
