### ISSUE TITLE
[BUG] Colour issues with the new 0.0.1(47) comments screen

### ISSUE THREAD

**Issue by z01L** [Memmy-App/memmy#91]
**Describe the bug**
Upvote and downvote colours are reversed. Upvote shows up as orange and downvote as green.

When you turn the phone landscape then back to portrait, green and blue coloured lines appear on the screen.

**To Reproduce**

1. Go to the comments screen on a post
2. Rotate the phone landscape and wait for text to realign
3. Rotate the phone portrait

**Expected behavior**
Upvote and downvote colours switched around. No green and blue lines appear when rotating phone.

**Screenshots**

![](https://uploads.linear.app/7655b776-38c4-4273-b069-78045fe3cd9c/7083f6d7-7a08-4f0b-823a-0e98a7fe8986/6871b424-e9e7-4ef5-a65a-0815105ec12f)

**Smartphone (please complete the following information):**

* Device: iPhone 13 Pro Max
* OS: iOS 16.5
* Version 0.0.1(47)

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-89](https://linear.app/memmyapp/issue/MEM-89/[bug]-colour-issues-with-the-new-00147-comments-screen)</sub>

**Comment by gkasdorf** [comment]
Yikes what happened?! Let me look into that.

**Comment by z01L** [comment]
The green and blue line issue seems to have been resolved in 0.0.1(49) although I noticed that the time to realign text when rotating the phone is slower.

The colour of the upvote/downvote still seems incorrect though. It should be green for upvote and orange for downvote right?

**Comment by gkasdorf** [comment]
The time it takes to reload is some rendering issues. Currently, the comment rendering is subpar to what it could be, and I have plans to refactor that into a much more management system for performance reasons. I'll get onto this sooner rather than later.

**Comment by ann0see** [comment]
Just as question: To me it seems as if you're not using the standard UI Kit styling but rather something with JS? I believe this is a lot more work to get right (as there seem to be quite some strange UI bugs and the app doesn't feel native)

**Comment by gkasdorf** [comment]
> Just as question: To me it seems as if you're not using the standard UI Kit styling but rather something with JS? I believe this is a lot more work to get right (as there seem to be quite some strange UI bugs #78 and the app doesn't feel native)

It is the result of a needless re-render. I'll make some changes to resolve this issue.

**Comment by sgriff96** [comment]
@gkasdorf is this still an issue? I assume not

**Comment by gkasdorf** [comment]
Don't think so. Should be using the theme. Other comment issues we already know about so we can close this.
