### ISSUE TITLE
[Bug] “mark read on image view” turned off but posts being marked as read

### ISSUE THREAD

**Issue by ScoobyDoo27** [Memmy-App/memmy#913]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

I click on an image and when I swipe away everything works as it should, it doesn’t mark my post as read. However, if I reload my feed, all the images I had viewed now show as read. 

### Expected Behavior

Images should never be marked as read when viewed. 

### Version

0.5.0.13

### App Store or TestFlight?

App Store

### iOS Version

17.x Beta

### Device

iPhone 14 Pro Max

**Comment by eoddc5** [comment]
@gkasdorf and I just tried to and neither of us were able to reproduce this 

not sure what’s going on. Works as intended for me. 

Can you try updating the app or uninstalling and reinstalling (account settings will remain when you reinstall)

**Comment by eoddc5** [comment]
@ScoobyDoo27 wait. do you have either of the mark read on scroll enabled?

**Comment by ScoobyDoo27** [comment]
I am not using the mark read on scroll. The only one I have turned on is "mark read on post open". I didn't catch it in my original post but I am using the newest TestFlight version. I did delete and re-install but it still marks read on refresh.

**Comment by gkasdorf** [comment]
@ScoobyDoo27 Apple was super weird and didn't approve the TF version but *did* approve App Store release. Anyway, can you try the App Store release quickly to see if it works there? This is the one occasion where that is actually more up to date than TF.

**Comment by ScoobyDoo27** [comment]
The App Store version is doing the same thing as well. I can make a video to show what it’s doing if that’ll help.

**Comment by gkasdorf** [comment]
@ScoobyDoo27 that would be great if you could. Thanks.

**Comment by ScoobyDoo27** [comment]
Here is a link to my settings and a video of the behavior: [Link](https://www.dropbox.com/scl/fo/xf8lvpzn1jhuba9ruerxa/h?rlkey=32pq16p0uerbi979bn4mh3peb&dl=0)

**Comment by eoddc5** [comment]
ok that video helps

please make sure to clarify, next time, that youre in compact mode :)

doing this, in compact mode, does trigger the read status, @gkasdorf

**Comment by gkasdorf** [comment]
@ScoobyDoo27 Ok I think I found what the issue was. If once the update is out it isn't fixed, feel free to either open a new issue or @ me here 👍
