### ISSUE TITLE
[Bug] tap to collapse disabled in settings, yet comments still collapse when tapped

### ISSUE THREAD

**Issue by valareevandyken** [Memmy-App/memmy#918]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

In settings, disable tap to collapse. In any comments section, tap a comment. It will collapse.

I noticed this after enabling swipe left to collapse and disabling tap to collapse, but the bug occurs regardless of whether or not swipe left to collapse is enabled.

### Expected Behavior

When “tap to collapse” is disabled, tapping on a comment should not collapse it. Tapping on a comment collapses it regardless of whether or not tap to collapse is enabled.

### Version

0.5.1.1

### App Store or TestFlight?

App Store

### iOS Version

16.5.1

### Device

iPhone XR

**Comment by gkasdorf** [comment]
Fixed https://github.com/Memmy-App/memmy/issues/917
