### ISSUE TITLE
[Bug] certain tap flicks when scrolling open a link instead of scrolling

### ISSUE THREAD

**Issue by chicaneau** [Memmy-App/memmy#923]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

When scrolling with a certain tap and flick up gesture. Memmy will often often a link, meaning you have to go back. I haven’t seen this type of behaviour in other social media apps. It’s hard to describe exactly how I make it happen. But I can reproduce it about 1 in 3 times. Sort of tap as you scroll I guess in a flicking type action with minimal time with finger on the screen 

### Expected Behavior

Scroll normally

### Version

0.5.0.13

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 14 Pro

**Comment by eoddc5** [comment]
I have no clue. There’s no flicking link opening gestures

**Comment by dsl101** [comment]
I see that behaviour too—it's not just links, it happens on posts too. Probably some overlap in the swipe and tap handlers detecting those events.

**Comment by dsl101** [comment]
It's definitely not user error :/. But, as @chicaneau said it's hard to replicate. The gesture needed is a very short duration upward scroll on the main feed, perhaps with some slight sideways (basic thumb scroll movement). I guess it's nothing Memmy is doing though, but the underlying RN components?

**Comment by eoddc5** [comment]
I get it, misclicks and misswipes that lead to unrequested actions are possible

but when we dont have a clear way to reproduce, I cant really make any sense of it

im trying to mess with scrolling in every way I can, and I just cannot replicate any issue.... maybe 1 tap out of 100 opens the post up, but its because im swiping like an insane person on the app

until I have easily replicable steps, I cant really make this a "bug"

maybe take a video of yourself using the app? thats all I can think of, since screen recordings wont work here :p

**Comment by dsl101** [comment]
OK, I think I've perfected my technique :). I can get it about 95% now.

I will try to find another device and record if I can, but for me it's a short (less than 10mm) diagonal swipe up and left on a post in the main feed. You can see the effect on the app here—the feed starts to scroll (and continues to do so), but the image also opens. When the image is closed, the feed is in its new position.

https://github.com/Memmy-App/memmy/assets/900542/76bcaef0-19cf-4a61-81dc-afd950f26ea0

**Comment by dsl101** [comment]
Also happens with collapsing comments. I'm convinced now that it's a very short duration drag being also interpreted as a press. Probably somewhere in the gluestack Pressable / RN usePress configuration. 

In this recording, I've collapsed all comments apart from the first. I scroll down and up a bit 'normally', then 'flick' the comment upwards. The comment list scrolls, but the drag was so short it also triggered the press event and collapses the comment. 

https://github.com/Memmy-App/memmy/assets/900542/1a8358a7-22e0-470b-ab8b-37683de1f805

I will try to see if I can affect it with the configuration of those components when I get chance next week. Would it be ok to reopen this though @eoddc5 ?

**Comment by chicaneau** [comment]
> OK, I think I've perfected my technique :). I can get it about 95% now.
> 
> I will try to find another device and record if I can, but for me it's a short (less than 10mm) diagonal swipe up and left on a post in the main feed. You can see the effect on the app here—the feed starts to scroll (and continues to do so), but the image also opens. When the image is closed, the feed is in its new position.
> 2023-08-01.17.53.40.mp4

Thanks for recording this while i slept @dsl101, both your videos are exactly the behaviour i see.
