### ISSUE TITLE
Accent Colour has no ability to be undone, once applied

### ISSUE THREAD

**Issue by tranquilcarbon** [Memmy-App/memmy#929]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

When a custom accent colour is set in the appropriate section, there is no way to turn it off if you want to use the default colour used by the chosen theme.

### Solution

A simple way to solve this would be to add a toggle for custom accent colours so it can be turned on or off

### Alternatives

Another alternative might be to automatically reset and disable the accent colour when the theme changes (for example, from Dracula to OLED) but this might cause unnecessary annoyance to users.

**Comment by sgriff96** [comment]
Fair, to get around it for now you can just go change themes and change back to your original theme. This will reset the accent color.

**Comment by sgriff96** [comment]
Oh sorry that doesn't work anymore, my mistake. But you can put an invalid hex code in as well and it will reset to the themes accent. Just tested that myself.

**Comment by sgriff96** [comment]
You can now put an empty value in and it will clear the accent color selection and reset to the default
