### ISSUE TITLE
[Bug]: Show hide read button doesn’t appear if hide read post on feed isnt on

### ISSUE THREAD

**Issue by slrgt** [Memmy-App/memmy#932]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Turn off hide read post on feed while hide read post button is enabled.

### Expected Behavior

The hide read posts button should be visible so i can choose when to hide read posts without posts hiding automatically on refresh

### Version

.6.0

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone

**Comment by eoddc5** [comment]
I dont understand this one.

the "hide read button" filters out the read posts.

if "hide read posts on feed" is off, then you would not be hiding anything, and the button would not work, it would just be a floating artifact 

this is set up like this by purpose

**Comment by slrgt** [comment]
@eoddc5 the idea is so we have a choice if when to hide the posts instead of always hiding all posts when you refresh. Sometimes we only scroll a little bit snd want to come back to the threads after a few hours but currently if you go back to the top they automatically hide.

the button should be able to stay visible and work when clicked without also automatically hiding every time the app is refreshed
