### ISSUE TITLE
[Feature]: subscribe to thread

### ISSUE THREAD

**Issue by slrgt** [Memmy-App/memmy#933]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

Ability to receive notifications to on any update to a thread whether the OP makes an edit, a new comment on the thread or a reply to any comment in the thread

### Solution

Subscribe to thread button

### Alternatives

The only alternative is saving a post and manually going back to it snd scrolling through every comment to see if sny comment has gotten replies

**Comment by eoddc5** [comment]
not a feature in the roadmap.

**Comment by slrgt** [comment]
Isn’t this the place to submit feature requests so they can be added to the roadmap?
