### ISSUE TITLE
[Bug]: comment jump button will always jump to first comment on first press, even after scrolling past it

### ISSUE THREAD

**Issue by Hikiru** [Memmy-App/memmy#934]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Scroll past top comment by any length, press comment jump button

### Expected Behavior

Jump to the next comment down

### Version

0.6.0 (1)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 13

**Comment by gkasdorf** [comment]
At first glance the logic actually seems correct but I do notice the issue. Will fix now.

**Comment by Hikiru** [comment]
@gkasdorf it still jumps to the first comment on the first press, but it is correctly updating after.
