### ISSUE TITLE
[Feature]: Long press comment jump button to jump to last comment

### ISSUE THREAD

**Issue by Hikiru** [Memmy-App/memmy#935]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

Long press the comment jump button to jump to previous comment. This is how Apollo’s worked

### Solution

Make long pressing the comment jump button jump to previous comment

### Alternatives

None

**Comment by gkasdorf** [comment]
Finished now :) @Hikiru
