### ISSUE TITLE
[Bug]: inbox text misaligned in latest TestFlight update

### ISSUE THREAD

**Issue by Hikiru** [Memmy-App/memmy#936]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Look at inbox button
![image](https://github.com/Memmy-App/memmy/assets/18605854/84c71eb1-fecf-4e30-9032-0e2c48eae4ea)

### Expected Behavior

Not misaligned

### Version

0.6.0 (1)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 13

**Comment by eoddc5** [comment]
Known bug. Being fixed
