### ISSUE TITLE
[Bug]: App treats logged-in duplicate usernames across instances as one

### ISSUE THREAD

**Issue by soren446** [Memmy-App/memmy#942]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Log into two Lemmy accounts on different instances with the same username before the @. Then, try logging out of one and it deletes both. 

https://github.com/Memmy-App/memmy/assets/141293054/2ff8b6d8-e068-4851-8e65-6640d9c6c462

### Expected Behavior

Accounts with the same username on different instances should be treated differently when doing something like logging out. In my video, I’m using soren446 on the lemmy.world and hexbear.net instance. However, when I log out of one, it logs out of both. 

### Version

0.5.1

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPhone 14 Pro Max

**Comment by eoddc5** [comment]
Replicated. 

@gkasdorf

**Comment by gkasdorf** [comment]
Thanks, will fix.

**Comment by gkasdorf** [comment]
Should be good now.
