### ISSUE TITLE
[Feature]: Implement PM’s

### ISSUE THREAD

**Issue by allluke** [Memmy-App/memmy#945]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

The ability to send and receive personal messages. 

### Solution

Personal Message (PM, or DM) added to the app. 

### Alternatives

Couldn’t see any alternative except to use web app.

**Comment by theycallmebeez** [comment]
there is already a feature request for this - https://github.com/Memmy-App/memmy/issues/339

@eoddc5

**Comment by gkasdorf** [comment]
I opened up a branch for this last night. I'll be finishing it up probably by Monday. See the issue above for when that's done.
