### ISSUE TITLE
[Bug] default feed sort options not respected at launch

### ISSUE THREAD

**Issue by Veedems** [Memmy-App/memmy#951]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Opening the app after iOS kills it in the background forces it to load the All feed sorted by Hot. In my settings, I have the default order set to Subscribed and New. 

### Expected Behavior

Feed should load as set in the settings. 

### Version

0.6.0.2

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iPhone 12

**Comment by gkasdorf** [comment]
Found this issue and has been fixed. Thanks!

**Comment by hungryca-t** [comment]
I am not finding that this issue has been resolved. Please see also my original issue #917
