### ISSUE TITLE
[Feature]: option to move the scroll to next comment button to the middle

### ISSUE THREAD

**Issue by slrgt** [Memmy-App/memmy#954]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

Apollo had the option to place it in the middle or either side for people with larger hands or left handed people to be able to reach it in the most comfortable location

### Solution

Option to move the button to the middle

### Alternatives

(Thanks for all the amazing work you do on memmy! Please enable github sponsors and a patreon)

**Comment by sgriff96** [comment]
Just did this, while you can't drag it around like i think Apollo allowed, you can now set it to "Bottom Right" "Bottom Left" or "Bottom Center" in the Appearance settings.

**Comment by slrgt** [comment]
amazing, ur the best!
