### ISSUE TITLE
[Feature]: Release IPA file (again)

### ISSUE THREAD

**Issue by My-ThrowAwayAccount** [Memmy-App/memmy#956]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

I would like for the IPA file to be released as the TestFlight beta is currently full and the latest release to include one is (the very outdated) [pre-release 0.0.2.17](https://github.com/Memmy-App/memmy/releases/tag/0.0.2.17).
Jailbroken devices (and any device with AltStore and the likes) can install IPAs without the AppStore or TestFlight, so it would be really handy for the ones that did not get into the TestFlight in time.
The IPA has been released in the past after issue #353

### Solution

Attach the IPA to every new release that comes out

### Alternatives

Attach the IPA on a non-regular basis, depending on the release type

**Comment by Felix-Staud** [comment]
The test flight version is usually not too far behind the App Store one. I’m not saying this is obsolete I’m just saying this won’t gain you much

**Comment by My-ThrowAwayAccount** [comment]
The point is that we can't access the TestFlight version since there's no free slots available

**Comment by gkasdorf** [comment]
I'll do this on the next update here shortly.
