### ISSUE TITLE
[Bug]: instance filters disappear after a while

### ISSUE THREAD

**Issue by martijk** [Memmy-App/memmy#957]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Settings -> Filters -> Instances -> add some hostnames of instances. Force close and reopen the app and note that the list is now empty. It has been this way for me since I discovered this feature, on iOS 16 as well as on iOS 17 beta. Instead of force close, you can also wait until the app is closed in the background by the OS. 

### Expected Behavior

The filter list should be retained. 

### Version

0.6.0 (2)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iPhone 12 Pro Max

**Comment by eoddc5** [comment]
Known bug. Thanks for reporting!

**Comment by darkniobe** [comment]
Bug also exists in App Store version 0.5.1 (1)

**Comment by mateohhh** [comment]
Just came to report this, appreciate that it’s high priority.

**Comment by gkasdorf** [comment]
No longer an issue
