### ISSUE TITLE
[Bug]: Crash when tapping share on a community

### ISSUE THREAD

**Issue by fynnay** [Memmy-App/memmy#959]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

- Navigate to a community
- Tap the three dots at the top right
- Tap “Share”

### Expected Behavior

- The app crashes instantly. Re-opening it brings us back to the front page

- Would expect it to instead show the sharing options

### Version

0.5.1.1

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPhone 12 Mini

**Comment by sgriff96** [comment]
This is fixed on latest build
