### ISSUE TITLE
[Bug] Cannot clear notification icon when PM was received and marked as read on web

### ISSUE THREAD

**Issue by efwis** [Memmy-App/memmy#960]
### Check for open issues

- [x] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Can’t clear notification icon for received inbox notifications if a pm was recieved and cleared via pc 
![IMG_0635](https://github.com/Memmy-App/memmy/assets/105600820/651fe2d5-1575-4902-a7d8-b77296a23e69)

### Expected Behavior

Should be cleared when another device uses Lemmy

### Version

0.5.1.1

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPhone 11

**Comment by eoddc5** [comment]
We don’t support PM stuff yet so this might be why. 

@gkasdorf @sgriff96 thoughts?

**Comment by sgriff96** [comment]
@efwis have you clicked the top right button to "mark all as read"?

**Comment by gkasdorf** [comment]
I opened up a branch last night to work on PMs and mentions, so should be available soon. But there's also another possibility that I'll check into.

**Comment by efwis** [comment]
I have clicked on all buttons, o realize pm aren’t added yet, but there should be some sort of checking code that would notify the app that the pm was opened by another device such as a computerSent from my iPhoneOn Aug 5, 2023, at 10:34 PM, Sean Griffin ***@***.***> wrote:﻿
@efwis have you clicked the top right button to "mark all as read"?

**Comment by gkasdorf** [comment]
Should be fixed up here shortly.
