### ISSUE TITLE
[Bug]: profile’s comment section total vote is not working

### ISSUE THREAD

**Issue by fmflurry** [Memmy-App/memmy#961]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

1. Open memmy app
2. Go to Profile tab
3. Comments’ upvotes count is wrong

### Expected Behavior

Comments’ upvotes count displays the real score.

### Version

0.6.0 (2)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

IPhone 11 Pro

### screenshot

![image](https://github.com/Memmy-App/memmy/assets/47488233/68e2aba9-8f8d-4fff-a0d2-d19ac58d8548)

**Comment by gkasdorf** [comment]
This is a Lemmy issue. We only display what is reported from the API. Unfortunately it seems to be a bug with federation.
