### ISSUE TITLE
[Bug]: Code TypeError: Cannot read property 'getPersonDetails' of null

### ISSUE THREAD

**Issue by J-The-Fox** [Memmy-App/memmy#964]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Opened the app and received the Unknown Error with a description of `Code TypeError: cannot read property '<shown below>' of null`. Doing a restart of the app and phone had no effect. Have also sent beta feedback through taking a screenshot as well. Thought it was working fine then, but it seems to broke after that error. The only page that works is settings. Everything else leads to the TypeError

Here is the 4 TypeErrors I am receiving: 
![image](https://github.com/Memmy-App/memmy/assets/116409406/234b6dd1-f7f6-44b7-a5bf-910e348fc2f6)
![image](https://github.com/Memmy-App/memmy/assets/116409406/786e8e1d-d056-412f-88ad-c19ef3557595)
![image](https://github.com/Memmy-App/memmy/assets/116409406/14a0f7de-93fc-41e9-8ad3-f76f210f1490)
![image](https://github.com/Memmy-App/memmy/assets/116409406/b1ab44a1-c375-4adc-b63b-3863f9d32997)

### Expected Behavior

Open the app and be able to view the current page. Only page that works is the settings page. Every other page leads to an unknown error

### Version

0.6.0 (2)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iPhone 11

**Comment by Felix-Staud** [comment]
Which instance is your account on? Did you try re-log with your account ?

**Comment by Felix-Staud** [comment]
Just keep an eye on Lemmy status (link in settings)

**Comment by J-The-Fox** [comment]
Sounds good, appears to be functioning once again so it probably was an issue with that instance
