### ISSUE TITLE
[Feature]: Search bar inside communities

### ISSUE THREAD

**Issue by Levsgetso** [Memmy-App/memmy#965]
### Check for open issues

- [ ] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

To access the search bar it would be required to scroll down from the top of the community page, like in some official IOS apps, like Settings.
![IMG_3655](https://github.com/Memmy-App/memmy/assets/141684216/ca4295ed-712f-46c8-b6ad-9789e4bda964)

### Solution

It would make it possible to search for posts inside communities, which would have better search results.

### Alternatives

I have thought about this for some time now and I feel that this would be the cleanest and most user-friendly way to search inside communities.

**Comment by sgriff96** [comment]
Please look for duplicates next time
