### ISSUE TITLE
[Feature]: user selected text in formatting wizards

### ISSUE THREAD

**Issue by RustedSwitch** [Memmy-App/memmy#969]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

When composing text, I want to select existing text and and format it, by adding a hyperlink or enriching it as italics. 

### Solution

When I preselect unformatted text and 

…tap to add a hyperlink, my selected text should be populated in the “show text” field. 

…tap italics, my selected text should be wrapped in the formatting characters. 

### Alternatives

Na

**Comment by gkasdorf** [comment]
Does this not currently work? It is supposed to but might be broken. Regardless I'm overhauling stuff and getting ready for a major update so I'll make sure its fine.

**Comment by RustedSwitch** [comment]
It has never worked, as far as I can tell. I’ve been a user of the app since close to the beginning. ~BHOn Aug 8, 2023, at 6:50 AM, Gavin Kasdorf ***@***.***> wrote:﻿
Does this not currently work? It is supposed to but might be broken. Regardless I'm overhauling stuff and getting ready for a major update so I'll make sure its fine.

**Comment by gkasdorf** [comment]
Done.
