### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by daweston** [Memmy-App/memmy#975]
### Check for open issues

- [ ] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Video plays incredibly fast:

https://lemm.ee/post/3529632

### Expected Behavior

Video plays at normal speed. 

### Version

0.6.0.2

### App Store or TestFlight?

App Store

### iOS Version

17.x Beta

### Device

iPhone 13 Pro

**Comment by sgriff96** [comment]
Why would you not look for duplicates when we literally ask you to do it

**Comment by daweston** [comment]
That response seems a little harsh. I looked but didn’t see the bug. I’m sorry if my search didn’t turn it up. Just trying to help the app out.

**Comment by eoddc5** [comment]
No title
