### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BobDaGeek276** [Memmy-App/memmy#980]
### Check for open issues

- [x] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

In the comment section, the Imgur links cover up the text instead of spacing them out.

![IMG_0664](https://github.com/Memmy-App/memmy/assets/55962871/b8e11a6e-71e0-41fc-a923-4000f9a353a1)

### Expected Behavior

To space out the comment by adding images to the bottom of the comment. Or by separating them out from the text in spacing.

### Version

0.5.1.1

### App Store or TestFlight?

App Store

### iOS Version

17.x Beta

### Device

iPhone 12

**Comment by eoddc5** [comment]
No title
