### ISSUE TITLE
[Feature Request] Add option to mark posts as read when opening a link

### ISSUE THREAD

**Issue by chibimagic** [Memmy-App/memmy#981]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Mark read settings:
Mark Read on Post Open ✅ 
Mark Read on Image View ✅ 
Mark Read on Vote ✅ 
Mark Read in Feed Scroll ❌ 
Mark Read on Community Scroll ❌ 

1. Have a post in the feed that is a link
2. Open the link by tapping it
3. Go back to the feed

### Expected Behavior

Expected: Post is marked as read (blue book icon with checkmark appears)
Actual: Post is not marked as read (icon does not appear)

### Version

0.5.1 (1)

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPad mini

**Comment by sgriff96** [comment]
Technically not a bug, we just didn't add that as a feature

**Comment by gkasdorf** [comment]
This is done.
