### ISSUE TITLE
[Bug]: Can’t login to kbin.social

### ISSUE THREAD

**Issue by SpenHub** [Memmy-App/memmy#982]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

- Create an account with kbin.social
- Activate account
- Attempt to login with Memmy either at splash screen (onboarding) or accounts page in settings 
- (Screenshot is taken too late after failed login but I promise I entered my password! )
![image](https://github.com/Memmy-App/memmy/assets/3013039/835cc057-dac6-4583-97b7-2cb7a4411dfc)
![image](https://github.com/Memmy-App/memmy/assets/3013039/6f8d6602-ea67-47a4-8a79-ea299cec604f)

### Expected Behavior

I’m able to login to kbin.social

### Version

Latest AppStore

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

13 Mini

**Comment by eoddc5** [comment]
This is not a kbin app
