### ISSUE TITLE
[Bug]: Post Feed on NSFW Communities Borked when Blur NSFW enabled

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#984]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Visit a NSFW community with a lot of photos when blur NSFW is enabled. 

Scroll through the post feed and it’s borked (see example below)

### Expected Behavior

The feed would act as normal and not have the broken behavior. 

### Version

0.6.1 (1)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iPhone 13

**Comment by theycallmebeez** [comment]
https://github.com/Memmy-App/memmy/assets/382845/d451934b-e622-43ee-8c22-f0b5ce3e0c65

**Comment by eoddc5** [comment]
@theycallmebeez thr video doesn’t really show anything

**Comment by grouNDfx** [comment]
I’m experiencing a similar thing on the normal feed as well. If it’s a single blurred picture by itself, it just doesn’t render. If it’s multiple in a row it’s similar to the video posted above

**Comment by gkasdorf** [comment]
All these issues are fixed.
