### ISSUE TITLE
[Bug]: Favorite Communities - Star Not Filled and Can’t Unfavorite

### ISSUE THREAD

**Issue by theycallmebeez** [Memmy-App/memmy#985]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Open the community drawer.
Favorite a community. 
The star is not filled and unable to unfavorite. 

See below: 

https://github.com/Memmy-App/memmy/assets/382845/a46f48f6-3e1e-4373-9826-bb94c0b80c93

### Expected Behavior

Able to unfavorite. 

### Version

0.6.1 (1)

### App Store or TestFlight?

TestFlight

### iOS Version

17.x Beta

### Device

iphone 13

**Comment by eoddc5** [comment]
@theycallmebeez the video doesn’t really show anything

**Comment by theycallmebeez** [comment]
Okay, if you favorite a community it goes to favorites but the star isn’t filled and you cannot unfavorite.

**Comment by theycallmebeez** [comment]
it is not visual, it’s functional. cannot unfavorite a community once favorited.

**Comment by gkasdorf** [comment]
This is fixed.
