### ISSUE TITLE
[Bug] apostraphe causing issue with links

### ISSUE THREAD

**Issue by dannyh** [Memmy-App/memmy#989]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

https://startrek.website/comment/1555702

the link in this comment opens the Wikipedia page for China when viewing in Memmy. In Safari it opens the correct page for “China’s Final Warning” https://en.m.wikipedia.org/wiki/China's_final_warning

https://github.com/Memmy-App/memmy/assets/1106220/d3aaafcc-6730-4b3e-86fb-9f650c1c3207

### Expected Behavior

When I tap the link in that comment it goes to the Wikipedia article for China, not the page that is linked

### Version

0.5.1.1

### App Store or TestFlight?

App Store

### iOS Version

17.x Beta

### Device

iPhone 12 Pro Max

**Comment by datenstau** [comment]
Why is this considered as "medium priority"? Opening urls is the key function of Lemmy. A client which messes up urls is useless. 

This bug happens with every url containing special characters. Taz.de articles contain a "!" character, eg. 12ft.io urls have problems, too. 

Please consider this as a top priority!

**Comment by Felix-Staud** [comment]
> Why is this considered as "medium priority"? Opening urls is the key function of Lemmy. A client which messes up urls is useless.
> 
> This bug happens with every url containing special characters. Taz.de articles contain a "!" character, eg. 12ft.io urls have problems, too.
> 
> Please consider this as a top priority!

Personal opinion: Cause it doesn't break or crash the app.
Priorities are given not by UI/UX but by technical & security evaluation (sorry, that's normal)
Medium does not mean it's not being looked at, it just means that people can still use the app fine without this (e.g. copy the link manually)

**Comment by gkasdorf** [comment]
Links are handled better now with new markdown.
