### ISSUE TITLE
[Bug]: Share button Community crash the app

### ISSUE THREAD

**Issue by kingmath** [Memmy-App/memmy#996]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

When I press Share in the menu for the Community, the app crashes.

![IMG_1913](https://github.com/Memmy-App/memmy/assets/16158664/5d138dc2-e80a-421d-ad98-5944b1e37faa)

### Expected Behavior

I want to press share and the url for the community is copier the clipboard.

Unfortunately, the app crashes after pressing a button.

### Version

0.5.1(1)

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPhone 13

**Comment by eoddc5** [comment]
I can’t get this to replicate. 

@gkasdorf do you know how far off 0.6 release to the App Store is? Or 1.0?

I can’t test 0.5 but I know in 0.6 it doesn’t do this

**Comment by kingmath** [comment]
The Version 0.5.1 (1) is shown in the App.

![IMG_1918](https://github.com/Memmy-App/memmy/assets/16158664/02552f22-34ad-40da-a18b-da5268225a6e)

This is the latest version from the App Store.

![IMG_1919](https://github.com/Memmy-App/memmy/assets/16158664/d8779f04-233e-4de2-a452-35a018e7a104)
